// Code generated by Fern. DO NOT EDIT.

package auth

import (
	context "context"
	novabillinggo "github.com/novabilling/novabilling-go"
	core "github.com/novabilling/novabilling-go/core"
	internal "github.com/novabilling/novabilling-go/internal"
	option "github.com/novabilling/novabilling-go/option"
	http "net/http"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) Register(
	ctx context.Context,
	request *novabillinggo.RegisterDto,
	opts ...option.RequestOption,
) (*core.Response[*novabillinggo.RegisterResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.novabilling.one",
	)
	endpointURL := baseURL + "/api/auth/register"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *novabillinggo.RegisterResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(novabillinggo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*novabillinggo.RegisterResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Login(
	ctx context.Context,
	request *novabillinggo.LoginDto,
	opts ...option.RequestOption,
) (*core.Response[*novabillinggo.LoginResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.novabilling.one",
	)
	endpointURL := baseURL + "/api/auth/login"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *novabillinggo.LoginResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(novabillinggo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*novabillinggo.LoginResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) RefreshToken(
	ctx context.Context,
	request *novabillinggo.RefreshTokenDto,
	opts ...option.RequestOption,
) (*core.Response[*novabillinggo.TokenPairResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.novabilling.one",
	)
	endpointURL := baseURL + "/api/auth/refresh"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *novabillinggo.TokenPairResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(novabillinggo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*novabillinggo.TokenPairResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ForgotPassword(
	ctx context.Context,
	request *novabillinggo.ForgotPasswordDto,
	opts ...option.RequestOption,
) (*core.Response[*novabillinggo.MessageResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.novabilling.one",
	)
	endpointURL := baseURL + "/api/auth/forgot-password"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *novabillinggo.MessageResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*novabillinggo.MessageResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ResetPassword(
	ctx context.Context,
	request *novabillinggo.ResetPasswordDto,
	opts ...option.RequestOption,
) (*core.Response[*novabillinggo.MessageResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.novabilling.one",
	)
	endpointURL := baseURL + "/api/auth/reset-password"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *novabillinggo.MessageResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(novabillinggo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*novabillinggo.MessageResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
