/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.events;

import com.fasterxml.jackson.core.JsonProcessingException;
import core.ClientOptions;
import core.MediaTypes;
import core.NovabillingApiApiException;
import core.NovabillingApiException;
import core.NovabillingApiHttpResponse;
import core.ObjectMappers;
import core.QueryStringMapper;
import core.RequestOptions;
import errors.NotFoundError;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import java.lang.Void;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import resources.events.requests.BatchEventsDto;
import resources.events.requests.GetBySubscriptionEventsRequest;
import resources.events.requests.GetEventsRequest;
import types.BatchEventResponse;
import types.CreateEventDto;
import types.PaginatedUsageEventResponse;
import types.UsageEventResponse;

public class RawEventsClient {
  protected final ClientOptions clientOptions;

  public RawEventsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public NovabillingApiHttpResponse<Void> list() {
    return list(null);
  }

  public NovabillingApiHttpResponse<Void> list(RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("api/events");if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        if (response.isSuccessful()) {
          return new NovabillingApiHttpResponse<>(null, response);
        }
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (IOException e) {
        throw new NovabillingApiException("Network error executing HTTP request", e);
      }
    }

    /**
     * Send a single usage event. Uses transactionId for idempotency - sending the same transactionId twice will return the existing event.
     */
    public NovabillingApiHttpResponse<UsageEventResponse> create(CreateEventDto request) {
      return create(request,null);
    }

    /**
     * Send a single usage event. Uses transactionId for idempotency - sending the same transactionId twice will return the existing event.
     */
    public NovabillingApiHttpResponse<UsageEventResponse> create(CreateEventDto request,
        RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("api/events");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        RequestBody body;
        try {
          body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        }
        catch(JsonProcessingException e) {
          throw new NovabillingApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
          .url(httpUrl.build())
          .method("POST", body)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json")
          .addHeader("Accept", "application/json")
          .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          if (response.isSuccessful()) {
            return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, UsageEventResponse.class), response);
          }
          try {
            if (response.code() == 404) {
              throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            }
          }
          catch (JsonProcessingException ignored) {
            // unable to map error response, throwing generic error
          }
          Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
          throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
        }
        catch (IOException e) {
          throw new NovabillingApiException("Network error executing HTTP request", e);
        }
      }

      /**
       * Send up to 100 usage events in a single request. Each event is processed independently - failures do not affect other events.
       */
      public NovabillingApiHttpResponse<BatchEventResponse> createBatch(BatchEventsDto request) {
        return createBatch(request,null);
      }

      /**
       * Send up to 100 usage events in a single request. Each event is processed independently - failures do not affect other events.
       */
      public NovabillingApiHttpResponse<BatchEventResponse> createBatch(BatchEventsDto request,
          RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("api/events/batch");if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          RequestBody body;
          try {
            body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
          }
          catch(JsonProcessingException e) {
            throw new NovabillingApiException("Failed to serialize request", e);
          }
          Request okhttpRequest = new Request.Builder()
            .url(httpUrl.build())
            .method("POST", body)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json")
            .addHeader("Accept", "application/json")
            .build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, BatchEventResponse.class), response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
          }
          catch (IOException e) {
            throw new NovabillingApiException("Network error executing HTTP request", e);
          }
        }

        /**
         * Retrieve a single usage event by its ID.
         */
        public NovabillingApiHttpResponse<UsageEventResponse> get(String id) {
          return get(id,GetEventsRequest.builder().build());
        }

        /**
         * Retrieve a single usage event by its ID.
         */
        public NovabillingApiHttpResponse<UsageEventResponse> get(String id,
            RequestOptions requestOptions) {
          return get(id,GetEventsRequest.builder().build(),requestOptions);
        }

        /**
         * Retrieve a single usage event by its ID.
         */
        public NovabillingApiHttpResponse<UsageEventResponse> get(String id,
            GetEventsRequest request) {
          return get(id,request,null);
        }

        /**
         * Retrieve a single usage event by its ID.
         */
        public NovabillingApiHttpResponse<UsageEventResponse> get(String id,
            GetEventsRequest request, RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("api/events")
            .addPathSegment(id);if (requestOptions != null) {
              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
              } );
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("GET", null)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Accept", "application/json");
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            try (Response response = client.newCall(okhttpRequest).execute()) {
              ResponseBody responseBody = response.body();
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              if (response.isSuccessful()) {
                return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, UsageEventResponse.class), response);
              }
              try {
                if (response.code() == 404) {
                  throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
            }
            catch (IOException e) {
              throw new NovabillingApiException("Network error executing HTTP request", e);
            }
          }

          /**
           * Retrieve usage events for a specific subscription with optional filtering.
           */
          public NovabillingApiHttpResponse<PaginatedUsageEventResponse> getBySubscription(
              String subscriptionId) {
            return getBySubscription(subscriptionId,GetBySubscriptionEventsRequest.builder().build());
          }

          /**
           * Retrieve usage events for a specific subscription with optional filtering.
           */
          public NovabillingApiHttpResponse<PaginatedUsageEventResponse> getBySubscription(
              String subscriptionId, RequestOptions requestOptions) {
            return getBySubscription(subscriptionId,GetBySubscriptionEventsRequest.builder().build(),requestOptions);
          }

          /**
           * Retrieve usage events for a specific subscription with optional filtering.
           */
          public NovabillingApiHttpResponse<PaginatedUsageEventResponse> getBySubscription(
              String subscriptionId, GetBySubscriptionEventsRequest request) {
            return getBySubscription(subscriptionId,request,null);
          }

          /**
           * Retrieve usage events for a specific subscription with optional filtering.
           */
          public NovabillingApiHttpResponse<PaginatedUsageEventResponse> getBySubscription(
              String subscriptionId, GetBySubscriptionEventsRequest request,
              RequestOptions requestOptions) {
            HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("api/events/subscription")
              .addPathSegment(subscriptionId);if (request.getCode().isPresent()) {
                QueryStringMapper.addQueryParameter(httpUrl, "code", request.getCode().get(), false);
              }
              if (request.getFrom().isPresent()) {
                QueryStringMapper.addQueryParameter(httpUrl, "from", request.getFrom().get(), false);
              }
              if (request.getTo().isPresent()) {
                QueryStringMapper.addQueryParameter(httpUrl, "to", request.getTo().get(), false);
              }
              if (request.getPage().isPresent()) {
                QueryStringMapper.addQueryParameter(httpUrl, "page", request.getPage().get(), false);
              }
              if (request.getPerPage().isPresent()) {
                QueryStringMapper.addQueryParameter(httpUrl, "perPage", request.getPerPage().get(), false);
              }
              if (requestOptions != null) {
                requestOptions.getQueryParameters().forEach((_key, _value) -> {
                  httpUrl.addQueryParameter(_key, _value);
                } );
              }
              Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
              Request okhttpRequest = _requestBuilder.build();
              OkHttpClient client = clientOptions.httpClient();
              if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
              }
              try (Response response = client.newCall(okhttpRequest).execute()) {
                ResponseBody responseBody = response.body();
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                if (response.isSuccessful()) {
                  return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PaginatedUsageEventResponse.class), response);
                }
                Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
              }
              catch (IOException e) {
                throw new NovabillingApiException("Network error executing HTTP request", e);
              }
            }
          }
