/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.subscriptions;

import com.fasterxml.jackson.core.JsonProcessingException;
import core.ClientOptions;
import core.MediaTypes;
import core.NovabillingApiApiException;
import core.NovabillingApiException;
import core.NovabillingApiHttpResponse;
import core.ObjectMappers;
import core.QueryStringMapper;
import core.RequestOptions;
import errors.BadRequestError;
import errors.NotFoundError;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import resources.subscriptions.requests.CancelSubscriptionDto;
import resources.subscriptions.requests.ChangePlanDto;
import resources.subscriptions.requests.CreateSubscriptionDto;
import resources.subscriptions.requests.GetSubscriptionsRequest;
import resources.subscriptions.requests.ListSubscriptionsRequest;
import resources.subscriptions.requests.PauseSubscriptionsRequest;
import resources.subscriptions.requests.ResumeSubscriptionsRequest;
import resources.subscriptions.requests.UpdateSubscriptionDto;
import types.PaginatedSubscriptionResponse;
import types.SubscriptionResponse;

public class RawSubscriptionsClient {
  protected final ClientOptions clientOptions;

  public RawSubscriptionsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Retrieve a paginated list of subscriptions. Supports filtering by status, customer, and plan.
   */
  public NovabillingApiHttpResponse<PaginatedSubscriptionResponse> list() {
    return list(ListSubscriptionsRequest.builder().build());
  }

  /**
   * Retrieve a paginated list of subscriptions. Supports filtering by status, customer, and plan.
   */
  public NovabillingApiHttpResponse<PaginatedSubscriptionResponse> list(
      RequestOptions requestOptions) {
    return list(ListSubscriptionsRequest.builder().build(),requestOptions);
  }

  /**
   * Retrieve a paginated list of subscriptions. Supports filtering by status, customer, and plan.
   */
  public NovabillingApiHttpResponse<PaginatedSubscriptionResponse> list(
      ListSubscriptionsRequest request) {
    return list(request,null);
  }

  /**
   * Retrieve a paginated list of subscriptions. Supports filtering by status, customer, and plan.
   */
  public NovabillingApiHttpResponse<PaginatedSubscriptionResponse> list(
      ListSubscriptionsRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("api/subscriptions");if (request.getStatus().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "status", request.getStatus().get(), false);
      }
      if (request.getCustomerId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "customerId", request.getCustomerId().get(), false);
      }
      if (request.getPlanId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "planId", request.getPlanId().get(), false);
      }
      if (request.getPage().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "page", request.getPage().get(), false);
      }
      if (request.getLimit().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
      }
      if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        if (response.isSuccessful()) {
          return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PaginatedSubscriptionResponse.class), response);
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (IOException e) {
        throw new NovabillingApiException("Network error executing HTTP request", e);
      }
    }

    /**
     * Subscribe a customer to a plan. The plan must have a price matching the specified currency. Optionally set a trial period in days.
     */
    public NovabillingApiHttpResponse<SubscriptionResponse> create(CreateSubscriptionDto request) {
      return create(request,null);
    }

    /**
     * Subscribe a customer to a plan. The plan must have a price matching the specified currency. Optionally set a trial period in days.
     */
    public NovabillingApiHttpResponse<SubscriptionResponse> create(CreateSubscriptionDto request,
        RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("api/subscriptions");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        RequestBody body;
        try {
          body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        }
        catch(JsonProcessingException e) {
          throw new NovabillingApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
          .url(httpUrl.build())
          .method("POST", body)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json")
          .addHeader("Accept", "application/json")
          .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          if (response.isSuccessful()) {
            return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SubscriptionResponse.class), response);
          }
          try {
            switch (response.code()) {
              case 400:throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            }
          }
          catch (JsonProcessingException ignored) {
            // unable to map error response, throwing generic error
          }
          Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
          throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
        }
        catch (IOException e) {
          throw new NovabillingApiException("Network error executing HTTP request", e);
        }
      }

      /**
       * Retrieve detailed subscription information including customer, plan with prices, and recent invoices.
       */
      public NovabillingApiHttpResponse<SubscriptionResponse> get(String id) {
        return get(id,GetSubscriptionsRequest.builder().build());
      }

      /**
       * Retrieve detailed subscription information including customer, plan with prices, and recent invoices.
       */
      public NovabillingApiHttpResponse<SubscriptionResponse> get(String id,
          RequestOptions requestOptions) {
        return get(id,GetSubscriptionsRequest.builder().build(),requestOptions);
      }

      /**
       * Retrieve detailed subscription information including customer, plan with prices, and recent invoices.
       */
      public NovabillingApiHttpResponse<SubscriptionResponse> get(String id,
          GetSubscriptionsRequest request) {
        return get(id,request,null);
      }

      /**
       * Retrieve detailed subscription information including customer, plan with prices, and recent invoices.
       */
      public NovabillingApiHttpResponse<SubscriptionResponse> get(String id,
          GetSubscriptionsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("api/subscriptions")
          .addPathSegment(id);if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Accept", "application/json");
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SubscriptionResponse.class), response);
            }
            try {
              if (response.code() == 404) {
                throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
          }
          catch (IOException e) {
            throw new NovabillingApiException("Network error executing HTTP request", e);
          }
        }

        /**
         * Update the metadata field on a subscription. Other fields cannot be changed directly.
         */
        public NovabillingApiHttpResponse<SubscriptionResponse> update(String id) {
          return update(id,UpdateSubscriptionDto.builder().build());
        }

        /**
         * Update the metadata field on a subscription. Other fields cannot be changed directly.
         */
        public NovabillingApiHttpResponse<SubscriptionResponse> update(String id,
            RequestOptions requestOptions) {
          return update(id,UpdateSubscriptionDto.builder().build(),requestOptions);
        }

        /**
         * Update the metadata field on a subscription. Other fields cannot be changed directly.
         */
        public NovabillingApiHttpResponse<SubscriptionResponse> update(String id,
            UpdateSubscriptionDto request) {
          return update(id,request,null);
        }

        /**
         * Update the metadata field on a subscription. Other fields cannot be changed directly.
         */
        public NovabillingApiHttpResponse<SubscriptionResponse> update(String id,
            UpdateSubscriptionDto request, RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("api/subscriptions")
            .addPathSegment(id);if (requestOptions != null) {
              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
              } );
            }
            RequestBody body;
            try {
              body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
            }
            catch(JsonProcessingException e) {
              throw new NovabillingApiException("Failed to serialize request", e);
            }
            Request okhttpRequest = new Request.Builder()
              .url(httpUrl.build())
              .method("PATCH", body)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Content-Type", "application/json")
              .addHeader("Accept", "application/json")
              .build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            try (Response response = client.newCall(okhttpRequest).execute()) {
              ResponseBody responseBody = response.body();
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              if (response.isSuccessful()) {
                return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SubscriptionResponse.class), response);
              }
              try {
                if (response.code() == 404) {
                  throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
            }
            catch (IOException e) {
              throw new NovabillingApiException("Network error executing HTTP request", e);
            }
          }

          /**
           * Cancel a subscription either immediately or at the end of the current billing period. When set to &quot;period_end&quot;, the subscription remains active until the current period expires.
           */
          public NovabillingApiHttpResponse<SubscriptionResponse> cancel(String id,
              CancelSubscriptionDto request) {
            return cancel(id,request,null);
          }

          /**
           * Cancel a subscription either immediately or at the end of the current billing period. When set to &quot;period_end&quot;, the subscription remains active until the current period expires.
           */
          public NovabillingApiHttpResponse<SubscriptionResponse> cancel(String id,
              CancelSubscriptionDto request, RequestOptions requestOptions) {
            HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("api/subscriptions")
              .addPathSegment(id)
              .addPathSegments("cancel");if (requestOptions != null) {
                requestOptions.getQueryParameters().forEach((_key, _value) -> {
                  httpUrl.addQueryParameter(_key, _value);
                } );
              }
              RequestBody body;
              try {
                body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
              }
              catch(JsonProcessingException e) {
                throw new NovabillingApiException("Failed to serialize request", e);
              }
              Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
              OkHttpClient client = clientOptions.httpClient();
              if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
              }
              try (Response response = client.newCall(okhttpRequest).execute()) {
                ResponseBody responseBody = response.body();
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                if (response.isSuccessful()) {
                  return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SubscriptionResponse.class), response);
                }
                try {
                  switch (response.code()) {
                    case 400:throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                  }
                }
                catch (JsonProcessingException ignored) {
                  // unable to map error response, throwing generic error
                }
                Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
              }
              catch (IOException e) {
                throw new NovabillingApiException("Network error executing HTTP request", e);
              }
            }

            /**
             * Temporarily pause an active subscription. Only active subscriptions can be paused.
             */
            public NovabillingApiHttpResponse<SubscriptionResponse> pause(String id) {
              return pause(id,PauseSubscriptionsRequest.builder().build());
            }

            /**
             * Temporarily pause an active subscription. Only active subscriptions can be paused.
             */
            public NovabillingApiHttpResponse<SubscriptionResponse> pause(String id,
                RequestOptions requestOptions) {
              return pause(id,PauseSubscriptionsRequest.builder().build(),requestOptions);
            }

            /**
             * Temporarily pause an active subscription. Only active subscriptions can be paused.
             */
            public NovabillingApiHttpResponse<SubscriptionResponse> pause(String id,
                PauseSubscriptionsRequest request) {
              return pause(id,request,null);
            }

            /**
             * Temporarily pause an active subscription. Only active subscriptions can be paused.
             */
            public NovabillingApiHttpResponse<SubscriptionResponse> pause(String id,
                PauseSubscriptionsRequest request, RequestOptions requestOptions) {
              HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                .addPathSegments("api/subscriptions")
                .addPathSegment(id)
                .addPathSegments("pause");if (requestOptions != null) {
                  requestOptions.getQueryParameters().forEach((_key, _value) -> {
                    httpUrl.addQueryParameter(_key, _value);
                  } );
                }
                Request.Builder _requestBuilder = new Request.Builder()
                  .url(httpUrl.build())
                  .method("POST", RequestBody.create("", null))
                  .headers(Headers.of(clientOptions.headers(requestOptions)))
                  .addHeader("Accept", "application/json");
                Request okhttpRequest = _requestBuilder.build();
                OkHttpClient client = clientOptions.httpClient();
                if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                  client = clientOptions.httpClientWithTimeout(requestOptions);
                }
                try (Response response = client.newCall(okhttpRequest).execute()) {
                  ResponseBody responseBody = response.body();
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  if (response.isSuccessful()) {
                    return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SubscriptionResponse.class), response);
                  }
                  try {
                    switch (response.code()) {
                      case 400:throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                      case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    }
                  }
                  catch (JsonProcessingException ignored) {
                    // unable to map error response, throwing generic error
                  }
                  Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                  throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                }
                catch (IOException e) {
                  throw new NovabillingApiException("Network error executing HTTP request", e);
                }
              }

              /**
               * Resume a previously paused subscription back to active status.
               */
              public NovabillingApiHttpResponse<SubscriptionResponse> resume(String id) {
                return resume(id,ResumeSubscriptionsRequest.builder().build());
              }

              /**
               * Resume a previously paused subscription back to active status.
               */
              public NovabillingApiHttpResponse<SubscriptionResponse> resume(String id,
                  RequestOptions requestOptions) {
                return resume(id,ResumeSubscriptionsRequest.builder().build(),requestOptions);
              }

              /**
               * Resume a previously paused subscription back to active status.
               */
              public NovabillingApiHttpResponse<SubscriptionResponse> resume(String id,
                  ResumeSubscriptionsRequest request) {
                return resume(id,request,null);
              }

              /**
               * Resume a previously paused subscription back to active status.
               */
              public NovabillingApiHttpResponse<SubscriptionResponse> resume(String id,
                  ResumeSubscriptionsRequest request, RequestOptions requestOptions) {
                HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                  .addPathSegments("api/subscriptions")
                  .addPathSegment(id)
                  .addPathSegments("resume");if (requestOptions != null) {
                    requestOptions.getQueryParameters().forEach((_key, _value) -> {
                      httpUrl.addQueryParameter(_key, _value);
                    } );
                  }
                  Request.Builder _requestBuilder = new Request.Builder()
                    .url(httpUrl.build())
                    .method("POST", RequestBody.create("", null))
                    .headers(Headers.of(clientOptions.headers(requestOptions)))
                    .addHeader("Accept", "application/json");
                  Request okhttpRequest = _requestBuilder.build();
                  OkHttpClient client = clientOptions.httpClient();
                  if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                    client = clientOptions.httpClientWithTimeout(requestOptions);
                  }
                  try (Response response = client.newCall(okhttpRequest).execute()) {
                    ResponseBody responseBody = response.body();
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                      return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SubscriptionResponse.class), response);
                    }
                    try {
                      switch (response.code()) {
                        case 400:throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                        case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                      }
                    }
                    catch (JsonProcessingException ignored) {
                      // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                  }
                  catch (IOException e) {
                    throw new NovabillingApiException("Network error executing HTTP request", e);
                  }
                }

                /**
                 * Switch a subscription to a different plan. The new plan must have a price for the subscription's currency. A new billing period starts immediately with the new plan.
                 */
                public NovabillingApiHttpResponse<SubscriptionResponse> changePlan(String id,
                    ChangePlanDto request) {
                  return changePlan(id,request,null);
                }

                /**
                 * Switch a subscription to a different plan. The new plan must have a price for the subscription's currency. A new billing period starts immediately with the new plan.
                 */
                public NovabillingApiHttpResponse<SubscriptionResponse> changePlan(String id,
                    ChangePlanDto request, RequestOptions requestOptions) {
                  HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                    .addPathSegments("api/subscriptions")
                    .addPathSegment(id)
                    .addPathSegments("change-plan");if (requestOptions != null) {
                      requestOptions.getQueryParameters().forEach((_key, _value) -> {
                        httpUrl.addQueryParameter(_key, _value);
                      } );
                    }
                    RequestBody body;
                    try {
                      body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
                    }
                    catch(JsonProcessingException e) {
                      throw new NovabillingApiException("Failed to serialize request", e);
                    }
                    Request okhttpRequest = new Request.Builder()
                      .url(httpUrl.build())
                      .method("POST", body)
                      .headers(Headers.of(clientOptions.headers(requestOptions)))
                      .addHeader("Content-Type", "application/json")
                      .addHeader("Accept", "application/json")
                      .build();
                    OkHttpClient client = clientOptions.httpClient();
                    if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                      client = clientOptions.httpClientWithTimeout(requestOptions);
                    }
                    try (Response response = client.newCall(okhttpRequest).execute()) {
                      ResponseBody responseBody = response.body();
                      String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                      if (response.isSuccessful()) {
                        return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SubscriptionResponse.class), response);
                      }
                      try {
                        switch (response.code()) {
                          case 400:throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                          case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                        }
                      }
                      catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                      }
                      Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                      throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                    }
                    catch (IOException e) {
                      throw new NovabillingApiException("Network error executing HTTP request", e);
                    }
                  }
                }
