/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.invoices.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListInvoicesRequest.Builder.class
)
public final class ListInvoicesRequest {
  private final Optional<String> status;

  private final Optional<String> customerId;

  private final Optional<String> dateFrom;

  private final Optional<String> dateTo;

  private final Optional<Double> page;

  private final Optional<Double> limit;

  private final Map<String, Object> additionalProperties;

  private ListInvoicesRequest(Optional<String> status, Optional<String> customerId,
      Optional<String> dateFrom, Optional<String> dateTo, Optional<Double> page,
      Optional<Double> limit, Map<String, Object> additionalProperties) {
    this.status = status;
    this.customerId = customerId;
    this.dateFrom = dateFrom;
    this.dateTo = dateTo;
    this.page = page;
    this.limit = limit;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("status")
  public Optional<String> getStatus() {
    return status;
  }

  @JsonProperty("customerId")
  public Optional<String> getCustomerId() {
    return customerId;
  }

  @JsonProperty("dateFrom")
  public Optional<String> getDateFrom() {
    return dateFrom;
  }

  @JsonProperty("dateTo")
  public Optional<String> getDateTo() {
    return dateTo;
  }

  @JsonProperty("page")
  public Optional<Double> getPage() {
    return page;
  }

  @JsonProperty("limit")
  public Optional<Double> getLimit() {
    return limit;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListInvoicesRequest && equalTo((ListInvoicesRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListInvoicesRequest other) {
    return status.equals(other.status) && customerId.equals(other.customerId) && dateFrom.equals(other.dateFrom) && dateTo.equals(other.dateTo) && page.equals(other.page) && limit.equals(other.limit);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.status, this.customerId, this.dateFrom, this.dateTo, this.page, this.limit);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> status = Optional.empty();

    private Optional<String> customerId = Optional.empty();

    private Optional<String> dateFrom = Optional.empty();

    private Optional<String> dateTo = Optional.empty();

    private Optional<Double> page = Optional.empty();

    private Optional<Double> limit = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ListInvoicesRequest other) {
      status(other.getStatus());
      customerId(other.getCustomerId());
      dateFrom(other.getDateFrom());
      dateTo(other.getDateTo());
      page(other.getPage());
      limit(other.getLimit());
      return this;
    }

    @JsonSetter(
        value = "status",
        nulls = Nulls.SKIP
    )
    public Builder status(Optional<String> status) {
      this.status = status;
      return this;
    }

    public Builder status(String status) {
      this.status = Optional.ofNullable(status);
      return this;
    }

    @JsonSetter(
        value = "customerId",
        nulls = Nulls.SKIP
    )
    public Builder customerId(Optional<String> customerId) {
      this.customerId = customerId;
      return this;
    }

    public Builder customerId(String customerId) {
      this.customerId = Optional.ofNullable(customerId);
      return this;
    }

    @JsonSetter(
        value = "dateFrom",
        nulls = Nulls.SKIP
    )
    public Builder dateFrom(Optional<String> dateFrom) {
      this.dateFrom = dateFrom;
      return this;
    }

    public Builder dateFrom(String dateFrom) {
      this.dateFrom = Optional.ofNullable(dateFrom);
      return this;
    }

    @JsonSetter(
        value = "dateTo",
        nulls = Nulls.SKIP
    )
    public Builder dateTo(Optional<String> dateTo) {
      this.dateTo = dateTo;
      return this;
    }

    public Builder dateTo(String dateTo) {
      this.dateTo = Optional.ofNullable(dateTo);
      return this;
    }

    @JsonSetter(
        value = "page",
        nulls = Nulls.SKIP
    )
    public Builder page(Optional<Double> page) {
      this.page = page;
      return this;
    }

    public Builder page(Double page) {
      this.page = Optional.ofNullable(page);
      return this;
    }

    @JsonSetter(
        value = "limit",
        nulls = Nulls.SKIP
    )
    public Builder limit(Optional<Double> limit) {
      this.limit = limit;
      return this;
    }

    public Builder limit(Double limit) {
      this.limit = Optional.ofNullable(limit);
      return this;
    }

    public ListInvoicesRequest build() {
      return new ListInvoicesRequest(status, customerId, dateFrom, dateTo, page, limit, additionalProperties);
    }
  }
}
