/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.coupons.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;
import resources.coupons.types.CreateCouponDtoDiscountType;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateCouponDto.Builder.class
)
public final class CreateCouponDto {
  private final String code;

  private final String name;

  private final Optional<String> description;

  private final CreateCouponDtoDiscountType discountType;

  private final double discountValue;

  private final Optional<String> currency;

  private final Optional<Double> maxRedemptions;

  private final Optional<List<String>> appliesToPlanIds;

  private final Optional<String> expiresAt;

  private final Optional<String> createdAt;

  private final Map<String, Object> additionalProperties;

  private CreateCouponDto(String code, String name, Optional<String> description,
      CreateCouponDtoDiscountType discountType, double discountValue, Optional<String> currency,
      Optional<Double> maxRedemptions, Optional<List<String>> appliesToPlanIds,
      Optional<String> expiresAt, Optional<String> createdAt,
      Map<String, Object> additionalProperties) {
    this.code = code;
    this.name = name;
    this.description = description;
    this.discountType = discountType;
    this.discountValue = discountValue;
    this.currency = currency;
    this.maxRedemptions = maxRedemptions;
    this.appliesToPlanIds = appliesToPlanIds;
    this.expiresAt = expiresAt;
    this.createdAt = createdAt;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Unique coupon code
   */
  @JsonProperty("code")
  public String getCode() {
    return code;
  }

  /**
   * @return Display name
   */
  @JsonProperty("name")
  public String getName() {
    return name;
  }

  @JsonProperty("description")
  public Optional<String> getDescription() {
    return description;
  }

  @JsonProperty("discountType")
  public CreateCouponDtoDiscountType getDiscountType() {
    return discountType;
  }

  /**
   * @return Discount value (percentage 0-100 or fixed amount)
   */
  @JsonProperty("discountValue")
  public double getDiscountValue() {
    return discountValue;
  }

  /**
   * @return Currency for FIXED_AMOUNT discounts
   */
  @JsonProperty("currency")
  public Optional<String> getCurrency() {
    return currency;
  }

  /**
   * @return Max number of redemptions (null = unlimited)
   */
  @JsonProperty("maxRedemptions")
  public Optional<Double> getMaxRedemptions() {
    return maxRedemptions;
  }

  /**
   * @return Plan IDs this coupon applies to (empty = all)
   */
  @JsonProperty("appliesToPlanIds")
  public Optional<List<String>> getAppliesToPlanIds() {
    return appliesToPlanIds;
  }

  @JsonProperty("expiresAt")
  public Optional<String> getExpiresAt() {
    return expiresAt;
  }

  /**
   * @return Backdate createdAt (ISO 8601). For data imports.
   */
  @JsonProperty("createdAt")
  public Optional<String> getCreatedAt() {
    return createdAt;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateCouponDto && equalTo((CreateCouponDto) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateCouponDto other) {
    return code.equals(other.code) && name.equals(other.name) && description.equals(other.description) && discountType.equals(other.discountType) && discountValue == other.discountValue && currency.equals(other.currency) && maxRedemptions.equals(other.maxRedemptions) && appliesToPlanIds.equals(other.appliesToPlanIds) && expiresAt.equals(other.expiresAt) && createdAt.equals(other.createdAt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.code, this.name, this.description, this.discountType, this.discountValue, this.currency, this.maxRedemptions, this.appliesToPlanIds, this.expiresAt, this.createdAt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static CodeStage builder() {
    return new Builder();
  }

  public interface CodeStage {
    /**
     * <p>Unique coupon code</p>
     */
    NameStage code(@NotNull String code);

    Builder from(CreateCouponDto other);
  }

  public interface NameStage {
    /**
     * <p>Display name</p>
     */
    DiscountTypeStage name(@NotNull String name);
  }

  public interface DiscountTypeStage {
    DiscountValueStage discountType(@NotNull CreateCouponDtoDiscountType discountType);
  }

  public interface DiscountValueStage {
    /**
     * <p>Discount value (percentage 0-100 or fixed amount)</p>
     */
    _FinalStage discountValue(double discountValue);
  }

  public interface _FinalStage {
    CreateCouponDto build();

    _FinalStage description(Optional<String> description);

    _FinalStage description(String description);

    /**
     * <p>Currency for FIXED_AMOUNT discounts</p>
     */
    _FinalStage currency(Optional<String> currency);

    _FinalStage currency(String currency);

    /**
     * <p>Max number of redemptions (null = unlimited)</p>
     */
    _FinalStage maxRedemptions(Optional<Double> maxRedemptions);

    _FinalStage maxRedemptions(Double maxRedemptions);

    /**
     * <p>Plan IDs this coupon applies to (empty = all)</p>
     */
    _FinalStage appliesToPlanIds(Optional<List<String>> appliesToPlanIds);

    _FinalStage appliesToPlanIds(List<String> appliesToPlanIds);

    _FinalStage expiresAt(Optional<String> expiresAt);

    _FinalStage expiresAt(String expiresAt);

    /**
     * <p>Backdate createdAt (ISO 8601). For data imports.</p>
     */
    _FinalStage createdAt(Optional<String> createdAt);

    _FinalStage createdAt(String createdAt);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements CodeStage, NameStage, DiscountTypeStage, DiscountValueStage, _FinalStage {
    private String code;

    private String name;

    private CreateCouponDtoDiscountType discountType;

    private double discountValue;

    private Optional<String> createdAt = Optional.empty();

    private Optional<String> expiresAt = Optional.empty();

    private Optional<List<String>> appliesToPlanIds = Optional.empty();

    private Optional<Double> maxRedemptions = Optional.empty();

    private Optional<String> currency = Optional.empty();

    private Optional<String> description = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateCouponDto other) {
      code(other.getCode());
      name(other.getName());
      description(other.getDescription());
      discountType(other.getDiscountType());
      discountValue(other.getDiscountValue());
      currency(other.getCurrency());
      maxRedemptions(other.getMaxRedemptions());
      appliesToPlanIds(other.getAppliesToPlanIds());
      expiresAt(other.getExpiresAt());
      createdAt(other.getCreatedAt());
      return this;
    }

    /**
     * <p>Unique coupon code</p>
     * <p>Unique coupon code</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("code")
    public NameStage code(@NotNull String code) {
      this.code = Objects.requireNonNull(code, "code must not be null");
      return this;
    }

    /**
     * <p>Display name</p>
     * <p>Display name</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("name")
    public DiscountTypeStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("discountType")
    public DiscountValueStage discountType(@NotNull CreateCouponDtoDiscountType discountType) {
      this.discountType = Objects.requireNonNull(discountType, "discountType must not be null");
      return this;
    }

    /**
     * <p>Discount value (percentage 0-100 or fixed amount)</p>
     * <p>Discount value (percentage 0-100 or fixed amount)</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("discountValue")
    public _FinalStage discountValue(double discountValue) {
      this.discountValue = discountValue;
      return this;
    }

    /**
     * <p>Backdate createdAt (ISO 8601). For data imports.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage createdAt(String createdAt) {
      this.createdAt = Optional.ofNullable(createdAt);
      return this;
    }

    /**
     * <p>Backdate createdAt (ISO 8601). For data imports.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "createdAt",
        nulls = Nulls.SKIP
    )
    public _FinalStage createdAt(Optional<String> createdAt) {
      this.createdAt = createdAt;
      return this;
    }

    @java.lang.Override
    public _FinalStage expiresAt(String expiresAt) {
      this.expiresAt = Optional.ofNullable(expiresAt);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "expiresAt",
        nulls = Nulls.SKIP
    )
    public _FinalStage expiresAt(Optional<String> expiresAt) {
      this.expiresAt = expiresAt;
      return this;
    }

    /**
     * <p>Plan IDs this coupon applies to (empty = all)</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage appliesToPlanIds(List<String> appliesToPlanIds) {
      this.appliesToPlanIds = Optional.ofNullable(appliesToPlanIds);
      return this;
    }

    /**
     * <p>Plan IDs this coupon applies to (empty = all)</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "appliesToPlanIds",
        nulls = Nulls.SKIP
    )
    public _FinalStage appliesToPlanIds(Optional<List<String>> appliesToPlanIds) {
      this.appliesToPlanIds = appliesToPlanIds;
      return this;
    }

    /**
     * <p>Max number of redemptions (null = unlimited)</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage maxRedemptions(Double maxRedemptions) {
      this.maxRedemptions = Optional.ofNullable(maxRedemptions);
      return this;
    }

    /**
     * <p>Max number of redemptions (null = unlimited)</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "maxRedemptions",
        nulls = Nulls.SKIP
    )
    public _FinalStage maxRedemptions(Optional<Double> maxRedemptions) {
      this.maxRedemptions = maxRedemptions;
      return this;
    }

    /**
     * <p>Currency for FIXED_AMOUNT discounts</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage currency(String currency) {
      this.currency = Optional.ofNullable(currency);
      return this;
    }

    /**
     * <p>Currency for FIXED_AMOUNT discounts</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "currency",
        nulls = Nulls.SKIP
    )
    public _FinalStage currency(Optional<String> currency) {
      this.currency = currency;
      return this;
    }

    @java.lang.Override
    public _FinalStage description(String description) {
      this.description = Optional.ofNullable(description);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "description",
        nulls = Nulls.SKIP
    )
    public _FinalStage description(Optional<String> description) {
      this.description = description;
      return this;
    }

    @java.lang.Override
    public CreateCouponDto build() {
      return new CreateCouponDto(code, name, description, discountType, discountValue, currency, maxRedemptions, appliesToPlanIds, expiresAt, createdAt, additionalProperties);
    }
  }
}
