/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.coupons.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListCouponsRequest.Builder.class
)
public final class ListCouponsRequest {
  private final Optional<Boolean> isActive;

  private final Optional<Double> page;

  private final Optional<Double> limit;

  private final Map<String, Object> additionalProperties;

  private ListCouponsRequest(Optional<Boolean> isActive, Optional<Double> page,
      Optional<Double> limit, Map<String, Object> additionalProperties) {
    this.isActive = isActive;
    this.page = page;
    this.limit = limit;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("isActive")
  public Optional<Boolean> getIsActive() {
    return isActive;
  }

  @JsonProperty("page")
  public Optional<Double> getPage() {
    return page;
  }

  @JsonProperty("limit")
  public Optional<Double> getLimit() {
    return limit;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListCouponsRequest && equalTo((ListCouponsRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListCouponsRequest other) {
    return isActive.equals(other.isActive) && page.equals(other.page) && limit.equals(other.limit);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.isActive, this.page, this.limit);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Boolean> isActive = Optional.empty();

    private Optional<Double> page = Optional.empty();

    private Optional<Double> limit = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ListCouponsRequest other) {
      isActive(other.getIsActive());
      page(other.getPage());
      limit(other.getLimit());
      return this;
    }

    @JsonSetter(
        value = "isActive",
        nulls = Nulls.SKIP
    )
    public Builder isActive(Optional<Boolean> isActive) {
      this.isActive = isActive;
      return this;
    }

    public Builder isActive(Boolean isActive) {
      this.isActive = Optional.ofNullable(isActive);
      return this;
    }

    @JsonSetter(
        value = "page",
        nulls = Nulls.SKIP
    )
    public Builder page(Optional<Double> page) {
      this.page = page;
      return this;
    }

    public Builder page(Double page) {
      this.page = Optional.ofNullable(page);
      return this;
    }

    @JsonSetter(
        value = "limit",
        nulls = Nulls.SKIP
    )
    public Builder limit(Optional<Double> limit) {
      this.limit = limit;
      return this;
    }

    public Builder limit(Double limit) {
      this.limit = Optional.ofNullable(limit);
      return this;
    }

    public ListCouponsRequest build() {
      return new ListCouponsRequest(isActive, page, limit, additionalProperties);
    }
  }
}
