/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.creditnotes.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import resources.creditnotes.types.ListCreditNotesRequestStatus;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListCreditNotesRequest.Builder.class
)
public final class ListCreditNotesRequest {
  private final Optional<String> customerId;

  private final Optional<String> invoiceId;

  private final Optional<ListCreditNotesRequestStatus> status;

  private final Optional<Double> page;

  private final Optional<Double> limit;

  private final Map<String, Object> additionalProperties;

  private ListCreditNotesRequest(Optional<String> customerId, Optional<String> invoiceId,
      Optional<ListCreditNotesRequestStatus> status, Optional<Double> page, Optional<Double> limit,
      Map<String, Object> additionalProperties) {
    this.customerId = customerId;
    this.invoiceId = invoiceId;
    this.status = status;
    this.page = page;
    this.limit = limit;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("customerId")
  public Optional<String> getCustomerId() {
    return customerId;
  }

  @JsonProperty("invoiceId")
  public Optional<String> getInvoiceId() {
    return invoiceId;
  }

  @JsonProperty("status")
  public Optional<ListCreditNotesRequestStatus> getStatus() {
    return status;
  }

  @JsonProperty("page")
  public Optional<Double> getPage() {
    return page;
  }

  @JsonProperty("limit")
  public Optional<Double> getLimit() {
    return limit;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListCreditNotesRequest && equalTo((ListCreditNotesRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListCreditNotesRequest other) {
    return customerId.equals(other.customerId) && invoiceId.equals(other.invoiceId) && status.equals(other.status) && page.equals(other.page) && limit.equals(other.limit);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.customerId, this.invoiceId, this.status, this.page, this.limit);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> customerId = Optional.empty();

    private Optional<String> invoiceId = Optional.empty();

    private Optional<ListCreditNotesRequestStatus> status = Optional.empty();

    private Optional<Double> page = Optional.empty();

    private Optional<Double> limit = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ListCreditNotesRequest other) {
      customerId(other.getCustomerId());
      invoiceId(other.getInvoiceId());
      status(other.getStatus());
      page(other.getPage());
      limit(other.getLimit());
      return this;
    }

    @JsonSetter(
        value = "customerId",
        nulls = Nulls.SKIP
    )
    public Builder customerId(Optional<String> customerId) {
      this.customerId = customerId;
      return this;
    }

    public Builder customerId(String customerId) {
      this.customerId = Optional.ofNullable(customerId);
      return this;
    }

    @JsonSetter(
        value = "invoiceId",
        nulls = Nulls.SKIP
    )
    public Builder invoiceId(Optional<String> invoiceId) {
      this.invoiceId = invoiceId;
      return this;
    }

    public Builder invoiceId(String invoiceId) {
      this.invoiceId = Optional.ofNullable(invoiceId);
      return this;
    }

    @JsonSetter(
        value = "status",
        nulls = Nulls.SKIP
    )
    public Builder status(Optional<ListCreditNotesRequestStatus> status) {
      this.status = status;
      return this;
    }

    public Builder status(ListCreditNotesRequestStatus status) {
      this.status = Optional.ofNullable(status);
      return this;
    }

    @JsonSetter(
        value = "page",
        nulls = Nulls.SKIP
    )
    public Builder page(Optional<Double> page) {
      this.page = page;
      return this;
    }

    public Builder page(Double page) {
      this.page = Optional.ofNullable(page);
      return this;
    }

    @JsonSetter(
        value = "limit",
        nulls = Nulls.SKIP
    )
    public Builder limit(Optional<Double> limit) {
      this.limit = limit;
      return this;
    }

    public Builder limit(Double limit) {
      this.limit = Optional.ofNullable(limit);
      return this;
    }

    public ListCreditNotesRequest build() {
      return new ListCreditNotesRequest(customerId, invoiceId, status, page, limit, additionalProperties);
    }
  }
}
