// Code generated by Fern. DO NOT EDIT.

package customers_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	novabillinggo "github.com/novabilling/novabilling-go"
	client "github.com/novabilling/novabilling-go/client"
	option "github.com/novabilling/novabilling-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestCustomersListWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &novabillinggo.ListCustomersRequest{}
	_, invocationErr := client.Customers.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCustomersListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCustomersListWithWireMock", "GET", "/api/customers", nil, 1)
}

func TestCustomersCreateWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &novabillinggo.CreateCustomerDto{
		ExternalID: "user_12345",
		Email:      "customer@example.com",
		Currency:   "NGN",
	}
	_, invocationErr := client.Customers.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCustomersCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCustomersCreateWithWireMock", "POST", "/api/customers", nil, 1)
}

func TestCustomersGetWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &novabillinggo.GetCustomersRequest{
		ID: "id",
	}
	_, invocationErr := client.Customers.Get(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCustomersGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCustomersGetWithWireMock", "GET", "/api/customers/id", nil, 1)
}

func TestCustomersDeleteWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &novabillinggo.DeleteCustomersRequest{
		ID: "id",
	}
	invocationErr := client.Customers.Delete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCustomersDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCustomersDeleteWithWireMock", "DELETE", "/api/customers/id", nil, 1)
}

func TestCustomersUpdateWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &novabillinggo.UpdateCustomerDto{
		ID: "id",
	}
	_, invocationErr := client.Customers.Update(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCustomersUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCustomersUpdateWithWireMock", "PATCH", "/api/customers/id", nil, 1)
}

func TestCustomersGetSubscriptionsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &novabillinggo.GetSubscriptionsCustomersRequest{
		ID: "id",
	}
	_, invocationErr := client.Customers.GetSubscriptions(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCustomersGetSubscriptionsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCustomersGetSubscriptionsWithWireMock", "GET", "/api/customers/id/subscriptions", nil, 1)
}

func TestCustomersGetInvoicesWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &novabillinggo.GetInvoicesCustomersRequest{
		ID: "id",
	}
	_, invocationErr := client.Customers.GetInvoices(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCustomersGetInvoicesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCustomersGetInvoicesWithWireMock", "GET", "/api/customers/id/invoices", nil, 1)
}

func TestCustomersGetPaymentsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &novabillinggo.GetPaymentsCustomersRequest{
		ID: "id",
	}
	_, invocationErr := client.Customers.GetPayments(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCustomersGetPaymentsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCustomersGetPaymentsWithWireMock", "GET", "/api/customers/id/payments", nil, 1)
}

func TestCustomersGetPaymentMethodsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &novabillinggo.GetPaymentMethodsCustomersRequest{
		ID: "id",
	}
	invocationErr := client.Customers.GetPaymentMethods(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCustomersGetPaymentMethodsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCustomersGetPaymentMethodsWithWireMock", "GET", "/api/customers/id/payment-methods", nil, 1)
}

func TestCustomersAddPaymentMethodWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &novabillinggo.AddPaymentMethodCustomersRequest{
		ID: "id",
	}
	invocationErr := client.Customers.AddPaymentMethod(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCustomersAddPaymentMethodWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCustomersAddPaymentMethodWithWireMock", "POST", "/api/customers/id/payment-methods", nil, 1)
}

func TestCustomersDeletePaymentMethodWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &novabillinggo.DeletePaymentMethodCustomersRequest{
		ID:       "id",
		MethodID: "methodId",
	}
	invocationErr := client.Customers.DeletePaymentMethod(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCustomersDeletePaymentMethodWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCustomersDeletePaymentMethodWithWireMock", "DELETE", "/api/customers/id/payment-methods/methodId", nil, 1)
}
