// Code generated by Fern. DO NOT EDIT.

package plans

import (
	context "context"
	novabillinggo "github.com/novabilling/novabilling-go"
	core "github.com/novabilling/novabilling-go/core"
	internal "github.com/novabilling/novabilling-go/internal"
	option "github.com/novabilling/novabilling-go/option"
	http "net/http"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) List(
	ctx context.Context,
	request *novabillinggo.ListPlansRequest,
	opts ...option.RequestOption,
) (*core.Response[[]*novabillinggo.PlanResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.novabilling.one",
	)
	endpointURL := baseURL + "/api/plans"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response []*novabillinggo.PlanResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[[]*novabillinggo.PlanResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Create(
	ctx context.Context,
	request *novabillinggo.CreatePlanDto,
	opts ...option.RequestOption,
) (*core.Response[*novabillinggo.PlanResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.novabilling.one",
	)
	endpointURL := baseURL + "/api/plans"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *novabillinggo.PlanResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(novabillinggo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*novabillinggo.PlanResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Get(
	ctx context.Context,
	request *novabillinggo.GetPlansRequest,
	opts ...option.RequestOption,
) (*core.Response[*novabillinggo.PlanResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.novabilling.one",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/plans/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *novabillinggo.PlanResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(novabillinggo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*novabillinggo.PlanResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Delete(
	ctx context.Context,
	request *novabillinggo.DeletePlansRequest,
	opts ...option.RequestOption,
) (*core.Response[*novabillinggo.PlanResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.novabilling.one",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/plans/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *novabillinggo.PlanResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(novabillinggo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*novabillinggo.PlanResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Update(
	ctx context.Context,
	request *novabillinggo.UpdatePlanDto,
	opts ...option.RequestOption,
) (*core.Response[*novabillinggo.PlanResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.novabilling.one",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/plans/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *novabillinggo.PlanResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(novabillinggo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*novabillinggo.PlanResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) AddPrice(
	ctx context.Context,
	request *novabillinggo.AddPricePlansRequest,
	opts ...option.RequestOption,
) (*core.Response[*novabillinggo.PlanPriceResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.novabilling.one",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/plans/%v/prices",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *novabillinggo.PlanPriceResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(novabillinggo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*novabillinggo.PlanPriceResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeletePrice(
	ctx context.Context,
	request *novabillinggo.DeletePricePlansRequest,
	opts ...option.RequestOption,
) (*core.Response[*novabillinggo.PlanPriceResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.novabilling.one",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/plans/%v/prices/%v",
		request.ID,
		request.PriceID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *novabillinggo.PlanPriceResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(novabillinggo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*novabillinggo.PlanPriceResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) UpdatePrice(
	ctx context.Context,
	request *novabillinggo.UpdatePricePlansRequest,
	opts ...option.RequestOption,
) (*core.Response[*novabillinggo.PlanPriceResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.novabilling.one",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/plans/%v/prices/%v",
		request.ID,
		request.PriceID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *novabillinggo.PlanPriceResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(novabillinggo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*novabillinggo.PlanPriceResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
