/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.addons;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import core.ClientOptions;
import core.MediaTypes;
import core.NovabillingApiApiException;
import core.NovabillingApiException;
import core.NovabillingApiHttpResponse;
import core.ObjectMappers;
import core.QueryStringMapper;
import core.RequestOptions;
import errors.BadRequestError;
import errors.NotFoundError;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;
import resources.addons.requests.ApplyAddOnDto;
import resources.addons.requests.CreateAddOnDto;
import resources.addons.requests.DeleteAddOnsRequest;
import resources.addons.requests.GetAddOnsRequest;
import resources.addons.requests.ListAddOnsRequest;
import resources.addons.requests.ListAppliedAddOnsRequest;
import resources.addons.requests.RemoveAppliedAddOnsRequest;
import resources.addons.requests.UpdateAddOnDto;
import types.AddOnResponse;
import types.AppliedAddOnResponse;
import types.PaginatedAddOnResponse;

public class AsyncRawAddOnsClient {
  protected final ClientOptions clientOptions;

  public AsyncRawAddOnsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Retrieve a paginated list of add-ons with prices.
   */
  public CompletableFuture<NovabillingApiHttpResponse<PaginatedAddOnResponse>> list() {
    return list(ListAddOnsRequest.builder().build());
  }

  /**
   * Retrieve a paginated list of add-ons with prices.
   */
  public CompletableFuture<NovabillingApiHttpResponse<PaginatedAddOnResponse>> list(
      RequestOptions requestOptions) {
    return list(ListAddOnsRequest.builder().build(),requestOptions);
  }

  /**
   * Retrieve a paginated list of add-ons with prices.
   */
  public CompletableFuture<NovabillingApiHttpResponse<PaginatedAddOnResponse>> list(
      ListAddOnsRequest request) {
    return list(request,null);
  }

  /**
   * Retrieve a paginated list of add-ons with prices.
   */
  public CompletableFuture<NovabillingApiHttpResponse<PaginatedAddOnResponse>> list(
      ListAddOnsRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("api/add-ons");if (request.getPage().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "page", request.getPage().get(), false);
      }
      if (request.getLimit().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
      }
      if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<NovabillingApiHttpResponse<PaginatedAddOnResponse>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              future.complete(new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PaginatedAddOnResponse.class), response));
              return;
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            future.completeExceptionally(new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new NovabillingApiException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new NovabillingApiException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    /**
     * Create a one-time charge add-on with multi-currency pricing.
     */
    public CompletableFuture<NovabillingApiHttpResponse<AddOnResponse>> create(
        CreateAddOnDto request) {
      return create(request,null);
    }

    /**
     * Create a one-time charge add-on with multi-currency pricing.
     */
    public CompletableFuture<NovabillingApiHttpResponse<AddOnResponse>> create(
        CreateAddOnDto request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("api/add-ons");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        RequestBody body;
        try {
          body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        }
        catch(JsonProcessingException e) {
          throw new NovabillingApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
          .url(httpUrl.build())
          .method("POST", body)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json")
          .addHeader("Accept", "application/json")
          .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<NovabillingApiHttpResponse<AddOnResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              if (response.isSuccessful()) {
                future.complete(new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AddOnResponse.class), response));
                return;
              }
              try {
                if (response.code() == 400) {
                  future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              future.completeExceptionally(new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
              return;
            }
            catch (IOException e) {
              future.completeExceptionally(new NovabillingApiException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new NovabillingApiException("Network error executing HTTP request", e));
          }
        });
        return future;
      }

      public CompletableFuture<NovabillingApiHttpResponse<AddOnResponse>> get(String id) {
        return get(id,GetAddOnsRequest.builder().build());
      }

      public CompletableFuture<NovabillingApiHttpResponse<AddOnResponse>> get(String id,
          RequestOptions requestOptions) {
        return get(id,GetAddOnsRequest.builder().build(),requestOptions);
      }

      public CompletableFuture<NovabillingApiHttpResponse<AddOnResponse>> get(String id,
          GetAddOnsRequest request) {
        return get(id,request,null);
      }

      public CompletableFuture<NovabillingApiHttpResponse<AddOnResponse>> get(String id,
          GetAddOnsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("api/add-ons")
          .addPathSegment(id);if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Accept", "application/json");
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          CompletableFuture<NovabillingApiHttpResponse<AddOnResponse>> future = new CompletableFuture<>();
          client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
              try (ResponseBody responseBody = response.body()) {
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                if (response.isSuccessful()) {
                  future.complete(new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AddOnResponse.class), response));
                  return;
                }
                try {
                  if (response.code() == 404) {
                    future.completeExceptionally(new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                    return;
                  }
                }
                catch (JsonProcessingException ignored) {
                  // unable to map error response, throwing generic error
                }
                Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                future.completeExceptionally(new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                return;
              }
              catch (IOException e) {
                future.completeExceptionally(new NovabillingApiException("Network error executing HTTP request", e));
              }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
              future.completeExceptionally(new NovabillingApiException("Network error executing HTTP request", e));
            }
          });
          return future;
        }

        public CompletableFuture<NovabillingApiHttpResponse<AddOnResponse>> delete(String id) {
          return delete(id,DeleteAddOnsRequest.builder().build());
        }

        public CompletableFuture<NovabillingApiHttpResponse<AddOnResponse>> delete(String id,
            RequestOptions requestOptions) {
          return delete(id,DeleteAddOnsRequest.builder().build(),requestOptions);
        }

        public CompletableFuture<NovabillingApiHttpResponse<AddOnResponse>> delete(String id,
            DeleteAddOnsRequest request) {
          return delete(id,request,null);
        }

        public CompletableFuture<NovabillingApiHttpResponse<AddOnResponse>> delete(String id,
            DeleteAddOnsRequest request, RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("api/add-ons")
            .addPathSegment(id);if (requestOptions != null) {
              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
              } );
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("DELETE", null)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Accept", "application/json");
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            CompletableFuture<NovabillingApiHttpResponse<AddOnResponse>> future = new CompletableFuture<>();
            client.newCall(okhttpRequest).enqueue(new Callback() {
              @Override
              public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  if (response.isSuccessful()) {
                    future.complete(new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AddOnResponse.class), response));
                    return;
                  }
                  try {
                    if (response.code() == 404) {
                      future.completeExceptionally(new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                      return;
                    }
                  }
                  catch (JsonProcessingException ignored) {
                    // unable to map error response, throwing generic error
                  }
                  Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                  future.completeExceptionally(new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                  return;
                }
                catch (IOException e) {
                  future.completeExceptionally(new NovabillingApiException("Network error executing HTTP request", e));
                }
              }

              @Override
              public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new NovabillingApiException("Network error executing HTTP request", e));
              }
            });
            return future;
          }

          public CompletableFuture<NovabillingApiHttpResponse<AddOnResponse>> update(String id) {
            return update(id,UpdateAddOnDto.builder().build());
          }

          public CompletableFuture<NovabillingApiHttpResponse<AddOnResponse>> update(String id,
              RequestOptions requestOptions) {
            return update(id,UpdateAddOnDto.builder().build(),requestOptions);
          }

          public CompletableFuture<NovabillingApiHttpResponse<AddOnResponse>> update(String id,
              UpdateAddOnDto request) {
            return update(id,request,null);
          }

          public CompletableFuture<NovabillingApiHttpResponse<AddOnResponse>> update(String id,
              UpdateAddOnDto request, RequestOptions requestOptions) {
            HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("api/add-ons")
              .addPathSegment(id);if (requestOptions != null) {
                requestOptions.getQueryParameters().forEach((_key, _value) -> {
                  httpUrl.addQueryParameter(_key, _value);
                } );
              }
              RequestBody body;
              try {
                body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
              }
              catch(JsonProcessingException e) {
                throw new NovabillingApiException("Failed to serialize request", e);
              }
              Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
              OkHttpClient client = clientOptions.httpClient();
              if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
              }
              CompletableFuture<NovabillingApiHttpResponse<AddOnResponse>> future = new CompletableFuture<>();
              client.newCall(okhttpRequest).enqueue(new Callback() {
                @Override
                public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                  try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                      future.complete(new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AddOnResponse.class), response));
                      return;
                    }
                    try {
                      if (response.code() == 404) {
                        future.completeExceptionally(new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                        return;
                      }
                    }
                    catch (JsonProcessingException ignored) {
                      // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                  }
                  catch (IOException e) {
                    future.completeExceptionally(new NovabillingApiException("Network error executing HTTP request", e));
                  }
                }

                @Override
                public void onFailure(@NotNull Call call, @NotNull IOException e) {
                  future.completeExceptionally(new NovabillingApiException("Network error executing HTTP request", e));
                }
              });
              return future;
            }

            /**
             * Create a one-time charge for a customer. Will be included in the next invoice.
             */
            public CompletableFuture<NovabillingApiHttpResponse<AppliedAddOnResponse>> apply(
                ApplyAddOnDto request) {
              return apply(request,null);
            }

            /**
             * Create a one-time charge for a customer. Will be included in the next invoice.
             */
            public CompletableFuture<NovabillingApiHttpResponse<AppliedAddOnResponse>> apply(
                ApplyAddOnDto request, RequestOptions requestOptions) {
              HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                .addPathSegments("api/add-ons/apply");if (requestOptions != null) {
                  requestOptions.getQueryParameters().forEach((_key, _value) -> {
                    httpUrl.addQueryParameter(_key, _value);
                  } );
                }
                RequestBody body;
                try {
                  body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
                }
                catch(JsonProcessingException e) {
                  throw new NovabillingApiException("Failed to serialize request", e);
                }
                Request okhttpRequest = new Request.Builder()
                  .url(httpUrl.build())
                  .method("POST", body)
                  .headers(Headers.of(clientOptions.headers(requestOptions)))
                  .addHeader("Content-Type", "application/json")
                  .addHeader("Accept", "application/json")
                  .build();
                OkHttpClient client = clientOptions.httpClient();
                if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                  client = clientOptions.httpClientWithTimeout(requestOptions);
                }
                CompletableFuture<NovabillingApiHttpResponse<AppliedAddOnResponse>> future = new CompletableFuture<>();
                client.newCall(okhttpRequest).enqueue(new Callback() {
                  @Override
                  public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                    try (ResponseBody responseBody = response.body()) {
                      String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                      if (response.isSuccessful()) {
                        future.complete(new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AppliedAddOnResponse.class), response));
                        return;
                      }
                      try {
                        if (response.code() == 404) {
                          future.completeExceptionally(new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                          return;
                        }
                      }
                      catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                      }
                      Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                      future.completeExceptionally(new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                      return;
                    }
                    catch (IOException e) {
                      future.completeExceptionally(new NovabillingApiException("Network error executing HTTP request", e));
                    }
                  }

                  @Override
                  public void onFailure(@NotNull Call call, @NotNull IOException e) {
                    future.completeExceptionally(new NovabillingApiException("Network error executing HTTP request", e));
                  }
                });
                return future;
              }

              /**
               * View one-time charges applied to customers.
               */
              public CompletableFuture<NovabillingApiHttpResponse<List<AppliedAddOnResponse>>> listApplied(
                  ) {
                return listApplied(ListAppliedAddOnsRequest.builder().build());
              }

              /**
               * View one-time charges applied to customers.
               */
              public CompletableFuture<NovabillingApiHttpResponse<List<AppliedAddOnResponse>>> listApplied(
                  RequestOptions requestOptions) {
                return listApplied(ListAppliedAddOnsRequest.builder().build(),requestOptions);
              }

              /**
               * View one-time charges applied to customers.
               */
              public CompletableFuture<NovabillingApiHttpResponse<List<AppliedAddOnResponse>>> listApplied(
                  ListAppliedAddOnsRequest request) {
                return listApplied(request,null);
              }

              /**
               * View one-time charges applied to customers.
               */
              public CompletableFuture<NovabillingApiHttpResponse<List<AppliedAddOnResponse>>> listApplied(
                  ListAppliedAddOnsRequest request, RequestOptions requestOptions) {
                HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                  .addPathSegments("api/add-ons/applied/list");if (request.getCustomerId().isPresent()) {
                    QueryStringMapper.addQueryParameter(httpUrl, "customerId", request.getCustomerId().get(), false);
                  }
                  if (request.getInvoiced().isPresent()) {
                    QueryStringMapper.addQueryParameter(httpUrl, "invoiced", request.getInvoiced().get(), false);
                  }
                  if (request.getPage().isPresent()) {
                    QueryStringMapper.addQueryParameter(httpUrl, "page", request.getPage().get(), false);
                  }
                  if (request.getLimit().isPresent()) {
                    QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
                  }
                  if (requestOptions != null) {
                    requestOptions.getQueryParameters().forEach((_key, _value) -> {
                      httpUrl.addQueryParameter(_key, _value);
                    } );
                  }
                  Request.Builder _requestBuilder = new Request.Builder()
                    .url(httpUrl.build())
                    .method("GET", null)
                    .headers(Headers.of(clientOptions.headers(requestOptions)))
                    .addHeader("Accept", "application/json");
                  Request okhttpRequest = _requestBuilder.build();
                  OkHttpClient client = clientOptions.httpClient();
                  if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                    client = clientOptions.httpClientWithTimeout(requestOptions);
                  }
                  CompletableFuture<NovabillingApiHttpResponse<List<AppliedAddOnResponse>>> future = new CompletableFuture<>();
                  client.newCall(okhttpRequest).enqueue(new Callback() {
                    @Override
                    public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                      try (ResponseBody responseBody = response.body()) {
                        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                        if (response.isSuccessful()) {
                          future.complete(new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, new TypeReference<List<AppliedAddOnResponse>>() {}), response));
                          return;
                        }
                        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                        future.completeExceptionally(new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                        return;
                      }
                      catch (IOException e) {
                        future.completeExceptionally(new NovabillingApiException("Network error executing HTTP request", e));
                      }
                    }

                    @Override
                    public void onFailure(@NotNull Call call, @NotNull IOException e) {
                      future.completeExceptionally(new NovabillingApiException("Network error executing HTTP request", e));
                    }
                  });
                  return future;
                }

                /**
                 * Remove a one-time charge that has not yet been invoiced.
                 */
                public CompletableFuture<NovabillingApiHttpResponse<AppliedAddOnResponse>> removeApplied(
                    String id) {
                  return removeApplied(id,RemoveAppliedAddOnsRequest.builder().build());
                }

                /**
                 * Remove a one-time charge that has not yet been invoiced.
                 */
                public CompletableFuture<NovabillingApiHttpResponse<AppliedAddOnResponse>> removeApplied(
                    String id, RequestOptions requestOptions) {
                  return removeApplied(id,RemoveAppliedAddOnsRequest.builder().build(),requestOptions);
                }

                /**
                 * Remove a one-time charge that has not yet been invoiced.
                 */
                public CompletableFuture<NovabillingApiHttpResponse<AppliedAddOnResponse>> removeApplied(
                    String id, RemoveAppliedAddOnsRequest request) {
                  return removeApplied(id,request,null);
                }

                /**
                 * Remove a one-time charge that has not yet been invoiced.
                 */
                public CompletableFuture<NovabillingApiHttpResponse<AppliedAddOnResponse>> removeApplied(
                    String id, RemoveAppliedAddOnsRequest request, RequestOptions requestOptions) {
                  HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                    .addPathSegments("api/add-ons/applied")
                    .addPathSegment(id);if (requestOptions != null) {
                      requestOptions.getQueryParameters().forEach((_key, _value) -> {
                        httpUrl.addQueryParameter(_key, _value);
                      } );
                    }
                    Request.Builder _requestBuilder = new Request.Builder()
                      .url(httpUrl.build())
                      .method("DELETE", null)
                      .headers(Headers.of(clientOptions.headers(requestOptions)))
                      .addHeader("Accept", "application/json");
                    Request okhttpRequest = _requestBuilder.build();
                    OkHttpClient client = clientOptions.httpClient();
                    if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                      client = clientOptions.httpClientWithTimeout(requestOptions);
                    }
                    CompletableFuture<NovabillingApiHttpResponse<AppliedAddOnResponse>> future = new CompletableFuture<>();
                    client.newCall(okhttpRequest).enqueue(new Callback() {
                      @Override
                      public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                        try (ResponseBody responseBody = response.body()) {
                          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                          if (response.isSuccessful()) {
                            future.complete(new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AppliedAddOnResponse.class), response));
                            return;
                          }
                          try {
                            switch (response.code()) {
                              case 400:future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                              return;
                              case 404:future.completeExceptionally(new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                              return;
                            }
                          }
                          catch (JsonProcessingException ignored) {
                            // unable to map error response, throwing generic error
                          }
                          Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                          future.completeExceptionally(new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                          return;
                        }
                        catch (IOException e) {
                          future.completeExceptionally(new NovabillingApiException("Network error executing HTTP request", e));
                        }
                      }

                      @Override
                      public void onFailure(@NotNull Call call, @NotNull IOException e) {
                        future.completeExceptionally(new NovabillingApiException("Network error executing HTTP request", e));
                      }
                    });
                    return future;
                  }
                }
