/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.addons;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import core.ClientOptions;
import core.MediaTypes;
import core.NovabillingApiApiException;
import core.NovabillingApiException;
import core.NovabillingApiHttpResponse;
import core.ObjectMappers;
import core.QueryStringMapper;
import core.RequestOptions;
import errors.BadRequestError;
import errors.NotFoundError;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import java.util.List;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import resources.addons.requests.ApplyAddOnDto;
import resources.addons.requests.CreateAddOnDto;
import resources.addons.requests.DeleteAddOnsRequest;
import resources.addons.requests.GetAddOnsRequest;
import resources.addons.requests.ListAddOnsRequest;
import resources.addons.requests.ListAppliedAddOnsRequest;
import resources.addons.requests.RemoveAppliedAddOnsRequest;
import resources.addons.requests.UpdateAddOnDto;
import types.AddOnResponse;
import types.AppliedAddOnResponse;
import types.PaginatedAddOnResponse;

public class RawAddOnsClient {
  protected final ClientOptions clientOptions;

  public RawAddOnsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Retrieve a paginated list of add-ons with prices.
   */
  public NovabillingApiHttpResponse<PaginatedAddOnResponse> list() {
    return list(ListAddOnsRequest.builder().build());
  }

  /**
   * Retrieve a paginated list of add-ons with prices.
   */
  public NovabillingApiHttpResponse<PaginatedAddOnResponse> list(RequestOptions requestOptions) {
    return list(ListAddOnsRequest.builder().build(),requestOptions);
  }

  /**
   * Retrieve a paginated list of add-ons with prices.
   */
  public NovabillingApiHttpResponse<PaginatedAddOnResponse> list(ListAddOnsRequest request) {
    return list(request,null);
  }

  /**
   * Retrieve a paginated list of add-ons with prices.
   */
  public NovabillingApiHttpResponse<PaginatedAddOnResponse> list(ListAddOnsRequest request,
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("api/add-ons");if (request.getPage().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "page", request.getPage().get(), false);
      }
      if (request.getLimit().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
      }
      if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        if (response.isSuccessful()) {
          return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PaginatedAddOnResponse.class), response);
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (IOException e) {
        throw new NovabillingApiException("Network error executing HTTP request", e);
      }
    }

    /**
     * Create a one-time charge add-on with multi-currency pricing.
     */
    public NovabillingApiHttpResponse<AddOnResponse> create(CreateAddOnDto request) {
      return create(request,null);
    }

    /**
     * Create a one-time charge add-on with multi-currency pricing.
     */
    public NovabillingApiHttpResponse<AddOnResponse> create(CreateAddOnDto request,
        RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("api/add-ons");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        RequestBody body;
        try {
          body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        }
        catch(JsonProcessingException e) {
          throw new NovabillingApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
          .url(httpUrl.build())
          .method("POST", body)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json")
          .addHeader("Accept", "application/json")
          .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          if (response.isSuccessful()) {
            return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AddOnResponse.class), response);
          }
          try {
            if (response.code() == 400) {
              throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            }
          }
          catch (JsonProcessingException ignored) {
            // unable to map error response, throwing generic error
          }
          Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
          throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
        }
        catch (IOException e) {
          throw new NovabillingApiException("Network error executing HTTP request", e);
        }
      }

      public NovabillingApiHttpResponse<AddOnResponse> get(String id) {
        return get(id,GetAddOnsRequest.builder().build());
      }

      public NovabillingApiHttpResponse<AddOnResponse> get(String id,
          RequestOptions requestOptions) {
        return get(id,GetAddOnsRequest.builder().build(),requestOptions);
      }

      public NovabillingApiHttpResponse<AddOnResponse> get(String id, GetAddOnsRequest request) {
        return get(id,request,null);
      }

      public NovabillingApiHttpResponse<AddOnResponse> get(String id, GetAddOnsRequest request,
          RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("api/add-ons")
          .addPathSegment(id);if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Accept", "application/json");
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AddOnResponse.class), response);
            }
            try {
              if (response.code() == 404) {
                throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
          }
          catch (IOException e) {
            throw new NovabillingApiException("Network error executing HTTP request", e);
          }
        }

        public NovabillingApiHttpResponse<AddOnResponse> delete(String id) {
          return delete(id,DeleteAddOnsRequest.builder().build());
        }

        public NovabillingApiHttpResponse<AddOnResponse> delete(String id,
            RequestOptions requestOptions) {
          return delete(id,DeleteAddOnsRequest.builder().build(),requestOptions);
        }

        public NovabillingApiHttpResponse<AddOnResponse> delete(String id,
            DeleteAddOnsRequest request) {
          return delete(id,request,null);
        }

        public NovabillingApiHttpResponse<AddOnResponse> delete(String id,
            DeleteAddOnsRequest request, RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("api/add-ons")
            .addPathSegment(id);if (requestOptions != null) {
              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
              } );
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("DELETE", null)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Accept", "application/json");
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            try (Response response = client.newCall(okhttpRequest).execute()) {
              ResponseBody responseBody = response.body();
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              if (response.isSuccessful()) {
                return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AddOnResponse.class), response);
              }
              try {
                if (response.code() == 404) {
                  throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
            }
            catch (IOException e) {
              throw new NovabillingApiException("Network error executing HTTP request", e);
            }
          }

          public NovabillingApiHttpResponse<AddOnResponse> update(String id) {
            return update(id,UpdateAddOnDto.builder().build());
          }

          public NovabillingApiHttpResponse<AddOnResponse> update(String id,
              RequestOptions requestOptions) {
            return update(id,UpdateAddOnDto.builder().build(),requestOptions);
          }

          public NovabillingApiHttpResponse<AddOnResponse> update(String id,
              UpdateAddOnDto request) {
            return update(id,request,null);
          }

          public NovabillingApiHttpResponse<AddOnResponse> update(String id, UpdateAddOnDto request,
              RequestOptions requestOptions) {
            HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("api/add-ons")
              .addPathSegment(id);if (requestOptions != null) {
                requestOptions.getQueryParameters().forEach((_key, _value) -> {
                  httpUrl.addQueryParameter(_key, _value);
                } );
              }
              RequestBody body;
              try {
                body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
              }
              catch(JsonProcessingException e) {
                throw new NovabillingApiException("Failed to serialize request", e);
              }
              Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
              OkHttpClient client = clientOptions.httpClient();
              if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
              }
              try (Response response = client.newCall(okhttpRequest).execute()) {
                ResponseBody responseBody = response.body();
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                if (response.isSuccessful()) {
                  return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AddOnResponse.class), response);
                }
                try {
                  if (response.code() == 404) {
                    throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                  }
                }
                catch (JsonProcessingException ignored) {
                  // unable to map error response, throwing generic error
                }
                Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
              }
              catch (IOException e) {
                throw new NovabillingApiException("Network error executing HTTP request", e);
              }
            }

            /**
             * Create a one-time charge for a customer. Will be included in the next invoice.
             */
            public NovabillingApiHttpResponse<AppliedAddOnResponse> apply(ApplyAddOnDto request) {
              return apply(request,null);
            }

            /**
             * Create a one-time charge for a customer. Will be included in the next invoice.
             */
            public NovabillingApiHttpResponse<AppliedAddOnResponse> apply(ApplyAddOnDto request,
                RequestOptions requestOptions) {
              HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                .addPathSegments("api/add-ons/apply");if (requestOptions != null) {
                  requestOptions.getQueryParameters().forEach((_key, _value) -> {
                    httpUrl.addQueryParameter(_key, _value);
                  } );
                }
                RequestBody body;
                try {
                  body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
                }
                catch(JsonProcessingException e) {
                  throw new NovabillingApiException("Failed to serialize request", e);
                }
                Request okhttpRequest = new Request.Builder()
                  .url(httpUrl.build())
                  .method("POST", body)
                  .headers(Headers.of(clientOptions.headers(requestOptions)))
                  .addHeader("Content-Type", "application/json")
                  .addHeader("Accept", "application/json")
                  .build();
                OkHttpClient client = clientOptions.httpClient();
                if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                  client = clientOptions.httpClientWithTimeout(requestOptions);
                }
                try (Response response = client.newCall(okhttpRequest).execute()) {
                  ResponseBody responseBody = response.body();
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  if (response.isSuccessful()) {
                    return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AppliedAddOnResponse.class), response);
                  }
                  try {
                    if (response.code() == 404) {
                      throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    }
                  }
                  catch (JsonProcessingException ignored) {
                    // unable to map error response, throwing generic error
                  }
                  Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                  throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                }
                catch (IOException e) {
                  throw new NovabillingApiException("Network error executing HTTP request", e);
                }
              }

              /**
               * View one-time charges applied to customers.
               */
              public NovabillingApiHttpResponse<List<AppliedAddOnResponse>> listApplied() {
                return listApplied(ListAppliedAddOnsRequest.builder().build());
              }

              /**
               * View one-time charges applied to customers.
               */
              public NovabillingApiHttpResponse<List<AppliedAddOnResponse>> listApplied(
                  RequestOptions requestOptions) {
                return listApplied(ListAppliedAddOnsRequest.builder().build(),requestOptions);
              }

              /**
               * View one-time charges applied to customers.
               */
              public NovabillingApiHttpResponse<List<AppliedAddOnResponse>> listApplied(
                  ListAppliedAddOnsRequest request) {
                return listApplied(request,null);
              }

              /**
               * View one-time charges applied to customers.
               */
              public NovabillingApiHttpResponse<List<AppliedAddOnResponse>> listApplied(
                  ListAppliedAddOnsRequest request, RequestOptions requestOptions) {
                HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                  .addPathSegments("api/add-ons/applied/list");if (request.getCustomerId().isPresent()) {
                    QueryStringMapper.addQueryParameter(httpUrl, "customerId", request.getCustomerId().get(), false);
                  }
                  if (request.getInvoiced().isPresent()) {
                    QueryStringMapper.addQueryParameter(httpUrl, "invoiced", request.getInvoiced().get(), false);
                  }
                  if (request.getPage().isPresent()) {
                    QueryStringMapper.addQueryParameter(httpUrl, "page", request.getPage().get(), false);
                  }
                  if (request.getLimit().isPresent()) {
                    QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
                  }
                  if (requestOptions != null) {
                    requestOptions.getQueryParameters().forEach((_key, _value) -> {
                      httpUrl.addQueryParameter(_key, _value);
                    } );
                  }
                  Request.Builder _requestBuilder = new Request.Builder()
                    .url(httpUrl.build())
                    .method("GET", null)
                    .headers(Headers.of(clientOptions.headers(requestOptions)))
                    .addHeader("Accept", "application/json");
                  Request okhttpRequest = _requestBuilder.build();
                  OkHttpClient client = clientOptions.httpClient();
                  if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                    client = clientOptions.httpClientWithTimeout(requestOptions);
                  }
                  try (Response response = client.newCall(okhttpRequest).execute()) {
                    ResponseBody responseBody = response.body();
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                      return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, new TypeReference<List<AppliedAddOnResponse>>() {}), response);
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                  }
                  catch (IOException e) {
                    throw new NovabillingApiException("Network error executing HTTP request", e);
                  }
                }

                /**
                 * Remove a one-time charge that has not yet been invoiced.
                 */
                public NovabillingApiHttpResponse<AppliedAddOnResponse> removeApplied(String id) {
                  return removeApplied(id,RemoveAppliedAddOnsRequest.builder().build());
                }

                /**
                 * Remove a one-time charge that has not yet been invoiced.
                 */
                public NovabillingApiHttpResponse<AppliedAddOnResponse> removeApplied(String id,
                    RequestOptions requestOptions) {
                  return removeApplied(id,RemoveAppliedAddOnsRequest.builder().build(),requestOptions);
                }

                /**
                 * Remove a one-time charge that has not yet been invoiced.
                 */
                public NovabillingApiHttpResponse<AppliedAddOnResponse> removeApplied(String id,
                    RemoveAppliedAddOnsRequest request) {
                  return removeApplied(id,request,null);
                }

                /**
                 * Remove a one-time charge that has not yet been invoiced.
                 */
                public NovabillingApiHttpResponse<AppliedAddOnResponse> removeApplied(String id,
                    RemoveAppliedAddOnsRequest request, RequestOptions requestOptions) {
                  HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                    .addPathSegments("api/add-ons/applied")
                    .addPathSegment(id);if (requestOptions != null) {
                      requestOptions.getQueryParameters().forEach((_key, _value) -> {
                        httpUrl.addQueryParameter(_key, _value);
                      } );
                    }
                    Request.Builder _requestBuilder = new Request.Builder()
                      .url(httpUrl.build())
                      .method("DELETE", null)
                      .headers(Headers.of(clientOptions.headers(requestOptions)))
                      .addHeader("Accept", "application/json");
                    Request okhttpRequest = _requestBuilder.build();
                    OkHttpClient client = clientOptions.httpClient();
                    if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                      client = clientOptions.httpClientWithTimeout(requestOptions);
                    }
                    try (Response response = client.newCall(okhttpRequest).execute()) {
                      ResponseBody responseBody = response.body();
                      String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                      if (response.isSuccessful()) {
                        return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AppliedAddOnResponse.class), response);
                      }
                      try {
                        switch (response.code()) {
                          case 400:throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                          case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                        }
                      }
                      catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                      }
                      Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                      throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                    }
                    catch (IOException e) {
                      throw new NovabillingApiException("Network error executing HTTP request", e);
                    }
                  }
                }
