/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.subscriptions.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;
import resources.subscriptions.types.CancelSubscriptionDtoCancelAt;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CancelSubscriptionDto.Builder.class
)
public final class CancelSubscriptionDto {
  private final CancelSubscriptionDtoCancelAt cancelAt;

  private final Map<String, Object> additionalProperties;

  private CancelSubscriptionDto(CancelSubscriptionDtoCancelAt cancelAt,
      Map<String, Object> additionalProperties) {
    this.cancelAt = cancelAt;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return When to cancel: immediately or at end of current period
   */
  @JsonProperty("cancelAt")
  public CancelSubscriptionDtoCancelAt getCancelAt() {
    return cancelAt;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CancelSubscriptionDto && equalTo((CancelSubscriptionDto) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CancelSubscriptionDto other) {
    return cancelAt.equals(other.cancelAt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.cancelAt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static CancelAtStage builder() {
    return new Builder();
  }

  public interface CancelAtStage {
    /**
     * <p>When to cancel: immediately or at end of current period</p>
     */
    _FinalStage cancelAt(@NotNull CancelSubscriptionDtoCancelAt cancelAt);

    Builder from(CancelSubscriptionDto other);
  }

  public interface _FinalStage {
    CancelSubscriptionDto build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements CancelAtStage, _FinalStage {
    private CancelSubscriptionDtoCancelAt cancelAt;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CancelSubscriptionDto other) {
      cancelAt(other.getCancelAt());
      return this;
    }

    /**
     * <p>When to cancel: immediately or at end of current period</p>
     * <p>When to cancel: immediately or at end of current period</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("cancelAt")
    public _FinalStage cancelAt(@NotNull CancelSubscriptionDtoCancelAt cancelAt) {
      this.cancelAt = Objects.requireNonNull(cancelAt, "cancelAt must not be null");
      return this;
    }

    @java.lang.Override
    public CancelSubscriptionDto build() {
      return new CancelSubscriptionDto(cancelAt, additionalProperties);
    }
  }
}
