// Code generated by Fern. DO NOT EDIT.

package payment_providers_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	novabillinggo "github.com/novabilling/novabilling-go"
	client "github.com/novabilling/novabilling-go/client"
	option "github.com/novabilling/novabilling-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestPaymentProvidersListWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.PaymentProviders.List(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPaymentProvidersListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPaymentProvidersListWithWireMock", "GET", "/api/payment-providers", nil, 1)
}

func TestPaymentProvidersConfigureWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &novabillinggo.CreateProviderDto{
		ProviderName: "flutterwave",
		Credentials: map[string]any{
			"key": "value",
		},
	}
	_, invocationErr := client.PaymentProviders.Configure(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPaymentProvidersConfigureWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPaymentProvidersConfigureWithWireMock", "POST", "/api/payment-providers", nil, 1)
}

func TestPaymentProvidersGetWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &novabillinggo.GetPaymentProvidersRequest{
		ID: "id",
	}
	_, invocationErr := client.PaymentProviders.Get(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPaymentProvidersGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPaymentProvidersGetWithWireMock", "GET", "/api/payment-providers/id", nil, 1)
}

func TestPaymentProvidersDeleteWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &novabillinggo.DeletePaymentProvidersRequest{
		ID: "id",
	}
	_, invocationErr := client.PaymentProviders.Delete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPaymentProvidersDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPaymentProvidersDeleteWithWireMock", "DELETE", "/api/payment-providers/id", nil, 1)
}

func TestPaymentProvidersUpdateWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &novabillinggo.UpdateProviderDto{
		ID: "id",
	}
	_, invocationErr := client.PaymentProviders.Update(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPaymentProvidersUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPaymentProvidersUpdateWithWireMock", "PATCH", "/api/payment-providers/id", nil, 1)
}

func TestPaymentProvidersTestConnectionWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &novabillinggo.TestConnectionPaymentProvidersRequest{
		ID: "id",
	}
	_, invocationErr := client.PaymentProviders.TestConnection(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPaymentProvidersTestConnectionWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPaymentProvidersTestConnectionWithWireMock", "POST", "/api/payment-providers/id/test", nil, 1)
}
