/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.webhooks.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = WebhooksControllerFlutterwaveRequest.Builder.class
)
public final class WebhooksControllerFlutterwaveRequest {
  private final Optional<String> verifHash;

  private final Map<String, Object> additionalProperties;

  private WebhooksControllerFlutterwaveRequest(Optional<String> verifHash,
      Map<String, Object> additionalProperties) {
    this.verifHash = verifHash;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Flutterwave verification hash
   */
  @JsonIgnore
  public Optional<String> getVerifHash() {
    return verifHash;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof WebhooksControllerFlutterwaveRequest && equalTo((WebhooksControllerFlutterwaveRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(WebhooksControllerFlutterwaveRequest other) {
    return verifHash.equals(other.verifHash);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.verifHash);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> verifHash = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(WebhooksControllerFlutterwaveRequest other) {
      verifHash(other.getVerifHash());
      return this;
    }

    /**
     * <p>Flutterwave verification hash</p>
     */
    public Builder verifHash(Optional<String> verifHash) {
      this.verifHash = verifHash;
      return this;
    }

    public Builder verifHash(String verifHash) {
      this.verifHash = Optional.ofNullable(verifHash);
      return this;
    }

    public WebhooksControllerFlutterwaveRequest build() {
      return new WebhooksControllerFlutterwaveRequest(verifHash, additionalProperties);
    }
  }
}
