/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.invoices;

import core.ClientOptions;
import core.RequestOptions;
import java.lang.String;
import java.lang.Void;
import java.util.concurrent.CompletableFuture;
import resources.invoices.requests.CreateCheckoutInvoicesRequest;
import resources.invoices.requests.CreateInvoiceDto;
import resources.invoices.requests.FinalizeInvoicesRequest;
import resources.invoices.requests.GetInvoicesRequest;
import resources.invoices.requests.GetPdfInvoicesRequest;
import resources.invoices.requests.ListInvoicesRequest;
import resources.invoices.requests.MarkPaidInvoicesRequest;
import resources.invoices.requests.SendEmailInvoicesRequest;
import resources.invoices.requests.VoidInvoicesRequest;
import types.CheckoutResponse;
import types.InvoiceResponse;
import types.MessageResponse;
import types.PaginatedInvoiceResponse;

public class AsyncInvoicesClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawInvoicesClient rawClient;

  public AsyncInvoicesClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawInvoicesClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawInvoicesClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Retrieve a paginated list of invoices. Supports filtering by status, customer, and date range.
   */
  public CompletableFuture<PaginatedInvoiceResponse> list() {
    return this.rawClient.list().thenApply(response -> response.body());
  }

  /**
   * Retrieve a paginated list of invoices. Supports filtering by status, customer, and date range.
   */
  public CompletableFuture<PaginatedInvoiceResponse> list(RequestOptions requestOptions) {
    return this.rawClient.list(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Retrieve a paginated list of invoices. Supports filtering by status, customer, and date range.
   */
  public CompletableFuture<PaginatedInvoiceResponse> list(ListInvoicesRequest request) {
    return this.rawClient.list(request).thenApply(response -> response.body());
  }

  /**
   * Retrieve a paginated list of invoices. Supports filtering by status, customer, and date range.
   */
  public CompletableFuture<PaginatedInvoiceResponse> list(ListInvoicesRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Create a draft invoice with line items. The total amount is automatically calculated from the items.
   */
  public CompletableFuture<InvoiceResponse> create(CreateInvoiceDto request) {
    return this.rawClient.create(request).thenApply(response -> response.body());
  }

  /**
   * Create a draft invoice with line items. The total amount is automatically calculated from the items.
   */
  public CompletableFuture<InvoiceResponse> create(CreateInvoiceDto request,
      RequestOptions requestOptions) {
    return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Retrieve detailed invoice information including associated customer, subscription, and payments.
   */
  public CompletableFuture<InvoiceResponse> get(String id) {
    return this.rawClient.get(id).thenApply(response -> response.body());
  }

  /**
   * Retrieve detailed invoice information including associated customer, subscription, and payments.
   */
  public CompletableFuture<InvoiceResponse> get(String id, RequestOptions requestOptions) {
    return this.rawClient.get(id, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Retrieve detailed invoice information including associated customer, subscription, and payments.
   */
  public CompletableFuture<InvoiceResponse> get(String id, GetInvoicesRequest request) {
    return this.rawClient.get(id, request).thenApply(response -> response.body());
  }

  /**
   * Retrieve detailed invoice information including associated customer, subscription, and payments.
   */
  public CompletableFuture<InvoiceResponse> get(String id, GetInvoicesRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.get(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Move an invoice from draft to pending status, making it ready for payment.
   */
  public CompletableFuture<InvoiceResponse> finalize(String id) {
    return this.rawClient.finalize(id).thenApply(response -> response.body());
  }

  /**
   * Move an invoice from draft to pending status, making it ready for payment.
   */
  public CompletableFuture<InvoiceResponse> finalize(String id, RequestOptions requestOptions) {
    return this.rawClient.finalize(id, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Move an invoice from draft to pending status, making it ready for payment.
   */
  public CompletableFuture<InvoiceResponse> finalize(String id, FinalizeInvoicesRequest request) {
    return this.rawClient.finalize(id, request).thenApply(response -> response.body());
  }

  /**
   * Move an invoice from draft to pending status, making it ready for payment.
   */
  public CompletableFuture<InvoiceResponse> finalize(String id, FinalizeInvoicesRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.finalize(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Cancel an unpaid invoice. Paid invoices cannot be voided — use a refund instead.
   */
  public CompletableFuture<InvoiceResponse> void_(String id) {
    return this.rawClient.void_(id).thenApply(response -> response.body());
  }

  /**
   * Cancel an unpaid invoice. Paid invoices cannot be voided — use a refund instead.
   */
  public CompletableFuture<InvoiceResponse> void_(String id, RequestOptions requestOptions) {
    return this.rawClient.void_(id, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Cancel an unpaid invoice. Paid invoices cannot be voided — use a refund instead.
   */
  public CompletableFuture<InvoiceResponse> void_(String id, VoidInvoicesRequest request) {
    return this.rawClient.void_(id, request).thenApply(response -> response.body());
  }

  /**
   * Cancel an unpaid invoice. Paid invoices cannot be voided — use a refund instead.
   */
  public CompletableFuture<InvoiceResponse> void_(String id, VoidInvoicesRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.void_(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Record an offline or manual payment against an invoice. Accepts an optional paymentMethod (e.g. &quot;cash&quot;, &quot;bank_transfer&quot;, &quot;check&quot;, &quot;manual&quot;).
   */
  public CompletableFuture<InvoiceResponse> markPaid(String id) {
    return this.rawClient.markPaid(id).thenApply(response -> response.body());
  }

  /**
   * Record an offline or manual payment against an invoice. Accepts an optional paymentMethod (e.g. &quot;cash&quot;, &quot;bank_transfer&quot;, &quot;check&quot;, &quot;manual&quot;).
   */
  public CompletableFuture<InvoiceResponse> markPaid(String id, RequestOptions requestOptions) {
    return this.rawClient.markPaid(id, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Record an offline or manual payment against an invoice. Accepts an optional paymentMethod (e.g. &quot;cash&quot;, &quot;bank_transfer&quot;, &quot;check&quot;, &quot;manual&quot;).
   */
  public CompletableFuture<InvoiceResponse> markPaid(String id, MarkPaidInvoicesRequest request) {
    return this.rawClient.markPaid(id, request).thenApply(response -> response.body());
  }

  /**
   * Record an offline or manual payment against an invoice. Accepts an optional paymentMethod (e.g. &quot;cash&quot;, &quot;bank_transfer&quot;, &quot;check&quot;, &quot;manual&quot;).
   */
  public CompletableFuture<InvoiceResponse> markPaid(String id, MarkPaidInvoicesRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.markPaid(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Initiate a payment session with the configured payment provider (Stripe, Paystack, Flutterwave, or M-Pesa). Returns a checkout URL that redirects the customer to the provider's hosted payment page.
   */
  public CompletableFuture<CheckoutResponse> createCheckout(String id) {
    return this.rawClient.createCheckout(id).thenApply(response -> response.body());
  }

  /**
   * Initiate a payment session with the configured payment provider (Stripe, Paystack, Flutterwave, or M-Pesa). Returns a checkout URL that redirects the customer to the provider's hosted payment page.
   */
  public CompletableFuture<CheckoutResponse> createCheckout(String id,
      RequestOptions requestOptions) {
    return this.rawClient.createCheckout(id, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Initiate a payment session with the configured payment provider (Stripe, Paystack, Flutterwave, or M-Pesa). Returns a checkout URL that redirects the customer to the provider's hosted payment page.
   */
  public CompletableFuture<CheckoutResponse> createCheckout(String id,
      CreateCheckoutInvoicesRequest request) {
    return this.rawClient.createCheckout(id, request).thenApply(response -> response.body());
  }

  /**
   * Initiate a payment session with the configured payment provider (Stripe, Paystack, Flutterwave, or M-Pesa). Returns a checkout URL that redirects the customer to the provider's hosted payment page.
   */
  public CompletableFuture<CheckoutResponse> createCheckout(String id,
      CreateCheckoutInvoicesRequest request, RequestOptions requestOptions) {
    return this.rawClient.createCheckout(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Send the invoice to a specified email address, or to the customer's email if none is provided.
   */
  public CompletableFuture<MessageResponse> sendEmail(String id) {
    return this.rawClient.sendEmail(id).thenApply(response -> response.body());
  }

  /**
   * Send the invoice to a specified email address, or to the customer's email if none is provided.
   */
  public CompletableFuture<MessageResponse> sendEmail(String id, RequestOptions requestOptions) {
    return this.rawClient.sendEmail(id, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Send the invoice to a specified email address, or to the customer's email if none is provided.
   */
  public CompletableFuture<MessageResponse> sendEmail(String id, SendEmailInvoicesRequest request) {
    return this.rawClient.sendEmail(id, request).thenApply(response -> response.body());
  }

  /**
   * Send the invoice to a specified email address, or to the customer's email if none is provided.
   */
  public CompletableFuture<MessageResponse> sendEmail(String id, SendEmailInvoicesRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.sendEmail(id, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the PDF binary for the invoice. If a PDF has not been generated yet, it will be created on-demand.
   */
  public CompletableFuture<Void> getPdf(String id) {
    return this.rawClient.getPdf(id).thenApply(response -> response.body());
  }

  /**
   * Returns the PDF binary for the invoice. If a PDF has not been generated yet, it will be created on-demand.
   */
  public CompletableFuture<Void> getPdf(String id, RequestOptions requestOptions) {
    return this.rawClient.getPdf(id, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Returns the PDF binary for the invoice. If a PDF has not been generated yet, it will be created on-demand.
   */
  public CompletableFuture<Void> getPdf(String id, GetPdfInvoicesRequest request) {
    return this.rawClient.getPdf(id, request).thenApply(response -> response.body());
  }

  /**
   * Returns the PDF binary for the invoice. If a PDF has not been generated yet, it will be created on-demand.
   */
  public CompletableFuture<Void> getPdf(String id, GetPdfInvoicesRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getPdf(id, request, requestOptions).thenApply(response -> response.body());
  }
}
