/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.auth.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ForgotPasswordDto.Builder.class
)
public final class ForgotPasswordDto {
  private final String email;

  private final Map<String, Object> additionalProperties;

  private ForgotPasswordDto(String email, Map<String, Object> additionalProperties) {
    this.email = email;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("email")
  public String getEmail() {
    return email;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ForgotPasswordDto && equalTo((ForgotPasswordDto) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ForgotPasswordDto other) {
    return email.equals(other.email);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.email);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static EmailStage builder() {
    return new Builder();
  }

  public interface EmailStage {
    _FinalStage email(@NotNull String email);

    Builder from(ForgotPasswordDto other);
  }

  public interface _FinalStage {
    ForgotPasswordDto build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements EmailStage, _FinalStage {
    private String email;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ForgotPasswordDto other) {
      email(other.getEmail());
      return this;
    }

    @java.lang.Override
    @JsonSetter("email")
    public _FinalStage email(@NotNull String email) {
      this.email = Objects.requireNonNull(email, "email must not be null");
      return this;
    }

    @java.lang.Override
    public ForgotPasswordDto build() {
      return new ForgotPasswordDto(email, additionalProperties);
    }
  }
}
