/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.auth.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = LoginDto.Builder.class
)
public final class LoginDto {
  private final String email;

  private final String password;

  private final Map<String, Object> additionalProperties;

  private LoginDto(String email, String password, Map<String, Object> additionalProperties) {
    this.email = email;
    this.password = password;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("email")
  public String getEmail() {
    return email;
  }

  @JsonProperty("password")
  public String getPassword() {
    return password;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof LoginDto && equalTo((LoginDto) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(LoginDto other) {
    return email.equals(other.email) && password.equals(other.password);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.email, this.password);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static EmailStage builder() {
    return new Builder();
  }

  public interface EmailStage {
    PasswordStage email(@NotNull String email);

    Builder from(LoginDto other);
  }

  public interface PasswordStage {
    _FinalStage password(@NotNull String password);
  }

  public interface _FinalStage {
    LoginDto build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements EmailStage, PasswordStage, _FinalStage {
    private String email;

    private String password;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(LoginDto other) {
      email(other.getEmail());
      password(other.getPassword());
      return this;
    }

    @java.lang.Override
    @JsonSetter("email")
    public PasswordStage email(@NotNull String email) {
      this.email = Objects.requireNonNull(email, "email must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("password")
    public _FinalStage password(@NotNull String password) {
      this.password = Objects.requireNonNull(password, "password must not be null");
      return this;
    }

    @java.lang.Override
    public LoginDto build() {
      return new LoginDto(email, password, additionalProperties);
    }
  }
}
