// Code generated by Fern. DO NOT EDIT.

package payments

import (
	context "context"
	novabillinggo "github.com/novabilling/novabilling-go"
	core "github.com/novabilling/novabilling-go/core"
	internal "github.com/novabilling/novabilling-go/internal"
	option "github.com/novabilling/novabilling-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Retrieve a paginated list of payments. Supports filtering by status, provider, invoice, and date range.
func (c *Client) List(
	ctx context.Context,
	request *novabillinggo.ListPaymentsRequest,
	opts ...option.RequestOption,
) (*novabillinggo.PaginatedPaymentResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a payment record manually. Useful for importing historical data. If status is SUCCEEDED, the associated invoice will also be marked as paid.
func (c *Client) PaymentsControllerCreate(
	ctx context.Context,
	request *novabillinggo.CreatePaymentDto,
	opts ...option.RequestOption,
) (*novabillinggo.PaymentResponse, error) {
	response, err := c.WithRawResponse.PaymentsControllerCreate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve detailed payment information including the associated invoice and customer.
func (c *Client) Get(
	ctx context.Context,
	request *novabillinggo.GetPaymentsRequest,
	opts ...option.RequestOption,
) (*novabillinggo.PaymentResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Issue a full or partial refund for a succeeded payment. If amount is omitted, the full payment amount is refunded.
func (c *Client) Refund(
	ctx context.Context,
	request *novabillinggo.RefundPaymentDto,
	opts ...option.RequestOption,
) (*novabillinggo.PaymentResponse, error) {
	response, err := c.WithRawResponse.Refund(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
