// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/novabilling/novabilling-go/internal"
	big "math/big"
)

var (
	createChargeDtoFieldPlanID             = big.NewInt(1 << 0)
	createChargeDtoFieldBillableMetricID   = big.NewInt(1 << 1)
	createChargeDtoFieldChargeModel        = big.NewInt(1 << 2)
	createChargeDtoFieldBillingTiming      = big.NewInt(1 << 3)
	createChargeDtoFieldInvoiceDisplayName = big.NewInt(1 << 4)
	createChargeDtoFieldMinAmountCents     = big.NewInt(1 << 5)
	createChargeDtoFieldProrated           = big.NewInt(1 << 6)
	createChargeDtoFieldProperties         = big.NewInt(1 << 7)
	createChargeDtoFieldGraduatedRanges    = big.NewInt(1 << 8)
	createChargeDtoFieldFilters            = big.NewInt(1 << 9)
)

type CreateChargeDto struct {
	// Plan ID to attach this charge to
	PlanID string `json:"planId" url:"-"`
	// Billable metric ID
	BillableMetricID string                        `json:"billableMetricId" url:"-"`
	ChargeModel      CreateChargeDtoChargeModel    `json:"chargeModel" url:"-"`
	BillingTiming    *CreateChargeDtoBillingTiming `json:"billingTiming,omitempty" url:"-"`
	// Display name on invoices
	InvoiceDisplayName *string `json:"invoiceDisplayName,omitempty" url:"-"`
	// Minimum charge in cents
	MinAmountCents *float64 `json:"minAmountCents,omitempty" url:"-"`
	Prorated       *bool    `json:"prorated,omitempty" url:"-"`
	// Model-specific config. Standard: { amount, currency }. Package: { amount, packageSize, currency }. Percentage: { rate, fixedAmount, freeUnitsPerEvent, freeUnitsPerTotalAggregation }
	Properties map[string]interface{} `json:"properties,omitempty" url:"-"`
	// Required for GRADUATED and VOLUME charge models
	GraduatedRanges []*GraduatedRangeDto `json:"graduatedRanges,omitempty" url:"-"`
	Filters         []*ChargeFilterDto   `json:"filters,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateChargeDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetPlanID sets the PlanID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateChargeDto) SetPlanID(planID string) {
	c.PlanID = planID
	c.require(createChargeDtoFieldPlanID)
}

// SetBillableMetricID sets the BillableMetricID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateChargeDto) SetBillableMetricID(billableMetricID string) {
	c.BillableMetricID = billableMetricID
	c.require(createChargeDtoFieldBillableMetricID)
}

// SetChargeModel sets the ChargeModel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateChargeDto) SetChargeModel(chargeModel CreateChargeDtoChargeModel) {
	c.ChargeModel = chargeModel
	c.require(createChargeDtoFieldChargeModel)
}

// SetBillingTiming sets the BillingTiming field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateChargeDto) SetBillingTiming(billingTiming *CreateChargeDtoBillingTiming) {
	c.BillingTiming = billingTiming
	c.require(createChargeDtoFieldBillingTiming)
}

// SetInvoiceDisplayName sets the InvoiceDisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateChargeDto) SetInvoiceDisplayName(invoiceDisplayName *string) {
	c.InvoiceDisplayName = invoiceDisplayName
	c.require(createChargeDtoFieldInvoiceDisplayName)
}

// SetMinAmountCents sets the MinAmountCents field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateChargeDto) SetMinAmountCents(minAmountCents *float64) {
	c.MinAmountCents = minAmountCents
	c.require(createChargeDtoFieldMinAmountCents)
}

// SetProrated sets the Prorated field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateChargeDto) SetProrated(prorated *bool) {
	c.Prorated = prorated
	c.require(createChargeDtoFieldProrated)
}

// SetProperties sets the Properties field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateChargeDto) SetProperties(properties map[string]interface{}) {
	c.Properties = properties
	c.require(createChargeDtoFieldProperties)
}

// SetGraduatedRanges sets the GraduatedRanges field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateChargeDto) SetGraduatedRanges(graduatedRanges []*GraduatedRangeDto) {
	c.GraduatedRanges = graduatedRanges
	c.require(createChargeDtoFieldGraduatedRanges)
}

// SetFilters sets the Filters field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateChargeDto) SetFilters(filters []*ChargeFilterDto) {
	c.Filters = filters
	c.require(createChargeDtoFieldFilters)
}

func (c *CreateChargeDto) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateChargeDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateChargeDto(body)
	return nil
}

func (c *CreateChargeDto) MarshalJSON() ([]byte, error) {
	type embed CreateChargeDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteChargesRequestFieldID = big.NewInt(1 << 0)
)

type DeleteChargesRequest struct {
	// Charge ID
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteChargesRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteChargesRequest) SetID(id string) {
	d.ID = id
	d.require(deleteChargesRequestFieldID)
}

var (
	getChargesRequestFieldID = big.NewInt(1 << 0)
)

type GetChargesRequest struct {
	// Charge ID
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetChargesRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetChargesRequest) SetID(id string) {
	g.ID = id
	g.require(getChargesRequestFieldID)
}

var (
	getByPlanChargesRequestFieldPlanID = big.NewInt(1 << 0)
)

type GetByPlanChargesRequest struct {
	// Plan ID
	PlanID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetByPlanChargesRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetPlanID sets the PlanID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetByPlanChargesRequest) SetPlanID(planID string) {
	g.PlanID = planID
	g.require(getByPlanChargesRequestFieldPlanID)
}

var (
	listChargesRequestFieldPlanID = big.NewInt(1 << 0)
)

type ListChargesRequest struct {
	// Filter by plan ID
	PlanID *string `json:"-" url:"planId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListChargesRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetPlanID sets the PlanID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListChargesRequest) SetPlanID(planID *string) {
	l.PlanID = planID
	l.require(listChargesRequestFieldPlanID)
}

var (
	chargeFilterDtoFieldKey        = big.NewInt(1 << 0)
	chargeFilterDtoFieldValues     = big.NewInt(1 << 1)
	chargeFilterDtoFieldProperties = big.NewInt(1 << 2)
)

type ChargeFilterDto struct {
	// Filter key (must match metric filter)
	Key string `json:"key" url:"key"`
	// Subset of allowed values
	Values []string `json:"values" url:"values"`
	// Override properties for this filter
	Properties map[string]interface{} `json:"properties,omitempty" url:"properties,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ChargeFilterDto) GetKey() string {
	if c == nil {
		return ""
	}
	return c.Key
}

func (c *ChargeFilterDto) GetValues() []string {
	if c == nil {
		return nil
	}
	return c.Values
}

func (c *ChargeFilterDto) GetProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.Properties
}

func (c *ChargeFilterDto) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ChargeFilterDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetKey sets the Key field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeFilterDto) SetKey(key string) {
	c.Key = key
	c.require(chargeFilterDtoFieldKey)
}

// SetValues sets the Values field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeFilterDto) SetValues(values []string) {
	c.Values = values
	c.require(chargeFilterDtoFieldValues)
}

// SetProperties sets the Properties field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeFilterDto) SetProperties(properties map[string]interface{}) {
	c.Properties = properties
	c.require(chargeFilterDtoFieldProperties)
}

func (c *ChargeFilterDto) UnmarshalJSON(data []byte) error {
	type unmarshaler ChargeFilterDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ChargeFilterDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ChargeFilterDto) MarshalJSON() ([]byte, error) {
	type embed ChargeFilterDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ChargeFilterDto) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	chargeFilterResponseFieldID         = big.NewInt(1 << 0)
	chargeFilterResponseFieldChargeID   = big.NewInt(1 << 1)
	chargeFilterResponseFieldKey        = big.NewInt(1 << 2)
	chargeFilterResponseFieldValues     = big.NewInt(1 << 3)
	chargeFilterResponseFieldProperties = big.NewInt(1 << 4)
)

type ChargeFilterResponse struct {
	ID         string                 `json:"id" url:"id"`
	ChargeID   string                 `json:"chargeId" url:"chargeId"`
	Key        string                 `json:"key" url:"key"`
	Values     []string               `json:"values" url:"values"`
	Properties map[string]interface{} `json:"properties,omitempty" url:"properties,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ChargeFilterResponse) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *ChargeFilterResponse) GetChargeID() string {
	if c == nil {
		return ""
	}
	return c.ChargeID
}

func (c *ChargeFilterResponse) GetKey() string {
	if c == nil {
		return ""
	}
	return c.Key
}

func (c *ChargeFilterResponse) GetValues() []string {
	if c == nil {
		return nil
	}
	return c.Values
}

func (c *ChargeFilterResponse) GetProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.Properties
}

func (c *ChargeFilterResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ChargeFilterResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeFilterResponse) SetID(id string) {
	c.ID = id
	c.require(chargeFilterResponseFieldID)
}

// SetChargeID sets the ChargeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeFilterResponse) SetChargeID(chargeID string) {
	c.ChargeID = chargeID
	c.require(chargeFilterResponseFieldChargeID)
}

// SetKey sets the Key field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeFilterResponse) SetKey(key string) {
	c.Key = key
	c.require(chargeFilterResponseFieldKey)
}

// SetValues sets the Values field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeFilterResponse) SetValues(values []string) {
	c.Values = values
	c.require(chargeFilterResponseFieldValues)
}

// SetProperties sets the Properties field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeFilterResponse) SetProperties(properties map[string]interface{}) {
	c.Properties = properties
	c.require(chargeFilterResponseFieldProperties)
}

func (c *ChargeFilterResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ChargeFilterResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ChargeFilterResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ChargeFilterResponse) MarshalJSON() ([]byte, error) {
	type embed ChargeFilterResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ChargeFilterResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	chargeGraduatedRangeResponseFieldID            = big.NewInt(1 << 0)
	chargeGraduatedRangeResponseFieldChargeID      = big.NewInt(1 << 1)
	chargeGraduatedRangeResponseFieldFromValue     = big.NewInt(1 << 2)
	chargeGraduatedRangeResponseFieldToValue       = big.NewInt(1 << 3)
	chargeGraduatedRangeResponseFieldPerUnitAmount = big.NewInt(1 << 4)
	chargeGraduatedRangeResponseFieldFlatAmount    = big.NewInt(1 << 5)
	chargeGraduatedRangeResponseFieldOrder         = big.NewInt(1 << 6)
)

type ChargeGraduatedRangeResponse struct {
	ID        string   `json:"id" url:"id"`
	ChargeID  string   `json:"chargeId" url:"chargeId"`
	FromValue float64  `json:"fromValue" url:"fromValue"`
	ToValue   *float64 `json:"toValue,omitempty" url:"toValue,omitempty"`
	// Per-unit amount as decimal string
	PerUnitAmount string `json:"perUnitAmount" url:"perUnitAmount"`
	// Flat fee for this range
	FlatAmount string  `json:"flatAmount" url:"flatAmount"`
	Order      float64 `json:"order" url:"order"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ChargeGraduatedRangeResponse) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *ChargeGraduatedRangeResponse) GetChargeID() string {
	if c == nil {
		return ""
	}
	return c.ChargeID
}

func (c *ChargeGraduatedRangeResponse) GetFromValue() float64 {
	if c == nil {
		return 0
	}
	return c.FromValue
}

func (c *ChargeGraduatedRangeResponse) GetToValue() *float64 {
	if c == nil {
		return nil
	}
	return c.ToValue
}

func (c *ChargeGraduatedRangeResponse) GetPerUnitAmount() string {
	if c == nil {
		return ""
	}
	return c.PerUnitAmount
}

func (c *ChargeGraduatedRangeResponse) GetFlatAmount() string {
	if c == nil {
		return ""
	}
	return c.FlatAmount
}

func (c *ChargeGraduatedRangeResponse) GetOrder() float64 {
	if c == nil {
		return 0
	}
	return c.Order
}

func (c *ChargeGraduatedRangeResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ChargeGraduatedRangeResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeGraduatedRangeResponse) SetID(id string) {
	c.ID = id
	c.require(chargeGraduatedRangeResponseFieldID)
}

// SetChargeID sets the ChargeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeGraduatedRangeResponse) SetChargeID(chargeID string) {
	c.ChargeID = chargeID
	c.require(chargeGraduatedRangeResponseFieldChargeID)
}

// SetFromValue sets the FromValue field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeGraduatedRangeResponse) SetFromValue(fromValue float64) {
	c.FromValue = fromValue
	c.require(chargeGraduatedRangeResponseFieldFromValue)
}

// SetToValue sets the ToValue field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeGraduatedRangeResponse) SetToValue(toValue *float64) {
	c.ToValue = toValue
	c.require(chargeGraduatedRangeResponseFieldToValue)
}

// SetPerUnitAmount sets the PerUnitAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeGraduatedRangeResponse) SetPerUnitAmount(perUnitAmount string) {
	c.PerUnitAmount = perUnitAmount
	c.require(chargeGraduatedRangeResponseFieldPerUnitAmount)
}

// SetFlatAmount sets the FlatAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeGraduatedRangeResponse) SetFlatAmount(flatAmount string) {
	c.FlatAmount = flatAmount
	c.require(chargeGraduatedRangeResponseFieldFlatAmount)
}

// SetOrder sets the Order field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeGraduatedRangeResponse) SetOrder(order float64) {
	c.Order = order
	c.require(chargeGraduatedRangeResponseFieldOrder)
}

func (c *ChargeGraduatedRangeResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ChargeGraduatedRangeResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ChargeGraduatedRangeResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ChargeGraduatedRangeResponse) MarshalJSON() ([]byte, error) {
	type embed ChargeGraduatedRangeResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ChargeGraduatedRangeResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	chargeResponseFieldID                 = big.NewInt(1 << 0)
	chargeResponseFieldPlanID             = big.NewInt(1 << 1)
	chargeResponseFieldBillableMetricID   = big.NewInt(1 << 2)
	chargeResponseFieldChargeModel        = big.NewInt(1 << 3)
	chargeResponseFieldBillingTiming      = big.NewInt(1 << 4)
	chargeResponseFieldInvoiceDisplayName = big.NewInt(1 << 5)
	chargeResponseFieldMinAmountCents     = big.NewInt(1 << 6)
	chargeResponseFieldProrated           = big.NewInt(1 << 7)
	chargeResponseFieldProperties         = big.NewInt(1 << 8)
	chargeResponseFieldGraduatedRanges    = big.NewInt(1 << 9)
	chargeResponseFieldFilters            = big.NewInt(1 << 10)
	chargeResponseFieldCreatedAt          = big.NewInt(1 << 11)
	chargeResponseFieldUpdatedAt          = big.NewInt(1 << 12)
)

type ChargeResponse struct {
	ID                 string                      `json:"id" url:"id"`
	PlanID             string                      `json:"planId" url:"planId"`
	BillableMetricID   string                      `json:"billableMetricId" url:"billableMetricId"`
	ChargeModel        ChargeResponseChargeModel   `json:"chargeModel" url:"chargeModel"`
	BillingTiming      ChargeResponseBillingTiming `json:"billingTiming" url:"billingTiming"`
	InvoiceDisplayName *string                     `json:"invoiceDisplayName,omitempty" url:"invoiceDisplayName,omitempty"`
	MinAmountCents     *float64                    `json:"minAmountCents,omitempty" url:"minAmountCents,omitempty"`
	Prorated           bool                        `json:"prorated" url:"prorated"`
	// Model-specific config
	Properties      map[string]interface{}          `json:"properties,omitempty" url:"properties,omitempty"`
	GraduatedRanges []*ChargeGraduatedRangeResponse `json:"graduatedRanges" url:"graduatedRanges"`
	Filters         []*ChargeFilterResponse         `json:"filters" url:"filters"`
	CreatedAt       string                          `json:"createdAt" url:"createdAt"`
	UpdatedAt       string                          `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ChargeResponse) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *ChargeResponse) GetPlanID() string {
	if c == nil {
		return ""
	}
	return c.PlanID
}

func (c *ChargeResponse) GetBillableMetricID() string {
	if c == nil {
		return ""
	}
	return c.BillableMetricID
}

func (c *ChargeResponse) GetChargeModel() ChargeResponseChargeModel {
	if c == nil {
		return ""
	}
	return c.ChargeModel
}

func (c *ChargeResponse) GetBillingTiming() ChargeResponseBillingTiming {
	if c == nil {
		return ""
	}
	return c.BillingTiming
}

func (c *ChargeResponse) GetInvoiceDisplayName() *string {
	if c == nil {
		return nil
	}
	return c.InvoiceDisplayName
}

func (c *ChargeResponse) GetMinAmountCents() *float64 {
	if c == nil {
		return nil
	}
	return c.MinAmountCents
}

func (c *ChargeResponse) GetProrated() bool {
	if c == nil {
		return false
	}
	return c.Prorated
}

func (c *ChargeResponse) GetProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.Properties
}

func (c *ChargeResponse) GetGraduatedRanges() []*ChargeGraduatedRangeResponse {
	if c == nil {
		return nil
	}
	return c.GraduatedRanges
}

func (c *ChargeResponse) GetFilters() []*ChargeFilterResponse {
	if c == nil {
		return nil
	}
	return c.Filters
}

func (c *ChargeResponse) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *ChargeResponse) GetUpdatedAt() string {
	if c == nil {
		return ""
	}
	return c.UpdatedAt
}

func (c *ChargeResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ChargeResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeResponse) SetID(id string) {
	c.ID = id
	c.require(chargeResponseFieldID)
}

// SetPlanID sets the PlanID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeResponse) SetPlanID(planID string) {
	c.PlanID = planID
	c.require(chargeResponseFieldPlanID)
}

// SetBillableMetricID sets the BillableMetricID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeResponse) SetBillableMetricID(billableMetricID string) {
	c.BillableMetricID = billableMetricID
	c.require(chargeResponseFieldBillableMetricID)
}

// SetChargeModel sets the ChargeModel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeResponse) SetChargeModel(chargeModel ChargeResponseChargeModel) {
	c.ChargeModel = chargeModel
	c.require(chargeResponseFieldChargeModel)
}

// SetBillingTiming sets the BillingTiming field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeResponse) SetBillingTiming(billingTiming ChargeResponseBillingTiming) {
	c.BillingTiming = billingTiming
	c.require(chargeResponseFieldBillingTiming)
}

// SetInvoiceDisplayName sets the InvoiceDisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeResponse) SetInvoiceDisplayName(invoiceDisplayName *string) {
	c.InvoiceDisplayName = invoiceDisplayName
	c.require(chargeResponseFieldInvoiceDisplayName)
}

// SetMinAmountCents sets the MinAmountCents field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeResponse) SetMinAmountCents(minAmountCents *float64) {
	c.MinAmountCents = minAmountCents
	c.require(chargeResponseFieldMinAmountCents)
}

// SetProrated sets the Prorated field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeResponse) SetProrated(prorated bool) {
	c.Prorated = prorated
	c.require(chargeResponseFieldProrated)
}

// SetProperties sets the Properties field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeResponse) SetProperties(properties map[string]interface{}) {
	c.Properties = properties
	c.require(chargeResponseFieldProperties)
}

// SetGraduatedRanges sets the GraduatedRanges field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeResponse) SetGraduatedRanges(graduatedRanges []*ChargeGraduatedRangeResponse) {
	c.GraduatedRanges = graduatedRanges
	c.require(chargeResponseFieldGraduatedRanges)
}

// SetFilters sets the Filters field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeResponse) SetFilters(filters []*ChargeFilterResponse) {
	c.Filters = filters
	c.require(chargeResponseFieldFilters)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeResponse) SetCreatedAt(createdAt string) {
	c.CreatedAt = createdAt
	c.require(chargeResponseFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ChargeResponse) SetUpdatedAt(updatedAt string) {
	c.UpdatedAt = updatedAt
	c.require(chargeResponseFieldUpdatedAt)
}

func (c *ChargeResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ChargeResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ChargeResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ChargeResponse) MarshalJSON() ([]byte, error) {
	type embed ChargeResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ChargeResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ChargeResponseBillingTiming string

const (
	ChargeResponseBillingTimingInAdvance ChargeResponseBillingTiming = "IN_ADVANCE"
	ChargeResponseBillingTimingInArrears ChargeResponseBillingTiming = "IN_ARREARS"
)

func NewChargeResponseBillingTimingFromString(s string) (ChargeResponseBillingTiming, error) {
	switch s {
	case "IN_ADVANCE":
		return ChargeResponseBillingTimingInAdvance, nil
	case "IN_ARREARS":
		return ChargeResponseBillingTimingInArrears, nil
	}
	var t ChargeResponseBillingTiming
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c ChargeResponseBillingTiming) Ptr() *ChargeResponseBillingTiming {
	return &c
}

type ChargeResponseChargeModel string

const (
	ChargeResponseChargeModelStandard   ChargeResponseChargeModel = "STANDARD"
	ChargeResponseChargeModelGraduated  ChargeResponseChargeModel = "GRADUATED"
	ChargeResponseChargeModelVolume     ChargeResponseChargeModel = "VOLUME"
	ChargeResponseChargeModelPackage    ChargeResponseChargeModel = "PACKAGE"
	ChargeResponseChargeModelPercentage ChargeResponseChargeModel = "PERCENTAGE"
)

func NewChargeResponseChargeModelFromString(s string) (ChargeResponseChargeModel, error) {
	switch s {
	case "STANDARD":
		return ChargeResponseChargeModelStandard, nil
	case "GRADUATED":
		return ChargeResponseChargeModelGraduated, nil
	case "VOLUME":
		return ChargeResponseChargeModelVolume, nil
	case "PACKAGE":
		return ChargeResponseChargeModelPackage, nil
	case "PERCENTAGE":
		return ChargeResponseChargeModelPercentage, nil
	}
	var t ChargeResponseChargeModel
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c ChargeResponseChargeModel) Ptr() *ChargeResponseChargeModel {
	return &c
}

var (
	graduatedRangeDtoFieldFromValue     = big.NewInt(1 << 0)
	graduatedRangeDtoFieldToValue       = big.NewInt(1 << 1)
	graduatedRangeDtoFieldPerUnitAmount = big.NewInt(1 << 2)
	graduatedRangeDtoFieldFlatAmount    = big.NewInt(1 << 3)
)

type GraduatedRangeDto struct {
	// Start of range (inclusive)
	FromValue float64 `json:"fromValue" url:"fromValue"`
	// End of range (inclusive), null = infinity
	ToValue *float64 `json:"toValue,omitempty" url:"toValue,omitempty"`
	// Price per unit in this range
	PerUnitAmount float64 `json:"perUnitAmount" url:"perUnitAmount"`
	// Flat fee for entering this range
	FlatAmount *float64 `json:"flatAmount,omitempty" url:"flatAmount,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GraduatedRangeDto) GetFromValue() float64 {
	if g == nil {
		return 0
	}
	return g.FromValue
}

func (g *GraduatedRangeDto) GetToValue() *float64 {
	if g == nil {
		return nil
	}
	return g.ToValue
}

func (g *GraduatedRangeDto) GetPerUnitAmount() float64 {
	if g == nil {
		return 0
	}
	return g.PerUnitAmount
}

func (g *GraduatedRangeDto) GetFlatAmount() *float64 {
	if g == nil {
		return nil
	}
	return g.FlatAmount
}

func (g *GraduatedRangeDto) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GraduatedRangeDto) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetFromValue sets the FromValue field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GraduatedRangeDto) SetFromValue(fromValue float64) {
	g.FromValue = fromValue
	g.require(graduatedRangeDtoFieldFromValue)
}

// SetToValue sets the ToValue field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GraduatedRangeDto) SetToValue(toValue *float64) {
	g.ToValue = toValue
	g.require(graduatedRangeDtoFieldToValue)
}

// SetPerUnitAmount sets the PerUnitAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GraduatedRangeDto) SetPerUnitAmount(perUnitAmount float64) {
	g.PerUnitAmount = perUnitAmount
	g.require(graduatedRangeDtoFieldPerUnitAmount)
}

// SetFlatAmount sets the FlatAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GraduatedRangeDto) SetFlatAmount(flatAmount *float64) {
	g.FlatAmount = flatAmount
	g.require(graduatedRangeDtoFieldFlatAmount)
}

func (g *GraduatedRangeDto) UnmarshalJSON(data []byte) error {
	type unmarshaler GraduatedRangeDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GraduatedRangeDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GraduatedRangeDto) MarshalJSON() ([]byte, error) {
	type embed GraduatedRangeDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GraduatedRangeDto) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type CreateChargeDtoBillingTiming string

const (
	CreateChargeDtoBillingTimingInAdvance CreateChargeDtoBillingTiming = "IN_ADVANCE"
	CreateChargeDtoBillingTimingInArrears CreateChargeDtoBillingTiming = "IN_ARREARS"
)

func NewCreateChargeDtoBillingTimingFromString(s string) (CreateChargeDtoBillingTiming, error) {
	switch s {
	case "IN_ADVANCE":
		return CreateChargeDtoBillingTimingInAdvance, nil
	case "IN_ARREARS":
		return CreateChargeDtoBillingTimingInArrears, nil
	}
	var t CreateChargeDtoBillingTiming
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateChargeDtoBillingTiming) Ptr() *CreateChargeDtoBillingTiming {
	return &c
}

type CreateChargeDtoChargeModel string

const (
	CreateChargeDtoChargeModelStandard   CreateChargeDtoChargeModel = "STANDARD"
	CreateChargeDtoChargeModelGraduated  CreateChargeDtoChargeModel = "GRADUATED"
	CreateChargeDtoChargeModelVolume     CreateChargeDtoChargeModel = "VOLUME"
	CreateChargeDtoChargeModelPackage    CreateChargeDtoChargeModel = "PACKAGE"
	CreateChargeDtoChargeModelPercentage CreateChargeDtoChargeModel = "PERCENTAGE"
)

func NewCreateChargeDtoChargeModelFromString(s string) (CreateChargeDtoChargeModel, error) {
	switch s {
	case "STANDARD":
		return CreateChargeDtoChargeModelStandard, nil
	case "GRADUATED":
		return CreateChargeDtoChargeModelGraduated, nil
	case "VOLUME":
		return CreateChargeDtoChargeModelVolume, nil
	case "PACKAGE":
		return CreateChargeDtoChargeModelPackage, nil
	case "PERCENTAGE":
		return CreateChargeDtoChargeModelPercentage, nil
	}
	var t CreateChargeDtoChargeModel
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateChargeDtoChargeModel) Ptr() *CreateChargeDtoChargeModel {
	return &c
}

type UpdateChargeDtoBillingTiming string

const (
	UpdateChargeDtoBillingTimingInAdvance UpdateChargeDtoBillingTiming = "IN_ADVANCE"
	UpdateChargeDtoBillingTimingInArrears UpdateChargeDtoBillingTiming = "IN_ARREARS"
)

func NewUpdateChargeDtoBillingTimingFromString(s string) (UpdateChargeDtoBillingTiming, error) {
	switch s {
	case "IN_ADVANCE":
		return UpdateChargeDtoBillingTimingInAdvance, nil
	case "IN_ARREARS":
		return UpdateChargeDtoBillingTimingInArrears, nil
	}
	var t UpdateChargeDtoBillingTiming
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateChargeDtoBillingTiming) Ptr() *UpdateChargeDtoBillingTiming {
	return &u
}

var (
	updateChargeDtoFieldID                 = big.NewInt(1 << 0)
	updateChargeDtoFieldBillingTiming      = big.NewInt(1 << 1)
	updateChargeDtoFieldInvoiceDisplayName = big.NewInt(1 << 2)
	updateChargeDtoFieldMinAmountCents     = big.NewInt(1 << 3)
	updateChargeDtoFieldProrated           = big.NewInt(1 << 4)
	updateChargeDtoFieldProperties         = big.NewInt(1 << 5)
	updateChargeDtoFieldGraduatedRanges    = big.NewInt(1 << 6)
	updateChargeDtoFieldFilters            = big.NewInt(1 << 7)
)

type UpdateChargeDto struct {
	// Charge ID
	ID                 string                        `json:"-" url:"-"`
	BillingTiming      *UpdateChargeDtoBillingTiming `json:"billingTiming,omitempty" url:"-"`
	InvoiceDisplayName *string                       `json:"invoiceDisplayName,omitempty" url:"-"`
	MinAmountCents     *float64                      `json:"minAmountCents,omitempty" url:"-"`
	Prorated           *bool                         `json:"prorated,omitempty" url:"-"`
	Properties         map[string]interface{}        `json:"properties,omitempty" url:"-"`
	GraduatedRanges    []*GraduatedRangeDto          `json:"graduatedRanges,omitempty" url:"-"`
	Filters            []*ChargeFilterDto            `json:"filters,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateChargeDto) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateChargeDto) SetID(id string) {
	u.ID = id
	u.require(updateChargeDtoFieldID)
}

// SetBillingTiming sets the BillingTiming field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateChargeDto) SetBillingTiming(billingTiming *UpdateChargeDtoBillingTiming) {
	u.BillingTiming = billingTiming
	u.require(updateChargeDtoFieldBillingTiming)
}

// SetInvoiceDisplayName sets the InvoiceDisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateChargeDto) SetInvoiceDisplayName(invoiceDisplayName *string) {
	u.InvoiceDisplayName = invoiceDisplayName
	u.require(updateChargeDtoFieldInvoiceDisplayName)
}

// SetMinAmountCents sets the MinAmountCents field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateChargeDto) SetMinAmountCents(minAmountCents *float64) {
	u.MinAmountCents = minAmountCents
	u.require(updateChargeDtoFieldMinAmountCents)
}

// SetProrated sets the Prorated field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateChargeDto) SetProrated(prorated *bool) {
	u.Prorated = prorated
	u.require(updateChargeDtoFieldProrated)
}

// SetProperties sets the Properties field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateChargeDto) SetProperties(properties map[string]interface{}) {
	u.Properties = properties
	u.require(updateChargeDtoFieldProperties)
}

// SetGraduatedRanges sets the GraduatedRanges field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateChargeDto) SetGraduatedRanges(graduatedRanges []*GraduatedRangeDto) {
	u.GraduatedRanges = graduatedRanges
	u.require(updateChargeDtoFieldGraduatedRanges)
}

// SetFilters sets the Filters field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateChargeDto) SetFilters(filters []*ChargeFilterDto) {
	u.Filters = filters
	u.require(updateChargeDtoFieldFilters)
}

func (u *UpdateChargeDto) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateChargeDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateChargeDto(body)
	return nil
}

func (u *UpdateChargeDto) MarshalJSON() ([]byte, error) {
	type embed UpdateChargeDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
