// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/novabilling/novabilling-go/internal"
	big "math/big"
)

var (
	updateCreditNoteDtoFieldID       = big.NewInt(1 << 0)
	updateCreditNoteDtoFieldAmount   = big.NewInt(1 << 1)
	updateCreditNoteDtoFieldReason   = big.NewInt(1 << 2)
	updateCreditNoteDtoFieldMetadata = big.NewInt(1 << 3)
)

type UpdateCreditNoteDto struct {
	// Credit note ID
	ID string `json:"-" url:"-"`
	// Updated amount
	Amount   *float64                   `json:"amount,omitempty" url:"-"`
	Reason   *UpdateCreditNoteDtoReason `json:"reason,omitempty" url:"-"`
	Metadata map[string]interface{}     `json:"metadata,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateCreditNoteDto) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCreditNoteDto) SetID(id string) {
	u.ID = id
	u.require(updateCreditNoteDtoFieldID)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCreditNoteDto) SetAmount(amount *float64) {
	u.Amount = amount
	u.require(updateCreditNoteDtoFieldAmount)
}

// SetReason sets the Reason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCreditNoteDto) SetReason(reason *UpdateCreditNoteDtoReason) {
	u.Reason = reason
	u.require(updateCreditNoteDtoFieldReason)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCreditNoteDto) SetMetadata(metadata map[string]interface{}) {
	u.Metadata = metadata
	u.require(updateCreditNoteDtoFieldMetadata)
}

func (u *UpdateCreditNoteDto) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateCreditNoteDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateCreditNoteDto(body)
	return nil
}

func (u *UpdateCreditNoteDto) MarshalJSON() ([]byte, error) {
	type embed UpdateCreditNoteDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createCreditNoteDtoFieldInvoiceID  = big.NewInt(1 << 0)
	createCreditNoteDtoFieldCustomerID = big.NewInt(1 << 1)
	createCreditNoteDtoFieldAmount     = big.NewInt(1 << 2)
	createCreditNoteDtoFieldCurrency   = big.NewInt(1 << 3)
	createCreditNoteDtoFieldReason     = big.NewInt(1 << 4)
	createCreditNoteDtoFieldMetadata   = big.NewInt(1 << 5)
	createCreditNoteDtoFieldStatus     = big.NewInt(1 << 6)
	createCreditNoteDtoFieldCreatedAt  = big.NewInt(1 << 7)
)

type CreateCreditNoteDto struct {
	// Invoice ID to credit against
	InvoiceID string `json:"invoiceId" url:"-"`
	// Customer ID
	CustomerID string `json:"customerId" url:"-"`
	// Credit amount
	Amount float64 `json:"amount" url:"-"`
	// Currency
	Currency string                    `json:"currency" url:"-"`
	Reason   CreateCreditNoteDtoReason `json:"reason" url:"-"`
	// Additional metadata
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"-"`
	// Override status for imports
	Status *CreateCreditNoteDtoStatus `json:"status,omitempty" url:"-"`
	// Backdate createdAt (ISO 8601). For data imports.
	CreatedAt *string `json:"createdAt,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateCreditNoteDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetInvoiceID sets the InvoiceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCreditNoteDto) SetInvoiceID(invoiceID string) {
	c.InvoiceID = invoiceID
	c.require(createCreditNoteDtoFieldInvoiceID)
}

// SetCustomerID sets the CustomerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCreditNoteDto) SetCustomerID(customerID string) {
	c.CustomerID = customerID
	c.require(createCreditNoteDtoFieldCustomerID)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCreditNoteDto) SetAmount(amount float64) {
	c.Amount = amount
	c.require(createCreditNoteDtoFieldAmount)
}

// SetCurrency sets the Currency field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCreditNoteDto) SetCurrency(currency string) {
	c.Currency = currency
	c.require(createCreditNoteDtoFieldCurrency)
}

// SetReason sets the Reason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCreditNoteDto) SetReason(reason CreateCreditNoteDtoReason) {
	c.Reason = reason
	c.require(createCreditNoteDtoFieldReason)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCreditNoteDto) SetMetadata(metadata map[string]interface{}) {
	c.Metadata = metadata
	c.require(createCreditNoteDtoFieldMetadata)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCreditNoteDto) SetStatus(status *CreateCreditNoteDtoStatus) {
	c.Status = status
	c.require(createCreditNoteDtoFieldStatus)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCreditNoteDto) SetCreatedAt(createdAt *string) {
	c.CreatedAt = createdAt
	c.require(createCreditNoteDtoFieldCreatedAt)
}

func (c *CreateCreditNoteDto) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateCreditNoteDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateCreditNoteDto(body)
	return nil
}

func (c *CreateCreditNoteDto) MarshalJSON() ([]byte, error) {
	type embed CreateCreditNoteDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	finalizeCreditNotesRequestFieldID = big.NewInt(1 << 0)
)

type FinalizeCreditNotesRequest struct {
	// Credit note ID
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (f *FinalizeCreditNotesRequest) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FinalizeCreditNotesRequest) SetID(id string) {
	f.ID = id
	f.require(finalizeCreditNotesRequestFieldID)
}

var (
	getCreditNotesRequestFieldID = big.NewInt(1 << 0)
)

type GetCreditNotesRequest struct {
	// Credit note ID
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetCreditNotesRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCreditNotesRequest) SetID(id string) {
	g.ID = id
	g.require(getCreditNotesRequestFieldID)
}

var (
	listCreditNotesRequestFieldCustomerID = big.NewInt(1 << 0)
	listCreditNotesRequestFieldInvoiceID  = big.NewInt(1 << 1)
	listCreditNotesRequestFieldStatus     = big.NewInt(1 << 2)
	listCreditNotesRequestFieldPage       = big.NewInt(1 << 3)
	listCreditNotesRequestFieldLimit      = big.NewInt(1 << 4)
)

type ListCreditNotesRequest struct {
	CustomerID *string                       `json:"-" url:"customerId,omitempty"`
	InvoiceID  *string                       `json:"-" url:"invoiceId,omitempty"`
	Status     *ListCreditNotesRequestStatus `json:"-" url:"status,omitempty"`
	Page       *float64                      `json:"-" url:"page,omitempty"`
	Limit      *float64                      `json:"-" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListCreditNotesRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetCustomerID sets the CustomerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCreditNotesRequest) SetCustomerID(customerID *string) {
	l.CustomerID = customerID
	l.require(listCreditNotesRequestFieldCustomerID)
}

// SetInvoiceID sets the InvoiceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCreditNotesRequest) SetInvoiceID(invoiceID *string) {
	l.InvoiceID = invoiceID
	l.require(listCreditNotesRequestFieldInvoiceID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCreditNotesRequest) SetStatus(status *ListCreditNotesRequestStatus) {
	l.Status = status
	l.require(listCreditNotesRequestFieldStatus)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCreditNotesRequest) SetPage(page *float64) {
	l.Page = page
	l.require(listCreditNotesRequestFieldPage)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListCreditNotesRequest) SetLimit(limit *float64) {
	l.Limit = limit
	l.require(listCreditNotesRequestFieldLimit)
}

var (
	creditNoteResponseFieldID         = big.NewInt(1 << 0)
	creditNoteResponseFieldInvoiceID  = big.NewInt(1 << 1)
	creditNoteResponseFieldCustomerID = big.NewInt(1 << 2)
	creditNoteResponseFieldAmount     = big.NewInt(1 << 3)
	creditNoteResponseFieldCurrency   = big.NewInt(1 << 4)
	creditNoteResponseFieldReason     = big.NewInt(1 << 5)
	creditNoteResponseFieldStatus     = big.NewInt(1 << 6)
	creditNoteResponseFieldMetadata   = big.NewInt(1 << 7)
	creditNoteResponseFieldCreatedAt  = big.NewInt(1 << 8)
	creditNoteResponseFieldUpdatedAt  = big.NewInt(1 << 9)
)

type CreditNoteResponse struct {
	ID         string `json:"id" url:"id"`
	InvoiceID  string `json:"invoiceId" url:"invoiceId"`
	CustomerID string `json:"customerId" url:"customerId"`
	// Decimal amount as string
	Amount    string                   `json:"amount" url:"amount"`
	Currency  string                   `json:"currency" url:"currency"`
	Reason    CreditNoteResponseReason `json:"reason" url:"reason"`
	Status    CreditNoteResponseStatus `json:"status" url:"status"`
	Metadata  map[string]interface{}   `json:"metadata,omitempty" url:"metadata,omitempty"`
	CreatedAt string                   `json:"createdAt" url:"createdAt"`
	UpdatedAt string                   `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreditNoteResponse) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreditNoteResponse) GetInvoiceID() string {
	if c == nil {
		return ""
	}
	return c.InvoiceID
}

func (c *CreditNoteResponse) GetCustomerID() string {
	if c == nil {
		return ""
	}
	return c.CustomerID
}

func (c *CreditNoteResponse) GetAmount() string {
	if c == nil {
		return ""
	}
	return c.Amount
}

func (c *CreditNoteResponse) GetCurrency() string {
	if c == nil {
		return ""
	}
	return c.Currency
}

func (c *CreditNoteResponse) GetReason() CreditNoteResponseReason {
	if c == nil {
		return ""
	}
	return c.Reason
}

func (c *CreditNoteResponse) GetStatus() CreditNoteResponseStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CreditNoteResponse) GetMetadata() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CreditNoteResponse) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *CreditNoteResponse) GetUpdatedAt() string {
	if c == nil {
		return ""
	}
	return c.UpdatedAt
}

func (c *CreditNoteResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreditNoteResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreditNoteResponse) SetID(id string) {
	c.ID = id
	c.require(creditNoteResponseFieldID)
}

// SetInvoiceID sets the InvoiceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreditNoteResponse) SetInvoiceID(invoiceID string) {
	c.InvoiceID = invoiceID
	c.require(creditNoteResponseFieldInvoiceID)
}

// SetCustomerID sets the CustomerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreditNoteResponse) SetCustomerID(customerID string) {
	c.CustomerID = customerID
	c.require(creditNoteResponseFieldCustomerID)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreditNoteResponse) SetAmount(amount string) {
	c.Amount = amount
	c.require(creditNoteResponseFieldAmount)
}

// SetCurrency sets the Currency field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreditNoteResponse) SetCurrency(currency string) {
	c.Currency = currency
	c.require(creditNoteResponseFieldCurrency)
}

// SetReason sets the Reason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreditNoteResponse) SetReason(reason CreditNoteResponseReason) {
	c.Reason = reason
	c.require(creditNoteResponseFieldReason)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreditNoteResponse) SetStatus(status CreditNoteResponseStatus) {
	c.Status = status
	c.require(creditNoteResponseFieldStatus)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreditNoteResponse) SetMetadata(metadata map[string]interface{}) {
	c.Metadata = metadata
	c.require(creditNoteResponseFieldMetadata)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreditNoteResponse) SetCreatedAt(createdAt string) {
	c.CreatedAt = createdAt
	c.require(creditNoteResponseFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreditNoteResponse) SetUpdatedAt(updatedAt string) {
	c.UpdatedAt = updatedAt
	c.require(creditNoteResponseFieldUpdatedAt)
}

func (c *CreditNoteResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreditNoteResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreditNoteResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreditNoteResponse) MarshalJSON() ([]byte, error) {
	type embed CreditNoteResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreditNoteResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CreditNoteResponseReason string

const (
	CreditNoteResponseReasonDuplicate             CreditNoteResponseReason = "DUPLICATE"
	CreditNoteResponseReasonProductUnsatisfactory CreditNoteResponseReason = "PRODUCT_UNSATISFACTORY"
	CreditNoteResponseReasonOrderChange           CreditNoteResponseReason = "ORDER_CHANGE"
	CreditNoteResponseReasonOther                 CreditNoteResponseReason = "OTHER"
)

func NewCreditNoteResponseReasonFromString(s string) (CreditNoteResponseReason, error) {
	switch s {
	case "DUPLICATE":
		return CreditNoteResponseReasonDuplicate, nil
	case "PRODUCT_UNSATISFACTORY":
		return CreditNoteResponseReasonProductUnsatisfactory, nil
	case "ORDER_CHANGE":
		return CreditNoteResponseReasonOrderChange, nil
	case "OTHER":
		return CreditNoteResponseReasonOther, nil
	}
	var t CreditNoteResponseReason
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreditNoteResponseReason) Ptr() *CreditNoteResponseReason {
	return &c
}

type CreditNoteResponseStatus string

const (
	CreditNoteResponseStatusDraft     CreditNoteResponseStatus = "DRAFT"
	CreditNoteResponseStatusFinalized CreditNoteResponseStatus = "FINALIZED"
	CreditNoteResponseStatusVoided    CreditNoteResponseStatus = "VOIDED"
)

func NewCreditNoteResponseStatusFromString(s string) (CreditNoteResponseStatus, error) {
	switch s {
	case "DRAFT":
		return CreditNoteResponseStatusDraft, nil
	case "FINALIZED":
		return CreditNoteResponseStatusFinalized, nil
	case "VOIDED":
		return CreditNoteResponseStatusVoided, nil
	}
	var t CreditNoteResponseStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreditNoteResponseStatus) Ptr() *CreditNoteResponseStatus {
	return &c
}

var (
	paginatedCreditNoteResponseFieldData = big.NewInt(1 << 0)
	paginatedCreditNoteResponseFieldMeta = big.NewInt(1 << 1)
)

type PaginatedCreditNoteResponse struct {
	Data []*CreditNoteResponse `json:"data" url:"data"`
	Meta *PaginationMeta       `json:"meta" url:"meta"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PaginatedCreditNoteResponse) GetData() []*CreditNoteResponse {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PaginatedCreditNoteResponse) GetMeta() *PaginationMeta {
	if p == nil {
		return nil
	}
	return p.Meta
}

func (p *PaginatedCreditNoteResponse) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PaginatedCreditNoteResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedCreditNoteResponse) SetData(data []*CreditNoteResponse) {
	p.Data = data
	p.require(paginatedCreditNoteResponseFieldData)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedCreditNoteResponse) SetMeta(meta *PaginationMeta) {
	p.Meta = meta
	p.require(paginatedCreditNoteResponseFieldMeta)
}

func (p *PaginatedCreditNoteResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PaginatedCreditNoteResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaginatedCreditNoteResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaginatedCreditNoteResponse) MarshalJSON() ([]byte, error) {
	type embed PaginatedCreditNoteResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PaginatedCreditNoteResponse) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type CreateCreditNoteDtoReason string

const (
	CreateCreditNoteDtoReasonDuplicate             CreateCreditNoteDtoReason = "DUPLICATE"
	CreateCreditNoteDtoReasonProductUnsatisfactory CreateCreditNoteDtoReason = "PRODUCT_UNSATISFACTORY"
	CreateCreditNoteDtoReasonOrderChange           CreateCreditNoteDtoReason = "ORDER_CHANGE"
	CreateCreditNoteDtoReasonOther                 CreateCreditNoteDtoReason = "OTHER"
)

func NewCreateCreditNoteDtoReasonFromString(s string) (CreateCreditNoteDtoReason, error) {
	switch s {
	case "DUPLICATE":
		return CreateCreditNoteDtoReasonDuplicate, nil
	case "PRODUCT_UNSATISFACTORY":
		return CreateCreditNoteDtoReasonProductUnsatisfactory, nil
	case "ORDER_CHANGE":
		return CreateCreditNoteDtoReasonOrderChange, nil
	case "OTHER":
		return CreateCreditNoteDtoReasonOther, nil
	}
	var t CreateCreditNoteDtoReason
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateCreditNoteDtoReason) Ptr() *CreateCreditNoteDtoReason {
	return &c
}

// Override status for imports
type CreateCreditNoteDtoStatus string

const (
	CreateCreditNoteDtoStatusDraft     CreateCreditNoteDtoStatus = "DRAFT"
	CreateCreditNoteDtoStatusFinalized CreateCreditNoteDtoStatus = "FINALIZED"
	CreateCreditNoteDtoStatusVoided    CreateCreditNoteDtoStatus = "VOIDED"
)

func NewCreateCreditNoteDtoStatusFromString(s string) (CreateCreditNoteDtoStatus, error) {
	switch s {
	case "DRAFT":
		return CreateCreditNoteDtoStatusDraft, nil
	case "FINALIZED":
		return CreateCreditNoteDtoStatusFinalized, nil
	case "VOIDED":
		return CreateCreditNoteDtoStatusVoided, nil
	}
	var t CreateCreditNoteDtoStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateCreditNoteDtoStatus) Ptr() *CreateCreditNoteDtoStatus {
	return &c
}

type ListCreditNotesRequestStatus string

const (
	ListCreditNotesRequestStatusDraft     ListCreditNotesRequestStatus = "DRAFT"
	ListCreditNotesRequestStatusFinalized ListCreditNotesRequestStatus = "FINALIZED"
	ListCreditNotesRequestStatusVoided    ListCreditNotesRequestStatus = "VOIDED"
)

func NewListCreditNotesRequestStatusFromString(s string) (ListCreditNotesRequestStatus, error) {
	switch s {
	case "DRAFT":
		return ListCreditNotesRequestStatusDraft, nil
	case "FINALIZED":
		return ListCreditNotesRequestStatusFinalized, nil
	case "VOIDED":
		return ListCreditNotesRequestStatusVoided, nil
	}
	var t ListCreditNotesRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListCreditNotesRequestStatus) Ptr() *ListCreditNotesRequestStatus {
	return &l
}

type UpdateCreditNoteDtoReason string

const (
	UpdateCreditNoteDtoReasonDuplicate             UpdateCreditNoteDtoReason = "DUPLICATE"
	UpdateCreditNoteDtoReasonProductUnsatisfactory UpdateCreditNoteDtoReason = "PRODUCT_UNSATISFACTORY"
	UpdateCreditNoteDtoReasonOrderChange           UpdateCreditNoteDtoReason = "ORDER_CHANGE"
	UpdateCreditNoteDtoReasonOther                 UpdateCreditNoteDtoReason = "OTHER"
)

func NewUpdateCreditNoteDtoReasonFromString(s string) (UpdateCreditNoteDtoReason, error) {
	switch s {
	case "DUPLICATE":
		return UpdateCreditNoteDtoReasonDuplicate, nil
	case "PRODUCT_UNSATISFACTORY":
		return UpdateCreditNoteDtoReasonProductUnsatisfactory, nil
	case "ORDER_CHANGE":
		return UpdateCreditNoteDtoReasonOrderChange, nil
	case "OTHER":
		return UpdateCreditNoteDtoReasonOther, nil
	}
	var t UpdateCreditNoteDtoReason
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateCreditNoteDtoReason) Ptr() *UpdateCreditNoteDtoReason {
	return &u
}

var (
	voidCreditNotesRequestFieldID = big.NewInt(1 << 0)
)

type VoidCreditNotesRequest struct {
	// Credit note ID
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *VoidCreditNotesRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VoidCreditNotesRequest) SetID(id string) {
	v.ID = id
	v.require(voidCreditNotesRequestFieldID)
}
