// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/novabilling/novabilling-go/internal"
	big "math/big"
)

var (
	createInvoiceDtoFieldCustomerID     = big.NewInt(1 << 0)
	createInvoiceDtoFieldSubscriptionID = big.NewInt(1 << 1)
	createInvoiceDtoFieldItems          = big.NewInt(1 << 2)
	createInvoiceDtoFieldDueDate        = big.NewInt(1 << 3)
	createInvoiceDtoFieldStatus         = big.NewInt(1 << 4)
	createInvoiceDtoFieldInvoiceNumber  = big.NewInt(1 << 5)
	createInvoiceDtoFieldCurrency       = big.NewInt(1 << 6)
	createInvoiceDtoFieldPaidAt         = big.NewInt(1 << 7)
	createInvoiceDtoFieldCreatedAt      = big.NewInt(1 << 8)
)

type CreateInvoiceDto struct {
	// Customer ID
	CustomerID string `json:"customerId" url:"-"`
	// Subscription ID (optional)
	SubscriptionID *string           `json:"subscriptionId,omitempty" url:"-"`
	Items          []*InvoiceItemDto `json:"items" url:"-"`
	// Due date
	DueDate string `json:"dueDate" url:"-"`
	// Override invoice status for imports
	Status *CreateInvoiceDtoStatus `json:"status,omitempty" url:"-"`
	// Override invoice number (e.g. INV-00042). Auto-generated if omitted.
	InvoiceNumber *string `json:"invoiceNumber,omitempty" url:"-"`
	// Currency override (defaults to customer currency)
	Currency *string `json:"currency,omitempty" url:"-"`
	// Paid at date (ISO 8601). For importing paid invoices.
	PaidAt *string `json:"paidAt,omitempty" url:"-"`
	// Backdate createdAt (ISO 8601). For data imports.
	CreatedAt *string `json:"createdAt,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateInvoiceDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetCustomerID sets the CustomerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateInvoiceDto) SetCustomerID(customerID string) {
	c.CustomerID = customerID
	c.require(createInvoiceDtoFieldCustomerID)
}

// SetSubscriptionID sets the SubscriptionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateInvoiceDto) SetSubscriptionID(subscriptionID *string) {
	c.SubscriptionID = subscriptionID
	c.require(createInvoiceDtoFieldSubscriptionID)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateInvoiceDto) SetItems(items []*InvoiceItemDto) {
	c.Items = items
	c.require(createInvoiceDtoFieldItems)
}

// SetDueDate sets the DueDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateInvoiceDto) SetDueDate(dueDate string) {
	c.DueDate = dueDate
	c.require(createInvoiceDtoFieldDueDate)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateInvoiceDto) SetStatus(status *CreateInvoiceDtoStatus) {
	c.Status = status
	c.require(createInvoiceDtoFieldStatus)
}

// SetInvoiceNumber sets the InvoiceNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateInvoiceDto) SetInvoiceNumber(invoiceNumber *string) {
	c.InvoiceNumber = invoiceNumber
	c.require(createInvoiceDtoFieldInvoiceNumber)
}

// SetCurrency sets the Currency field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateInvoiceDto) SetCurrency(currency *string) {
	c.Currency = currency
	c.require(createInvoiceDtoFieldCurrency)
}

// SetPaidAt sets the PaidAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateInvoiceDto) SetPaidAt(paidAt *string) {
	c.PaidAt = paidAt
	c.require(createInvoiceDtoFieldPaidAt)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateInvoiceDto) SetCreatedAt(createdAt *string) {
	c.CreatedAt = createdAt
	c.require(createInvoiceDtoFieldCreatedAt)
}

func (c *CreateInvoiceDto) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateInvoiceDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateInvoiceDto(body)
	return nil
}

func (c *CreateInvoiceDto) MarshalJSON() ([]byte, error) {
	type embed CreateInvoiceDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createCheckoutInvoicesRequestFieldID          = big.NewInt(1 << 0)
	createCheckoutInvoicesRequestFieldCallbackURL = big.NewInt(1 << 1)
)

type CreateCheckoutInvoicesRequest struct {
	// Invoice ID
	ID string `json:"-" url:"-"`
	// URL to redirect customer after payment
	CallbackURL *string `json:"callbackUrl,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateCheckoutInvoicesRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCheckoutInvoicesRequest) SetID(id string) {
	c.ID = id
	c.require(createCheckoutInvoicesRequestFieldID)
}

// SetCallbackURL sets the CallbackURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCheckoutInvoicesRequest) SetCallbackURL(callbackURL *string) {
	c.CallbackURL = callbackURL
	c.require(createCheckoutInvoicesRequestFieldCallbackURL)
}

func (c *CreateCheckoutInvoicesRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateCheckoutInvoicesRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateCheckoutInvoicesRequest(body)
	return nil
}

func (c *CreateCheckoutInvoicesRequest) MarshalJSON() ([]byte, error) {
	type embed CreateCheckoutInvoicesRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	finalizeInvoicesRequestFieldID = big.NewInt(1 << 0)
)

type FinalizeInvoicesRequest struct {
	// Invoice ID
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (f *FinalizeInvoicesRequest) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FinalizeInvoicesRequest) SetID(id string) {
	f.ID = id
	f.require(finalizeInvoicesRequestFieldID)
}

var (
	getInvoicesRequestFieldID = big.NewInt(1 << 0)
)

type GetInvoicesRequest struct {
	// Invoice ID
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetInvoicesRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetInvoicesRequest) SetID(id string) {
	g.ID = id
	g.require(getInvoicesRequestFieldID)
}

var (
	getPdfInvoicesRequestFieldID = big.NewInt(1 << 0)
)

type GetPdfInvoicesRequest struct {
	// Invoice ID
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPdfInvoicesRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPdfInvoicesRequest) SetID(id string) {
	g.ID = id
	g.require(getPdfInvoicesRequestFieldID)
}

var (
	listInvoicesRequestFieldStatus     = big.NewInt(1 << 0)
	listInvoicesRequestFieldCustomerID = big.NewInt(1 << 1)
	listInvoicesRequestFieldDateFrom   = big.NewInt(1 << 2)
	listInvoicesRequestFieldDateTo     = big.NewInt(1 << 3)
	listInvoicesRequestFieldPage       = big.NewInt(1 << 4)
	listInvoicesRequestFieldLimit      = big.NewInt(1 << 5)
)

type ListInvoicesRequest struct {
	Status     *string  `json:"-" url:"status,omitempty"`
	CustomerID *string  `json:"-" url:"customerId,omitempty"`
	DateFrom   *string  `json:"-" url:"dateFrom,omitempty"`
	DateTo     *string  `json:"-" url:"dateTo,omitempty"`
	Page       *float64 `json:"-" url:"page,omitempty"`
	Limit      *float64 `json:"-" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListInvoicesRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListInvoicesRequest) SetStatus(status *string) {
	l.Status = status
	l.require(listInvoicesRequestFieldStatus)
}

// SetCustomerID sets the CustomerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListInvoicesRequest) SetCustomerID(customerID *string) {
	l.CustomerID = customerID
	l.require(listInvoicesRequestFieldCustomerID)
}

// SetDateFrom sets the DateFrom field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListInvoicesRequest) SetDateFrom(dateFrom *string) {
	l.DateFrom = dateFrom
	l.require(listInvoicesRequestFieldDateFrom)
}

// SetDateTo sets the DateTo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListInvoicesRequest) SetDateTo(dateTo *string) {
	l.DateTo = dateTo
	l.require(listInvoicesRequestFieldDateTo)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListInvoicesRequest) SetPage(page *float64) {
	l.Page = page
	l.require(listInvoicesRequestFieldPage)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListInvoicesRequest) SetLimit(limit *float64) {
	l.Limit = limit
	l.require(listInvoicesRequestFieldLimit)
}

var (
	markPaidInvoicesRequestFieldID            = big.NewInt(1 << 0)
	markPaidInvoicesRequestFieldPaymentMethod = big.NewInt(1 << 1)
)

type MarkPaidInvoicesRequest struct {
	// Invoice ID
	ID string `json:"-" url:"-"`
	// Payment method used (cash, bank_transfer, check, manual). Defaults to "manual".
	PaymentMethod *string `json:"paymentMethod,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MarkPaidInvoicesRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MarkPaidInvoicesRequest) SetID(id string) {
	m.ID = id
	m.require(markPaidInvoicesRequestFieldID)
}

// SetPaymentMethod sets the PaymentMethod field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MarkPaidInvoicesRequest) SetPaymentMethod(paymentMethod *string) {
	m.PaymentMethod = paymentMethod
	m.require(markPaidInvoicesRequestFieldPaymentMethod)
}

func (m *MarkPaidInvoicesRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler MarkPaidInvoicesRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*m = MarkPaidInvoicesRequest(body)
	return nil
}

func (m *MarkPaidInvoicesRequest) MarshalJSON() ([]byte, error) {
	type embed MarkPaidInvoicesRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	sendEmailInvoicesRequestFieldID    = big.NewInt(1 << 0)
	sendEmailInvoicesRequestFieldEmail = big.NewInt(1 << 1)
)

type SendEmailInvoicesRequest struct {
	// Invoice ID
	ID string `json:"-" url:"-"`
	// Recipient email address. Defaults to the customer email if omitted.
	Email *string `json:"email,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SendEmailInvoicesRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SendEmailInvoicesRequest) SetID(id string) {
	s.ID = id
	s.require(sendEmailInvoicesRequestFieldID)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SendEmailInvoicesRequest) SetEmail(email *string) {
	s.Email = email
	s.require(sendEmailInvoicesRequestFieldEmail)
}

func (s *SendEmailInvoicesRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler SendEmailInvoicesRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*s = SendEmailInvoicesRequest(body)
	return nil
}

func (s *SendEmailInvoicesRequest) MarshalJSON() ([]byte, error) {
	type embed SendEmailInvoicesRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	invoiceItemDtoFieldDescription = big.NewInt(1 << 0)
	invoiceItemDtoFieldQuantity    = big.NewInt(1 << 1)
	invoiceItemDtoFieldUnitAmount  = big.NewInt(1 << 2)
)

type InvoiceItemDto struct {
	Description string  `json:"description" url:"description"`
	Quantity    float64 `json:"quantity" url:"quantity"`
	UnitAmount  float64 `json:"unitAmount" url:"unitAmount"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InvoiceItemDto) GetDescription() string {
	if i == nil {
		return ""
	}
	return i.Description
}

func (i *InvoiceItemDto) GetQuantity() float64 {
	if i == nil {
		return 0
	}
	return i.Quantity
}

func (i *InvoiceItemDto) GetUnitAmount() float64 {
	if i == nil {
		return 0
	}
	return i.UnitAmount
}

func (i *InvoiceItemDto) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *InvoiceItemDto) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvoiceItemDto) SetDescription(description string) {
	i.Description = description
	i.require(invoiceItemDtoFieldDescription)
}

// SetQuantity sets the Quantity field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvoiceItemDto) SetQuantity(quantity float64) {
	i.Quantity = quantity
	i.require(invoiceItemDtoFieldQuantity)
}

// SetUnitAmount sets the UnitAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvoiceItemDto) SetUnitAmount(unitAmount float64) {
	i.UnitAmount = unitAmount
	i.require(invoiceItemDtoFieldUnitAmount)
}

func (i *InvoiceItemDto) UnmarshalJSON(data []byte) error {
	type unmarshaler InvoiceItemDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InvoiceItemDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InvoiceItemDto) MarshalJSON() ([]byte, error) {
	type embed InvoiceItemDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InvoiceItemDto) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// Override invoice status for imports
type CreateInvoiceDtoStatus string

const (
	CreateInvoiceDtoStatusDraft    CreateInvoiceDtoStatus = "DRAFT"
	CreateInvoiceDtoStatusPending  CreateInvoiceDtoStatus = "PENDING"
	CreateInvoiceDtoStatusPaid     CreateInvoiceDtoStatus = "PAID"
	CreateInvoiceDtoStatusFailed   CreateInvoiceDtoStatus = "FAILED"
	CreateInvoiceDtoStatusCanceled CreateInvoiceDtoStatus = "CANCELED"
)

func NewCreateInvoiceDtoStatusFromString(s string) (CreateInvoiceDtoStatus, error) {
	switch s {
	case "DRAFT":
		return CreateInvoiceDtoStatusDraft, nil
	case "PENDING":
		return CreateInvoiceDtoStatusPending, nil
	case "PAID":
		return CreateInvoiceDtoStatusPaid, nil
	case "FAILED":
		return CreateInvoiceDtoStatusFailed, nil
	case "CANCELED":
		return CreateInvoiceDtoStatusCanceled, nil
	}
	var t CreateInvoiceDtoStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateInvoiceDtoStatus) Ptr() *CreateInvoiceDtoStatus {
	return &c
}

var (
	voidInvoicesRequestFieldID = big.NewInt(1 << 0)
)

type VoidInvoicesRequest struct {
	// Invoice ID
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *VoidInvoicesRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VoidInvoicesRequest) SetID(id string) {
	v.ID = id
	v.require(voidInvoicesRequestFieldID)
}
