// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/novabilling/novabilling-go/internal"
	big "math/big"
)

var (
	taxesControllerGetCustomerTaxesRequestFieldCustomerID = big.NewInt(1 << 0)
)

type TaxesControllerGetCustomerTaxesRequest struct {
	// Customer ID
	CustomerID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (t *TaxesControllerGetCustomerTaxesRequest) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetCustomerID sets the CustomerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaxesControllerGetCustomerTaxesRequest) SetCustomerID(customerID string) {
	t.CustomerID = customerID
	t.require(taxesControllerGetCustomerTaxesRequestFieldCustomerID)
}

var (
	taxesControllerGetPlanTaxesRequestFieldPlanID = big.NewInt(1 << 0)
)

type TaxesControllerGetPlanTaxesRequest struct {
	// Plan ID
	PlanID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (t *TaxesControllerGetPlanTaxesRequest) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetPlanID sets the PlanID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaxesControllerGetPlanTaxesRequest) SetPlanID(planID string) {
	t.PlanID = planID
	t.require(taxesControllerGetPlanTaxesRequestFieldPlanID)
}

var (
	assignToChargeTaxesRequestFieldChargeID = big.NewInt(1 << 0)
)

type AssignToChargeTaxesRequest struct {
	// Charge ID
	ChargeID string        `json:"-" url:"-"`
	Body     *AssignTaxDto `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AssignToChargeTaxesRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetChargeID sets the ChargeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AssignToChargeTaxesRequest) SetChargeID(chargeID string) {
	a.ChargeID = chargeID
	a.require(assignToChargeTaxesRequestFieldChargeID)
}

func (a *AssignToChargeTaxesRequest) UnmarshalJSON(data []byte) error {
	body := new(AssignTaxDto)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	a.Body = body
	return nil
}

func (a *AssignToChargeTaxesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(a.Body)
}

var (
	assignToCustomerTaxesRequestFieldCustomerID = big.NewInt(1 << 0)
)

type AssignToCustomerTaxesRequest struct {
	// Customer ID
	CustomerID string        `json:"-" url:"-"`
	Body       *AssignTaxDto `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AssignToCustomerTaxesRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetCustomerID sets the CustomerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AssignToCustomerTaxesRequest) SetCustomerID(customerID string) {
	a.CustomerID = customerID
	a.require(assignToCustomerTaxesRequestFieldCustomerID)
}

func (a *AssignToCustomerTaxesRequest) UnmarshalJSON(data []byte) error {
	body := new(AssignTaxDto)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	a.Body = body
	return nil
}

func (a *AssignToCustomerTaxesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(a.Body)
}

var (
	assignToPlanTaxesRequestFieldPlanID = big.NewInt(1 << 0)
)

type AssignToPlanTaxesRequest struct {
	// Plan ID
	PlanID string        `json:"-" url:"-"`
	Body   *AssignTaxDto `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AssignToPlanTaxesRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetPlanID sets the PlanID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AssignToPlanTaxesRequest) SetPlanID(planID string) {
	a.PlanID = planID
	a.require(assignToPlanTaxesRequestFieldPlanID)
}

func (a *AssignToPlanTaxesRequest) UnmarshalJSON(data []byte) error {
	body := new(AssignTaxDto)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	a.Body = body
	return nil
}

func (a *AssignToPlanTaxesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(a.Body)
}

var (
	createTaxDtoFieldName             = big.NewInt(1 << 0)
	createTaxDtoFieldCode             = big.NewInt(1 << 1)
	createTaxDtoFieldRate             = big.NewInt(1 << 2)
	createTaxDtoFieldDescription      = big.NewInt(1 << 3)
	createTaxDtoFieldAppliedByDefault = big.NewInt(1 << 4)
)

type CreateTaxDto struct {
	// Tax name
	Name string `json:"name" url:"-"`
	// Unique tax code (lowercase, underscores)
	Code string `json:"code" url:"-"`
	// Tax rate as a percentage (e.g., 18 for 18%)
	Rate float64 `json:"rate" url:"-"`
	// Tax description
	Description *string `json:"description,omitempty" url:"-"`
	// Whether this tax is applied by default to all invoices
	AppliedByDefault *bool `json:"appliedByDefault,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateTaxDto) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTaxDto) SetName(name string) {
	c.Name = name
	c.require(createTaxDtoFieldName)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTaxDto) SetCode(code string) {
	c.Code = code
	c.require(createTaxDtoFieldCode)
}

// SetRate sets the Rate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTaxDto) SetRate(rate float64) {
	c.Rate = rate
	c.require(createTaxDtoFieldRate)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTaxDto) SetDescription(description *string) {
	c.Description = description
	c.require(createTaxDtoFieldDescription)
}

// SetAppliedByDefault sets the AppliedByDefault field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTaxDto) SetAppliedByDefault(appliedByDefault *bool) {
	c.AppliedByDefault = appliedByDefault
	c.require(createTaxDtoFieldAppliedByDefault)
}

func (c *CreateTaxDto) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateTaxDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateTaxDto(body)
	return nil
}

func (c *CreateTaxDto) MarshalJSON() ([]byte, error) {
	type embed CreateTaxDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteTaxesRequestFieldID = big.NewInt(1 << 0)
)

type DeleteTaxesRequest struct {
	// Tax ID
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteTaxesRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteTaxesRequest) SetID(id string) {
	d.ID = id
	d.require(deleteTaxesRequestFieldID)
}

var (
	getTaxesRequestFieldID = big.NewInt(1 << 0)
)

type GetTaxesRequest struct {
	// Tax ID
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetTaxesRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTaxesRequest) SetID(id string) {
	g.ID = id
	g.require(getTaxesRequestFieldID)
}

var (
	listTaxesRequestFieldAppliedByDefault = big.NewInt(1 << 0)
	listTaxesRequestFieldPage             = big.NewInt(1 << 1)
	listTaxesRequestFieldLimit            = big.NewInt(1 << 2)
)

type ListTaxesRequest struct {
	AppliedByDefault *bool    `json:"-" url:"appliedByDefault,omitempty"`
	Page             *float64 `json:"-" url:"page,omitempty"`
	Limit            *float64 `json:"-" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListTaxesRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetAppliedByDefault sets the AppliedByDefault field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTaxesRequest) SetAppliedByDefault(appliedByDefault *bool) {
	l.AppliedByDefault = appliedByDefault
	l.require(listTaxesRequestFieldAppliedByDefault)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTaxesRequest) SetPage(page *float64) {
	l.Page = page
	l.require(listTaxesRequestFieldPage)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTaxesRequest) SetLimit(limit *float64) {
	l.Limit = limit
	l.require(listTaxesRequestFieldLimit)
}

var (
	removeFromChargeTaxesRequestFieldChargeID = big.NewInt(1 << 0)
	removeFromChargeTaxesRequestFieldTaxID    = big.NewInt(1 << 1)
)

type RemoveFromChargeTaxesRequest struct {
	// Charge ID
	ChargeID string `json:"-" url:"-"`
	// Tax ID
	TaxID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RemoveFromChargeTaxesRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetChargeID sets the ChargeID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoveFromChargeTaxesRequest) SetChargeID(chargeID string) {
	r.ChargeID = chargeID
	r.require(removeFromChargeTaxesRequestFieldChargeID)
}

// SetTaxID sets the TaxID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoveFromChargeTaxesRequest) SetTaxID(taxID string) {
	r.TaxID = taxID
	r.require(removeFromChargeTaxesRequestFieldTaxID)
}

var (
	removeFromCustomerTaxesRequestFieldCustomerID = big.NewInt(1 << 0)
	removeFromCustomerTaxesRequestFieldTaxID      = big.NewInt(1 << 1)
)

type RemoveFromCustomerTaxesRequest struct {
	// Customer ID
	CustomerID string `json:"-" url:"-"`
	// Tax ID
	TaxID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RemoveFromCustomerTaxesRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetCustomerID sets the CustomerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoveFromCustomerTaxesRequest) SetCustomerID(customerID string) {
	r.CustomerID = customerID
	r.require(removeFromCustomerTaxesRequestFieldCustomerID)
}

// SetTaxID sets the TaxID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoveFromCustomerTaxesRequest) SetTaxID(taxID string) {
	r.TaxID = taxID
	r.require(removeFromCustomerTaxesRequestFieldTaxID)
}

var (
	removeFromPlanTaxesRequestFieldPlanID = big.NewInt(1 << 0)
	removeFromPlanTaxesRequestFieldTaxID  = big.NewInt(1 << 1)
)

type RemoveFromPlanTaxesRequest struct {
	// Plan ID
	PlanID string `json:"-" url:"-"`
	// Tax ID
	TaxID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RemoveFromPlanTaxesRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetPlanID sets the PlanID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoveFromPlanTaxesRequest) SetPlanID(planID string) {
	r.PlanID = planID
	r.require(removeFromPlanTaxesRequestFieldPlanID)
}

// SetTaxID sets the TaxID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoveFromPlanTaxesRequest) SetTaxID(taxID string) {
	r.TaxID = taxID
	r.require(removeFromPlanTaxesRequestFieldTaxID)
}

var (
	assignTaxDtoFieldTaxID = big.NewInt(1 << 0)
)

type AssignTaxDto struct {
	// Tax ID to assign
	TaxID string `json:"taxId" url:"taxId"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AssignTaxDto) GetTaxID() string {
	if a == nil {
		return ""
	}
	return a.TaxID
}

func (a *AssignTaxDto) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AssignTaxDto) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetTaxID sets the TaxID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AssignTaxDto) SetTaxID(taxID string) {
	a.TaxID = taxID
	a.require(assignTaxDtoFieldTaxID)
}

func (a *AssignTaxDto) UnmarshalJSON(data []byte) error {
	type unmarshaler AssignTaxDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AssignTaxDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AssignTaxDto) MarshalJSON() ([]byte, error) {
	type embed AssignTaxDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AssignTaxDto) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	paginatedTaxResponseFieldData = big.NewInt(1 << 0)
	paginatedTaxResponseFieldMeta = big.NewInt(1 << 1)
)

type PaginatedTaxResponse struct {
	Data []*TaxResponse  `json:"data" url:"data"`
	Meta *PaginationMeta `json:"meta" url:"meta"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PaginatedTaxResponse) GetData() []*TaxResponse {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PaginatedTaxResponse) GetMeta() *PaginationMeta {
	if p == nil {
		return nil
	}
	return p.Meta
}

func (p *PaginatedTaxResponse) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PaginatedTaxResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedTaxResponse) SetData(data []*TaxResponse) {
	p.Data = data
	p.require(paginatedTaxResponseFieldData)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedTaxResponse) SetMeta(meta *PaginationMeta) {
	p.Meta = meta
	p.require(paginatedTaxResponseFieldMeta)
}

func (p *PaginatedTaxResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PaginatedTaxResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaginatedTaxResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaginatedTaxResponse) MarshalJSON() ([]byte, error) {
	type embed PaginatedTaxResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PaginatedTaxResponse) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	taxResponseFieldID               = big.NewInt(1 << 0)
	taxResponseFieldName             = big.NewInt(1 << 1)
	taxResponseFieldCode             = big.NewInt(1 << 2)
	taxResponseFieldRate             = big.NewInt(1 << 3)
	taxResponseFieldDescription      = big.NewInt(1 << 4)
	taxResponseFieldAppliedByDefault = big.NewInt(1 << 5)
	taxResponseFieldCreatedAt        = big.NewInt(1 << 6)
	taxResponseFieldUpdatedAt        = big.NewInt(1 << 7)
)

type TaxResponse struct {
	ID               string  `json:"id" url:"id"`
	Name             string  `json:"name" url:"name"`
	Code             string  `json:"code" url:"code"`
	Rate             string  `json:"rate" url:"rate"`
	Description      *string `json:"description,omitempty" url:"description,omitempty"`
	AppliedByDefault bool    `json:"appliedByDefault" url:"appliedByDefault"`
	CreatedAt        string  `json:"createdAt" url:"createdAt"`
	UpdatedAt        string  `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TaxResponse) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TaxResponse) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *TaxResponse) GetCode() string {
	if t == nil {
		return ""
	}
	return t.Code
}

func (t *TaxResponse) GetRate() string {
	if t == nil {
		return ""
	}
	return t.Rate
}

func (t *TaxResponse) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *TaxResponse) GetAppliedByDefault() bool {
	if t == nil {
		return false
	}
	return t.AppliedByDefault
}

func (t *TaxResponse) GetCreatedAt() string {
	if t == nil {
		return ""
	}
	return t.CreatedAt
}

func (t *TaxResponse) GetUpdatedAt() string {
	if t == nil {
		return ""
	}
	return t.UpdatedAt
}

func (t *TaxResponse) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TaxResponse) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaxResponse) SetID(id string) {
	t.ID = id
	t.require(taxResponseFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaxResponse) SetName(name string) {
	t.Name = name
	t.require(taxResponseFieldName)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaxResponse) SetCode(code string) {
	t.Code = code
	t.require(taxResponseFieldCode)
}

// SetRate sets the Rate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaxResponse) SetRate(rate string) {
	t.Rate = rate
	t.require(taxResponseFieldRate)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaxResponse) SetDescription(description *string) {
	t.Description = description
	t.require(taxResponseFieldDescription)
}

// SetAppliedByDefault sets the AppliedByDefault field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaxResponse) SetAppliedByDefault(appliedByDefault bool) {
	t.AppliedByDefault = appliedByDefault
	t.require(taxResponseFieldAppliedByDefault)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaxResponse) SetCreatedAt(createdAt string) {
	t.CreatedAt = createdAt
	t.require(taxResponseFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TaxResponse) SetUpdatedAt(updatedAt string) {
	t.UpdatedAt = updatedAt
	t.require(taxResponseFieldUpdatedAt)
}

func (t *TaxResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler TaxResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TaxResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TaxResponse) MarshalJSON() ([]byte, error) {
	type embed TaxResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TaxResponse) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	updateTaxDtoFieldID               = big.NewInt(1 << 0)
	updateTaxDtoFieldName             = big.NewInt(1 << 1)
	updateTaxDtoFieldRate             = big.NewInt(1 << 2)
	updateTaxDtoFieldDescription      = big.NewInt(1 << 3)
	updateTaxDtoFieldAppliedByDefault = big.NewInt(1 << 4)
)

type UpdateTaxDto struct {
	// Tax ID
	ID               string   `json:"-" url:"-"`
	Name             *string  `json:"name,omitempty" url:"-"`
	Rate             *float64 `json:"rate,omitempty" url:"-"`
	Description      *string  `json:"description,omitempty" url:"-"`
	AppliedByDefault *bool    `json:"appliedByDefault,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateTaxDto) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTaxDto) SetID(id string) {
	u.ID = id
	u.require(updateTaxDtoFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTaxDto) SetName(name *string) {
	u.Name = name
	u.require(updateTaxDtoFieldName)
}

// SetRate sets the Rate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTaxDto) SetRate(rate *float64) {
	u.Rate = rate
	u.require(updateTaxDtoFieldRate)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTaxDto) SetDescription(description *string) {
	u.Description = description
	u.require(updateTaxDtoFieldDescription)
}

// SetAppliedByDefault sets the AppliedByDefault field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateTaxDto) SetAppliedByDefault(appliedByDefault *bool) {
	u.AppliedByDefault = appliedByDefault
	u.require(updateTaxDtoFieldAppliedByDefault)
}

func (u *UpdateTaxDto) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateTaxDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateTaxDto(body)
	return nil
}

func (u *UpdateTaxDto) MarshalJSON() ([]byte, error) {
	type embed UpdateTaxDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
