// Code generated by Fern. DO NOT EDIT.

package addons

import (
	context "context"
	novabillinggo "github.com/novabilling/novabilling-go"
	core "github.com/novabilling/novabilling-go/core"
	internal "github.com/novabilling/novabilling-go/internal"
	option "github.com/novabilling/novabilling-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Retrieve a paginated list of add-ons with prices.
func (c *Client) List(
	ctx context.Context,
	request *novabillinggo.ListAddOnsRequest,
	opts ...option.RequestOption,
) (*novabillinggo.PaginatedAddOnResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a one-time charge add-on with multi-currency pricing.
func (c *Client) Create(
	ctx context.Context,
	request *novabillinggo.CreateAddOnDto,
	opts ...option.RequestOption,
) (*novabillinggo.AddOnResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Get(
	ctx context.Context,
	request *novabillinggo.GetAddOnsRequest,
	opts ...option.RequestOption,
) (*novabillinggo.AddOnResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Delete(
	ctx context.Context,
	request *novabillinggo.DeleteAddOnsRequest,
	opts ...option.RequestOption,
) (*novabillinggo.AddOnResponse, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Update(
	ctx context.Context,
	request *novabillinggo.UpdateAddOnDto,
	opts ...option.RequestOption,
) (*novabillinggo.AddOnResponse, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a one-time charge for a customer. Will be included in the next invoice.
func (c *Client) Apply(
	ctx context.Context,
	request *novabillinggo.ApplyAddOnDto,
	opts ...option.RequestOption,
) (*novabillinggo.AppliedAddOnResponse, error) {
	response, err := c.WithRawResponse.Apply(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// View one-time charges applied to customers.
func (c *Client) ListApplied(
	ctx context.Context,
	request *novabillinggo.ListAppliedAddOnsRequest,
	opts ...option.RequestOption,
) ([]*novabillinggo.AppliedAddOnResponse, error) {
	response, err := c.WithRawResponse.ListApplied(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Remove a one-time charge that has not yet been invoiced.
func (c *Client) RemoveApplied(
	ctx context.Context,
	request *novabillinggo.RemoveAppliedAddOnsRequest,
	opts ...option.RequestOption,
) (*novabillinggo.AppliedAddOnResponse, error) {
	response, err := c.WithRawResponse.RemoveApplied(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
