/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = AppliedAddOnResponse.Builder.class
)
public final class AppliedAddOnResponse {
  private final String id;

  private final String addOnId;

  private final String customerId;

  private final Optional<String> subscriptionId;

  private final String amount;

  private final String currency;

  private final Optional<String> invoiceId;

  private final String createdAt;

  private final Map<String, Object> additionalProperties;

  private AppliedAddOnResponse(String id, String addOnId, String customerId,
      Optional<String> subscriptionId, String amount, String currency, Optional<String> invoiceId,
      String createdAt, Map<String, Object> additionalProperties) {
    this.id = id;
    this.addOnId = addOnId;
    this.customerId = customerId;
    this.subscriptionId = subscriptionId;
    this.amount = amount;
    this.currency = currency;
    this.invoiceId = invoiceId;
    this.createdAt = createdAt;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("addOnId")
  public String getAddOnId() {
    return addOnId;
  }

  @JsonProperty("customerId")
  public String getCustomerId() {
    return customerId;
  }

  @JsonProperty("subscriptionId")
  public Optional<String> getSubscriptionId() {
    return subscriptionId;
  }

  @JsonProperty("amount")
  public String getAmount() {
    return amount;
  }

  @JsonProperty("currency")
  public String getCurrency() {
    return currency;
  }

  @JsonProperty("invoiceId")
  public Optional<String> getInvoiceId() {
    return invoiceId;
  }

  @JsonProperty("createdAt")
  public String getCreatedAt() {
    return createdAt;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AppliedAddOnResponse && equalTo((AppliedAddOnResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(AppliedAddOnResponse other) {
    return id.equals(other.id) && addOnId.equals(other.addOnId) && customerId.equals(other.customerId) && subscriptionId.equals(other.subscriptionId) && amount.equals(other.amount) && currency.equals(other.currency) && invoiceId.equals(other.invoiceId) && createdAt.equals(other.createdAt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.addOnId, this.customerId, this.subscriptionId, this.amount, this.currency, this.invoiceId, this.createdAt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    AddOnIdStage id(@NotNull String id);

    Builder from(AppliedAddOnResponse other);
  }

  public interface AddOnIdStage {
    CustomerIdStage addOnId(@NotNull String addOnId);
  }

  public interface CustomerIdStage {
    AmountStage customerId(@NotNull String customerId);
  }

  public interface AmountStage {
    CurrencyStage amount(@NotNull String amount);
  }

  public interface CurrencyStage {
    CreatedAtStage currency(@NotNull String currency);
  }

  public interface CreatedAtStage {
    _FinalStage createdAt(@NotNull String createdAt);
  }

  public interface _FinalStage {
    AppliedAddOnResponse build();

    _FinalStage subscriptionId(Optional<String> subscriptionId);

    _FinalStage subscriptionId(String subscriptionId);

    _FinalStage invoiceId(Optional<String> invoiceId);

    _FinalStage invoiceId(String invoiceId);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, AddOnIdStage, CustomerIdStage, AmountStage, CurrencyStage, CreatedAtStage, _FinalStage {
    private String id;

    private String addOnId;

    private String customerId;

    private String amount;

    private String currency;

    private String createdAt;

    private Optional<String> invoiceId = Optional.empty();

    private Optional<String> subscriptionId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(AppliedAddOnResponse other) {
      id(other.getId());
      addOnId(other.getAddOnId());
      customerId(other.getCustomerId());
      subscriptionId(other.getSubscriptionId());
      amount(other.getAmount());
      currency(other.getCurrency());
      invoiceId(other.getInvoiceId());
      createdAt(other.getCreatedAt());
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public AddOnIdStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("addOnId")
    public CustomerIdStage addOnId(@NotNull String addOnId) {
      this.addOnId = Objects.requireNonNull(addOnId, "addOnId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("customerId")
    public AmountStage customerId(@NotNull String customerId) {
      this.customerId = Objects.requireNonNull(customerId, "customerId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("amount")
    public CurrencyStage amount(@NotNull String amount) {
      this.amount = Objects.requireNonNull(amount, "amount must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("currency")
    public CreatedAtStage currency(@NotNull String currency) {
      this.currency = Objects.requireNonNull(currency, "currency must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("createdAt")
    public _FinalStage createdAt(@NotNull String createdAt) {
      this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage invoiceId(String invoiceId) {
      this.invoiceId = Optional.ofNullable(invoiceId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "invoiceId",
        nulls = Nulls.SKIP
    )
    public _FinalStage invoiceId(Optional<String> invoiceId) {
      this.invoiceId = invoiceId;
      return this;
    }

    @java.lang.Override
    public _FinalStage subscriptionId(String subscriptionId) {
      this.subscriptionId = Optional.ofNullable(subscriptionId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "subscriptionId",
        nulls = Nulls.SKIP
    )
    public _FinalStage subscriptionId(Optional<String> subscriptionId) {
      this.subscriptionId = subscriptionId;
      return this;
    }

    @java.lang.Override
    public AppliedAddOnResponse build() {
      return new AppliedAddOnResponse(id, addOnId, customerId, subscriptionId, amount, currency, invoiceId, createdAt, additionalProperties);
    }
  }
}
