/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = AssignTaxDto.Builder.class
)
public final class AssignTaxDto {
  private final String taxId;

  private final Map<String, Object> additionalProperties;

  private AssignTaxDto(String taxId, Map<String, Object> additionalProperties) {
    this.taxId = taxId;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Tax ID to assign
   */
  @JsonProperty("taxId")
  public String getTaxId() {
    return taxId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AssignTaxDto && equalTo((AssignTaxDto) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(AssignTaxDto other) {
    return taxId.equals(other.taxId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.taxId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TaxIdStage builder() {
    return new Builder();
  }

  public interface TaxIdStage {
    /**
     * <p>Tax ID to assign</p>
     */
    _FinalStage taxId(@NotNull String taxId);

    Builder from(AssignTaxDto other);
  }

  public interface _FinalStage {
    AssignTaxDto build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TaxIdStage, _FinalStage {
    private String taxId;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(AssignTaxDto other) {
      taxId(other.getTaxId());
      return this;
    }

    /**
     * <p>Tax ID to assign</p>
     * <p>Tax ID to assign</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("taxId")
    public _FinalStage taxId(@NotNull String taxId) {
      this.taxId = Objects.requireNonNull(taxId, "taxId must not be null");
      return this;
    }

    @java.lang.Override
    public AssignTaxDto build() {
      return new AssignTaxDto(taxId, additionalProperties);
    }
  }
}
