/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GraduatedRangeDto.Builder.class
)
public final class GraduatedRangeDto {
  private final double fromValue;

  private final Optional<Double> toValue;

  private final double perUnitAmount;

  private final Optional<Double> flatAmount;

  private final Map<String, Object> additionalProperties;

  private GraduatedRangeDto(double fromValue, Optional<Double> toValue, double perUnitAmount,
      Optional<Double> flatAmount, Map<String, Object> additionalProperties) {
    this.fromValue = fromValue;
    this.toValue = toValue;
    this.perUnitAmount = perUnitAmount;
    this.flatAmount = flatAmount;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Start of range (inclusive)
   */
  @JsonProperty("fromValue")
  public double getFromValue() {
    return fromValue;
  }

  /**
   * @return End of range (inclusive), null = infinity
   */
  @JsonProperty("toValue")
  public Optional<Double> getToValue() {
    return toValue;
  }

  /**
   * @return Price per unit in this range
   */
  @JsonProperty("perUnitAmount")
  public double getPerUnitAmount() {
    return perUnitAmount;
  }

  /**
   * @return Flat fee for entering this range
   */
  @JsonProperty("flatAmount")
  public Optional<Double> getFlatAmount() {
    return flatAmount;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GraduatedRangeDto && equalTo((GraduatedRangeDto) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GraduatedRangeDto other) {
    return fromValue == other.fromValue && toValue.equals(other.toValue) && perUnitAmount == other.perUnitAmount && flatAmount.equals(other.flatAmount);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.fromValue, this.toValue, this.perUnitAmount, this.flatAmount);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static FromValueStage builder() {
    return new Builder();
  }

  public interface FromValueStage {
    /**
     * <p>Start of range (inclusive)</p>
     */
    PerUnitAmountStage fromValue(double fromValue);

    Builder from(GraduatedRangeDto other);
  }

  public interface PerUnitAmountStage {
    /**
     * <p>Price per unit in this range</p>
     */
    _FinalStage perUnitAmount(double perUnitAmount);
  }

  public interface _FinalStage {
    GraduatedRangeDto build();

    /**
     * <p>End of range (inclusive), null = infinity</p>
     */
    _FinalStage toValue(Optional<Double> toValue);

    _FinalStage toValue(Double toValue);

    /**
     * <p>Flat fee for entering this range</p>
     */
    _FinalStage flatAmount(Optional<Double> flatAmount);

    _FinalStage flatAmount(Double flatAmount);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements FromValueStage, PerUnitAmountStage, _FinalStage {
    private double fromValue;

    private double perUnitAmount;

    private Optional<Double> flatAmount = Optional.empty();

    private Optional<Double> toValue = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(GraduatedRangeDto other) {
      fromValue(other.getFromValue());
      toValue(other.getToValue());
      perUnitAmount(other.getPerUnitAmount());
      flatAmount(other.getFlatAmount());
      return this;
    }

    /**
     * <p>Start of range (inclusive)</p>
     * <p>Start of range (inclusive)</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("fromValue")
    public PerUnitAmountStage fromValue(double fromValue) {
      this.fromValue = fromValue;
      return this;
    }

    /**
     * <p>Price per unit in this range</p>
     * <p>Price per unit in this range</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("perUnitAmount")
    public _FinalStage perUnitAmount(double perUnitAmount) {
      this.perUnitAmount = perUnitAmount;
      return this;
    }

    /**
     * <p>Flat fee for entering this range</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage flatAmount(Double flatAmount) {
      this.flatAmount = Optional.ofNullable(flatAmount);
      return this;
    }

    /**
     * <p>Flat fee for entering this range</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "flatAmount",
        nulls = Nulls.SKIP
    )
    public _FinalStage flatAmount(Optional<Double> flatAmount) {
      this.flatAmount = flatAmount;
      return this;
    }

    /**
     * <p>End of range (inclusive), null = infinity</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage toValue(Double toValue) {
      this.toValue = Optional.ofNullable(toValue);
      return this;
    }

    /**
     * <p>End of range (inclusive), null = infinity</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "toValue",
        nulls = Nulls.SKIP
    )
    public _FinalStage toValue(Optional<Double> toValue) {
      this.toValue = toValue;
      return this;
    }

    @java.lang.Override
    public GraduatedRangeDto build() {
      return new GraduatedRangeDto(fromValue, toValue, perUnitAmount, flatAmount, additionalProperties);
    }
  }
}
