/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PaymentAnalyticsResponse.Builder.class
)
public final class PaymentAnalyticsResponse {
  private final double totalPayments;

  private final double succeeded;

  private final double failed;

  private final double pending;

  private final String successRate;

  private final Map<String, Object> additionalProperties;

  private PaymentAnalyticsResponse(double totalPayments, double succeeded, double failed,
      double pending, String successRate, Map<String, Object> additionalProperties) {
    this.totalPayments = totalPayments;
    this.succeeded = succeeded;
    this.failed = failed;
    this.pending = pending;
    this.successRate = successRate;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("totalPayments")
  public double getTotalPayments() {
    return totalPayments;
  }

  @JsonProperty("succeeded")
  public double getSucceeded() {
    return succeeded;
  }

  @JsonProperty("failed")
  public double getFailed() {
    return failed;
  }

  @JsonProperty("pending")
  public double getPending() {
    return pending;
  }

  /**
   * @return Success rate percentage
   */
  @JsonProperty("successRate")
  public String getSuccessRate() {
    return successRate;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PaymentAnalyticsResponse && equalTo((PaymentAnalyticsResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PaymentAnalyticsResponse other) {
    return totalPayments == other.totalPayments && succeeded == other.succeeded && failed == other.failed && pending == other.pending && successRate.equals(other.successRate);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.totalPayments, this.succeeded, this.failed, this.pending, this.successRate);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TotalPaymentsStage builder() {
    return new Builder();
  }

  public interface TotalPaymentsStage {
    SucceededStage totalPayments(double totalPayments);

    Builder from(PaymentAnalyticsResponse other);
  }

  public interface SucceededStage {
    FailedStage succeeded(double succeeded);
  }

  public interface FailedStage {
    PendingStage failed(double failed);
  }

  public interface PendingStage {
    SuccessRateStage pending(double pending);
  }

  public interface SuccessRateStage {
    /**
     * <p>Success rate percentage</p>
     */
    _FinalStage successRate(@NotNull String successRate);
  }

  public interface _FinalStage {
    PaymentAnalyticsResponse build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TotalPaymentsStage, SucceededStage, FailedStage, PendingStage, SuccessRateStage, _FinalStage {
    private double totalPayments;

    private double succeeded;

    private double failed;

    private double pending;

    private String successRate;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PaymentAnalyticsResponse other) {
      totalPayments(other.getTotalPayments());
      succeeded(other.getSucceeded());
      failed(other.getFailed());
      pending(other.getPending());
      successRate(other.getSuccessRate());
      return this;
    }

    @java.lang.Override
    @JsonSetter("totalPayments")
    public SucceededStage totalPayments(double totalPayments) {
      this.totalPayments = totalPayments;
      return this;
    }

    @java.lang.Override
    @JsonSetter("succeeded")
    public FailedStage succeeded(double succeeded) {
      this.succeeded = succeeded;
      return this;
    }

    @java.lang.Override
    @JsonSetter("failed")
    public PendingStage failed(double failed) {
      this.failed = failed;
      return this;
    }

    @java.lang.Override
    @JsonSetter("pending")
    public SuccessRateStage pending(double pending) {
      this.pending = pending;
      return this;
    }

    /**
     * <p>Success rate percentage</p>
     * <p>Success rate percentage</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("successRate")
    public _FinalStage successRate(@NotNull String successRate) {
      this.successRate = Objects.requireNonNull(successRate, "successRate must not be null");
      return this;
    }

    @java.lang.Override
    public PaymentAnalyticsResponse build() {
      return new PaymentAnalyticsResponse(totalPayments, succeeded, failed, pending, successRate, additionalProperties);
    }
  }
}
