/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PaymentProviderResponse.Builder.class
)
public final class PaymentProviderResponse {
  private final String id;

  private final String providerName;

  private final boolean isActive;

  private final double priority;

  private final String createdAt;

  private final String updatedAt;

  private final Map<String, Object> additionalProperties;

  private PaymentProviderResponse(String id, String providerName, boolean isActive, double priority,
      String createdAt, String updatedAt, Map<String, Object> additionalProperties) {
    this.id = id;
    this.providerName = providerName;
    this.isActive = isActive;
    this.priority = priority;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("providerName")
  public String getProviderName() {
    return providerName;
  }

  @JsonProperty("isActive")
  public boolean getIsActive() {
    return isActive;
  }

  @JsonProperty("priority")
  public double getPriority() {
    return priority;
  }

  @JsonProperty("createdAt")
  public String getCreatedAt() {
    return createdAt;
  }

  @JsonProperty("updatedAt")
  public String getUpdatedAt() {
    return updatedAt;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PaymentProviderResponse && equalTo((PaymentProviderResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PaymentProviderResponse other) {
    return id.equals(other.id) && providerName.equals(other.providerName) && isActive == other.isActive && priority == other.priority && createdAt.equals(other.createdAt) && updatedAt.equals(other.updatedAt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.providerName, this.isActive, this.priority, this.createdAt, this.updatedAt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    ProviderNameStage id(@NotNull String id);

    Builder from(PaymentProviderResponse other);
  }

  public interface ProviderNameStage {
    IsActiveStage providerName(@NotNull String providerName);
  }

  public interface IsActiveStage {
    PriorityStage isActive(boolean isActive);
  }

  public interface PriorityStage {
    CreatedAtStage priority(double priority);
  }

  public interface CreatedAtStage {
    UpdatedAtStage createdAt(@NotNull String createdAt);
  }

  public interface UpdatedAtStage {
    _FinalStage updatedAt(@NotNull String updatedAt);
  }

  public interface _FinalStage {
    PaymentProviderResponse build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, ProviderNameStage, IsActiveStage, PriorityStage, CreatedAtStage, UpdatedAtStage, _FinalStage {
    private String id;

    private String providerName;

    private boolean isActive;

    private double priority;

    private String createdAt;

    private String updatedAt;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PaymentProviderResponse other) {
      id(other.getId());
      providerName(other.getProviderName());
      isActive(other.getIsActive());
      priority(other.getPriority());
      createdAt(other.getCreatedAt());
      updatedAt(other.getUpdatedAt());
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public ProviderNameStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("providerName")
    public IsActiveStage providerName(@NotNull String providerName) {
      this.providerName = Objects.requireNonNull(providerName, "providerName must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("isActive")
    public PriorityStage isActive(boolean isActive) {
      this.isActive = isActive;
      return this;
    }

    @java.lang.Override
    @JsonSetter("priority")
    public CreatedAtStage priority(double priority) {
      this.priority = priority;
      return this;
    }

    @java.lang.Override
    @JsonSetter("createdAt")
    public UpdatedAtStage createdAt(@NotNull String createdAt) {
      this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("updatedAt")
    public _FinalStage updatedAt(@NotNull String updatedAt) {
      this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
      return this;
    }

    @java.lang.Override
    public PaymentProviderResponse build() {
      return new PaymentProviderResponse(id, providerName, isActive, priority, createdAt, updatedAt, additionalProperties);
    }
  }
}
