/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class SubscriptionResponseBillingTiming {
  public static final SubscriptionResponseBillingTiming IN_ARREARS = new SubscriptionResponseBillingTiming(Value.IN_ARREARS, "IN_ARREARS");

  public static final SubscriptionResponseBillingTiming IN_ADVANCE = new SubscriptionResponseBillingTiming(Value.IN_ADVANCE, "IN_ADVANCE");

  private final Value value;

  private final String string;

  SubscriptionResponseBillingTiming(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof SubscriptionResponseBillingTiming && this.string.equals(((SubscriptionResponseBillingTiming) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case IN_ARREARS:
        return visitor.visitInArrears();
      case IN_ADVANCE:
        return visitor.visitInAdvance();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static SubscriptionResponseBillingTiming valueOf(String value) {
    switch (value) {
      case "IN_ARREARS":
        return IN_ARREARS;
      case "IN_ADVANCE":
        return IN_ADVANCE;
      default:
        return new SubscriptionResponseBillingTiming(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    IN_ADVANCE,

    IN_ARREARS,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitInAdvance();

    T visitInArrears();

    T visitUnknown(String unknownType);
  }
}
