/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = WalletResponse.Builder.class
)
public final class WalletResponse {
  private final String id;

  private final String customerId;

  private final Optional<String> name;

  private final String currency;

  private final String rateAmount;

  private final String creditsBalance;

  private final String balance;

  private final String consumedCredits;

  private final String consumedAmount;

  private final WalletResponseStatus status;

  private final Optional<String> expirationAt;

  private final Optional<String> terminatedAt;

  private final Optional<WalletCustomerResponse> customer;

  private final Optional<Map<String, Object>> metadata;

  private final String createdAt;

  private final String updatedAt;

  private final Map<String, Object> additionalProperties;

  private WalletResponse(String id, String customerId, Optional<String> name, String currency,
      String rateAmount, String creditsBalance, String balance, String consumedCredits,
      String consumedAmount, WalletResponseStatus status, Optional<String> expirationAt,
      Optional<String> terminatedAt, Optional<WalletCustomerResponse> customer,
      Optional<Map<String, Object>> metadata, String createdAt, String updatedAt,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.customerId = customerId;
    this.name = name;
    this.currency = currency;
    this.rateAmount = rateAmount;
    this.creditsBalance = creditsBalance;
    this.balance = balance;
    this.consumedCredits = consumedCredits;
    this.consumedAmount = consumedAmount;
    this.status = status;
    this.expirationAt = expirationAt;
    this.terminatedAt = terminatedAt;
    this.customer = customer;
    this.metadata = metadata;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("customerId")
  public String getCustomerId() {
    return customerId;
  }

  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  @JsonProperty("currency")
  public String getCurrency() {
    return currency;
  }

  /**
   * @return 1 credit = rateAmount in currency
   */
  @JsonProperty("rateAmount")
  public String getRateAmount() {
    return rateAmount;
  }

  /**
   * @return Available credits
   */
  @JsonProperty("creditsBalance")
  public String getCreditsBalance() {
    return creditsBalance;
  }

  /**
   * @return Monetary equivalent of credits
   */
  @JsonProperty("balance")
  public String getBalance() {
    return balance;
  }

  /**
   * @return Lifetime consumed credits
   */
  @JsonProperty("consumedCredits")
  public String getConsumedCredits() {
    return consumedCredits;
  }

  /**
   * @return Lifetime consumed amount
   */
  @JsonProperty("consumedAmount")
  public String getConsumedAmount() {
    return consumedAmount;
  }

  @JsonProperty("status")
  public WalletResponseStatus getStatus() {
    return status;
  }

  @JsonProperty("expirationAt")
  public Optional<String> getExpirationAt() {
    return expirationAt;
  }

  @JsonProperty("terminatedAt")
  public Optional<String> getTerminatedAt() {
    return terminatedAt;
  }

  @JsonProperty("customer")
  public Optional<WalletCustomerResponse> getCustomer() {
    return customer;
  }

  @JsonProperty("metadata")
  public Optional<Map<String, Object>> getMetadata() {
    return metadata;
  }

  @JsonProperty("createdAt")
  public String getCreatedAt() {
    return createdAt;
  }

  @JsonProperty("updatedAt")
  public String getUpdatedAt() {
    return updatedAt;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof WalletResponse && equalTo((WalletResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(WalletResponse other) {
    return id.equals(other.id) && customerId.equals(other.customerId) && name.equals(other.name) && currency.equals(other.currency) && rateAmount.equals(other.rateAmount) && creditsBalance.equals(other.creditsBalance) && balance.equals(other.balance) && consumedCredits.equals(other.consumedCredits) && consumedAmount.equals(other.consumedAmount) && status.equals(other.status) && expirationAt.equals(other.expirationAt) && terminatedAt.equals(other.terminatedAt) && customer.equals(other.customer) && metadata.equals(other.metadata) && createdAt.equals(other.createdAt) && updatedAt.equals(other.updatedAt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.customerId, this.name, this.currency, this.rateAmount, this.creditsBalance, this.balance, this.consumedCredits, this.consumedAmount, this.status, this.expirationAt, this.terminatedAt, this.customer, this.metadata, this.createdAt, this.updatedAt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    CustomerIdStage id(@NotNull String id);

    Builder from(WalletResponse other);
  }

  public interface CustomerIdStage {
    CurrencyStage customerId(@NotNull String customerId);
  }

  public interface CurrencyStage {
    RateAmountStage currency(@NotNull String currency);
  }

  public interface RateAmountStage {
    /**
     * <p>1 credit = rateAmount in currency</p>
     */
    CreditsBalanceStage rateAmount(@NotNull String rateAmount);
  }

  public interface CreditsBalanceStage {
    /**
     * <p>Available credits</p>
     */
    BalanceStage creditsBalance(@NotNull String creditsBalance);
  }

  public interface BalanceStage {
    /**
     * <p>Monetary equivalent of credits</p>
     */
    ConsumedCreditsStage balance(@NotNull String balance);
  }

  public interface ConsumedCreditsStage {
    /**
     * <p>Lifetime consumed credits</p>
     */
    ConsumedAmountStage consumedCredits(@NotNull String consumedCredits);
  }

  public interface ConsumedAmountStage {
    /**
     * <p>Lifetime consumed amount</p>
     */
    StatusStage consumedAmount(@NotNull String consumedAmount);
  }

  public interface StatusStage {
    CreatedAtStage status(@NotNull WalletResponseStatus status);
  }

  public interface CreatedAtStage {
    UpdatedAtStage createdAt(@NotNull String createdAt);
  }

  public interface UpdatedAtStage {
    _FinalStage updatedAt(@NotNull String updatedAt);
  }

  public interface _FinalStage {
    WalletResponse build();

    _FinalStage name(Optional<String> name);

    _FinalStage name(String name);

    _FinalStage expirationAt(Optional<String> expirationAt);

    _FinalStage expirationAt(String expirationAt);

    _FinalStage terminatedAt(Optional<String> terminatedAt);

    _FinalStage terminatedAt(String terminatedAt);

    _FinalStage customer(Optional<WalletCustomerResponse> customer);

    _FinalStage customer(WalletCustomerResponse customer);

    _FinalStage metadata(Optional<Map<String, Object>> metadata);

    _FinalStage metadata(Map<String, Object> metadata);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, CustomerIdStage, CurrencyStage, RateAmountStage, CreditsBalanceStage, BalanceStage, ConsumedCreditsStage, ConsumedAmountStage, StatusStage, CreatedAtStage, UpdatedAtStage, _FinalStage {
    private String id;

    private String customerId;

    private String currency;

    private String rateAmount;

    private String creditsBalance;

    private String balance;

    private String consumedCredits;

    private String consumedAmount;

    private WalletResponseStatus status;

    private String createdAt;

    private String updatedAt;

    private Optional<Map<String, Object>> metadata = Optional.empty();

    private Optional<WalletCustomerResponse> customer = Optional.empty();

    private Optional<String> terminatedAt = Optional.empty();

    private Optional<String> expirationAt = Optional.empty();

    private Optional<String> name = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(WalletResponse other) {
      id(other.getId());
      customerId(other.getCustomerId());
      name(other.getName());
      currency(other.getCurrency());
      rateAmount(other.getRateAmount());
      creditsBalance(other.getCreditsBalance());
      balance(other.getBalance());
      consumedCredits(other.getConsumedCredits());
      consumedAmount(other.getConsumedAmount());
      status(other.getStatus());
      expirationAt(other.getExpirationAt());
      terminatedAt(other.getTerminatedAt());
      customer(other.getCustomer());
      metadata(other.getMetadata());
      createdAt(other.getCreatedAt());
      updatedAt(other.getUpdatedAt());
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public CustomerIdStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("customerId")
    public CurrencyStage customerId(@NotNull String customerId) {
      this.customerId = Objects.requireNonNull(customerId, "customerId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("currency")
    public RateAmountStage currency(@NotNull String currency) {
      this.currency = Objects.requireNonNull(currency, "currency must not be null");
      return this;
    }

    /**
     * <p>1 credit = rateAmount in currency</p>
     * <p>1 credit = rateAmount in currency</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("rateAmount")
    public CreditsBalanceStage rateAmount(@NotNull String rateAmount) {
      this.rateAmount = Objects.requireNonNull(rateAmount, "rateAmount must not be null");
      return this;
    }

    /**
     * <p>Available credits</p>
     * <p>Available credits</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("creditsBalance")
    public BalanceStage creditsBalance(@NotNull String creditsBalance) {
      this.creditsBalance = Objects.requireNonNull(creditsBalance, "creditsBalance must not be null");
      return this;
    }

    /**
     * <p>Monetary equivalent of credits</p>
     * <p>Monetary equivalent of credits</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("balance")
    public ConsumedCreditsStage balance(@NotNull String balance) {
      this.balance = Objects.requireNonNull(balance, "balance must not be null");
      return this;
    }

    /**
     * <p>Lifetime consumed credits</p>
     * <p>Lifetime consumed credits</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("consumedCredits")
    public ConsumedAmountStage consumedCredits(@NotNull String consumedCredits) {
      this.consumedCredits = Objects.requireNonNull(consumedCredits, "consumedCredits must not be null");
      return this;
    }

    /**
     * <p>Lifetime consumed amount</p>
     * <p>Lifetime consumed amount</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("consumedAmount")
    public StatusStage consumedAmount(@NotNull String consumedAmount) {
      this.consumedAmount = Objects.requireNonNull(consumedAmount, "consumedAmount must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("status")
    public CreatedAtStage status(@NotNull WalletResponseStatus status) {
      this.status = Objects.requireNonNull(status, "status must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("createdAt")
    public UpdatedAtStage createdAt(@NotNull String createdAt) {
      this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("updatedAt")
    public _FinalStage updatedAt(@NotNull String updatedAt) {
      this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage metadata(Map<String, Object> metadata) {
      this.metadata = Optional.ofNullable(metadata);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "metadata",
        nulls = Nulls.SKIP
    )
    public _FinalStage metadata(Optional<Map<String, Object>> metadata) {
      this.metadata = metadata;
      return this;
    }

    @java.lang.Override
    public _FinalStage customer(WalletCustomerResponse customer) {
      this.customer = Optional.ofNullable(customer);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "customer",
        nulls = Nulls.SKIP
    )
    public _FinalStage customer(Optional<WalletCustomerResponse> customer) {
      this.customer = customer;
      return this;
    }

    @java.lang.Override
    public _FinalStage terminatedAt(String terminatedAt) {
      this.terminatedAt = Optional.ofNullable(terminatedAt);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "terminatedAt",
        nulls = Nulls.SKIP
    )
    public _FinalStage terminatedAt(Optional<String> terminatedAt) {
      this.terminatedAt = terminatedAt;
      return this;
    }

    @java.lang.Override
    public _FinalStage expirationAt(String expirationAt) {
      this.expirationAt = Optional.ofNullable(expirationAt);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "expirationAt",
        nulls = Nulls.SKIP
    )
    public _FinalStage expirationAt(Optional<String> expirationAt) {
      this.expirationAt = expirationAt;
      return this;
    }

    @java.lang.Override
    public _FinalStage name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public _FinalStage name(Optional<String> name) {
      this.name = name;
      return this;
    }

    @java.lang.Override
    public WalletResponse build() {
      return new WalletResponse(id, customerId, name, currency, rateAmount, creditsBalance, balance, consumedCredits, consumedAmount, status, expirationAt, terminatedAt, customer, metadata, createdAt, updatedAt, additionalProperties);
    }
  }
}
