// Code generated by Fern. DO NOT EDIT.

package coupons_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	novabillinggo "github.com/novabilling/novabilling-go"
	client "github.com/novabilling/novabilling-go/client"
	option "github.com/novabilling/novabilling-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestCouponsListWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &novabillinggo.ListCouponsRequest{}
	_, invocationErr := client.Coupons.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCouponsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCouponsListWithWireMock", "GET", "/api/coupons", nil, 1)
}

func TestCouponsCreateWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &novabillinggo.CreateCouponDto{
		Code:          "WELCOME20",
		Name:          "20% Welcome Discount",
		DiscountType:  novabillinggo.CreateCouponDtoDiscountTypePercentage,
		DiscountValue: 20,
	}
	_, invocationErr := client.Coupons.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCouponsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCouponsCreateWithWireMock", "POST", "/api/coupons", nil, 1)
}

func TestCouponsGetWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &novabillinggo.GetCouponsRequest{
		ID: "id",
	}
	_, invocationErr := client.Coupons.Get(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCouponsGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCouponsGetWithWireMock", "GET", "/api/coupons/id", nil, 1)
}

func TestCouponsDeleteWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &novabillinggo.DeleteCouponsRequest{
		ID: "id",
	}
	_, invocationErr := client.Coupons.Delete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCouponsDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCouponsDeleteWithWireMock", "DELETE", "/api/coupons/id", nil, 1)
}

func TestCouponsUpdateWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &novabillinggo.UpdateCouponDto{
		ID: "id",
	}
	_, invocationErr := client.Coupons.Update(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCouponsUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCouponsUpdateWithWireMock", "PATCH", "/api/coupons/id", nil, 1)
}

func TestCouponsApplyWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &novabillinggo.ApplyCouponDto{
		CouponID:   "couponId",
		CustomerID: "customerId",
	}
	_, invocationErr := client.Coupons.Apply(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCouponsApplyWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCouponsApplyWithWireMock", "POST", "/api/coupons/apply", nil, 1)
}

func TestCouponsRemoveAppliedWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &novabillinggo.RemoveAppliedCouponsRequest{
		ID: "id",
	}
	invocationErr := client.Coupons.RemoveApplied(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCouponsRemoveAppliedWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCouponsRemoveAppliedWithWireMock", "DELETE", "/api/coupons/applied/id", nil, 1)
}
