apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: novabilling

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - central-db.yaml
  - tenant-db.yaml
  - redis.yaml
  - api.yaml
  - worker.yaml
  - dashboard.yaml
  - landing.yaml
  - docs.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/novabilling/api
    newTag: latest
  - name: ghcr.io/novabilling/dashboard
    newTag: latest
  - name: ghcr.io/novabilling/landing
    newTag: latest
  - name: ghcr.io/novabilling/docs
    newTag: latest
