/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.apikeys;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import core.ClientOptions;
import core.MediaTypes;
import core.NovabillingApiApiException;
import core.NovabillingApiException;
import core.NovabillingApiHttpResponse;
import core.ObjectMappers;
import core.RequestOptions;
import errors.NotFoundError;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import java.lang.Void;
import java.util.List;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import resources.apikeys.requests.CreateApiKeyBodyDto;
import resources.apikeys.requests.DeleteApiKeysRequest;
import types.ApiKeyResponse;

public class RawApiKeysClient {
  protected final ClientOptions clientOptions;

  public RawApiKeysClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Retrieve all API keys for the tenant. Keys are masked for security — only the last 8 characters are shown.
   */
  public NovabillingApiHttpResponse<List<ApiKeyResponse>> list() {
    return list(null);
  }

  /**
   * Retrieve all API keys for the tenant. Keys are masked for security — only the last 8 characters are shown.
   */
  public NovabillingApiHttpResponse<List<ApiKeyResponse>> list(RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("api/tenants/me/api-keys");if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json")
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        if (response.isSuccessful()) {
          return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, new TypeReference<List<ApiKeyResponse>>() {}), response);
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (IOException e) {
        throw new NovabillingApiException("Network error executing HTTP request", e);
      }
    }

    /**
     * Generate a new API key with specified scopes. The full key is returned only once in the response — store it securely.
     */
    public NovabillingApiHttpResponse<ApiKeyResponse> create(CreateApiKeyBodyDto request) {
      return create(request,null);
    }

    /**
     * Generate a new API key with specified scopes. The full key is returned only once in the response — store it securely.
     */
    public NovabillingApiHttpResponse<ApiKeyResponse> create(CreateApiKeyBodyDto request,
        RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("api/tenants/me/api-keys");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        RequestBody body;
        try {
          body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        }
        catch(JsonProcessingException e) {
          throw new NovabillingApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
          .url(httpUrl.build())
          .method("POST", body)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json")
          .addHeader("Accept", "application/json")
          .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          if (response.isSuccessful()) {
            return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiKeyResponse.class), response);
          }
          Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
          throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
        }
        catch (IOException e) {
          throw new NovabillingApiException("Network error executing HTTP request", e);
        }
      }

      /**
       * Permanently revoke an API key. Any requests using this key will immediately fail.
       */
      public NovabillingApiHttpResponse<Void> delete(String id) {
        return delete(id,DeleteApiKeysRequest.builder().build());
      }

      /**
       * Permanently revoke an API key. Any requests using this key will immediately fail.
       */
      public NovabillingApiHttpResponse<Void> delete(String id, RequestOptions requestOptions) {
        return delete(id,DeleteApiKeysRequest.builder().build(),requestOptions);
      }

      /**
       * Permanently revoke an API key. Any requests using this key will immediately fail.
       */
      public NovabillingApiHttpResponse<Void> delete(String id, DeleteApiKeysRequest request) {
        return delete(id,request,null);
      }

      /**
       * Permanently revoke an API key. Any requests using this key will immediately fail.
       */
      public NovabillingApiHttpResponse<Void> delete(String id, DeleteApiKeysRequest request,
          RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("api/tenants/me/api-keys")
          .addPathSegment(id);if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("DELETE", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Accept", "application/json");
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
              return new NovabillingApiHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
              if (response.code() == 404) {
                throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
          }
          catch (IOException e) {
            throw new NovabillingApiException("Network error executing HTTP request", e);
          }
        }
      }
