/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.wallets;

import core.ClientOptions;
import core.RequestOptions;
import java.lang.String;
import resources.wallets.requests.CreateWalletDto;
import resources.wallets.requests.DeleteWalletsRequest;
import resources.wallets.requests.GetTransactionsWalletsRequest;
import resources.wallets.requests.GetWalletsRequest;
import resources.wallets.requests.ListWalletsRequest;
import resources.wallets.requests.TopUpWalletDto;
import resources.wallets.requests.UpdateWalletDto;
import types.PaginatedWalletResponse;
import types.PaginatedWalletTransactionResponse;
import types.TopUpResponse;
import types.WalletResponse;

public class WalletsClient {
  protected final ClientOptions clientOptions;

  private final RawWalletsClient rawClient;

  public WalletsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawWalletsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawWalletsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * List wallets, optionally filtered by customer or status.
   */
  public PaginatedWalletResponse list() {
    return this.rawClient.list().body();
  }

  /**
   * List wallets, optionally filtered by customer or status.
   */
  public PaginatedWalletResponse list(RequestOptions requestOptions) {
    return this.rawClient.list(requestOptions).body();
  }

  /**
   * List wallets, optionally filtered by customer or status.
   */
  public PaginatedWalletResponse list(ListWalletsRequest request) {
    return this.rawClient.list(request).body();
  }

  /**
   * List wallets, optionally filtered by customer or status.
   */
  public PaginatedWalletResponse list(ListWalletsRequest request, RequestOptions requestOptions) {
    return this.rawClient.list(request, requestOptions).body();
  }

  /**
   * Create a prepaid credit wallet for a customer. Optionally seed it with paid or granted credits.
   */
  public WalletResponse create(CreateWalletDto request) {
    return this.rawClient.create(request).body();
  }

  /**
   * Create a prepaid credit wallet for a customer. Optionally seed it with paid or granted credits.
   */
  public WalletResponse create(CreateWalletDto request, RequestOptions requestOptions) {
    return this.rawClient.create(request, requestOptions).body();
  }

  public WalletResponse get(String id) {
    return this.rawClient.get(id).body();
  }

  public WalletResponse get(String id, RequestOptions requestOptions) {
    return this.rawClient.get(id, requestOptions).body();
  }

  public WalletResponse get(String id, GetWalletsRequest request) {
    return this.rawClient.get(id, request).body();
  }

  public WalletResponse get(String id, GetWalletsRequest request, RequestOptions requestOptions) {
    return this.rawClient.get(id, request, requestOptions).body();
  }

  /**
   * Terminate a wallet. Remaining credits are voided.
   */
  public WalletResponse delete(String id) {
    return this.rawClient.delete(id).body();
  }

  /**
   * Terminate a wallet. Remaining credits are voided.
   */
  public WalletResponse delete(String id, RequestOptions requestOptions) {
    return this.rawClient.delete(id, requestOptions).body();
  }

  /**
   * Terminate a wallet. Remaining credits are voided.
   */
  public WalletResponse delete(String id, DeleteWalletsRequest request) {
    return this.rawClient.delete(id, request).body();
  }

  /**
   * Terminate a wallet. Remaining credits are voided.
   */
  public WalletResponse delete(String id, DeleteWalletsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.delete(id, request, requestOptions).body();
  }

  /**
   * Update wallet name, expiration, or metadata.
   */
  public WalletResponse update(String id) {
    return this.rawClient.update(id).body();
  }

  /**
   * Update wallet name, expiration, or metadata.
   */
  public WalletResponse update(String id, RequestOptions requestOptions) {
    return this.rawClient.update(id, requestOptions).body();
  }

  /**
   * Update wallet name, expiration, or metadata.
   */
  public WalletResponse update(String id, UpdateWalletDto request) {
    return this.rawClient.update(id, request).body();
  }

  /**
   * Update wallet name, expiration, or metadata.
   */
  public WalletResponse update(String id, UpdateWalletDto request, RequestOptions requestOptions) {
    return this.rawClient.update(id, request, requestOptions).body();
  }

  /**
   * Add paid/granted credits or void existing credits from a wallet.
   */
  public TopUpResponse createTransaction(TopUpWalletDto request) {
    return this.rawClient.createTransaction(request).body();
  }

  /**
   * Add paid/granted credits or void existing credits from a wallet.
   */
  public TopUpResponse createTransaction(TopUpWalletDto request, RequestOptions requestOptions) {
    return this.rawClient.createTransaction(request, requestOptions).body();
  }

  public PaginatedWalletTransactionResponse getTransactions(String id) {
    return this.rawClient.getTransactions(id).body();
  }

  public PaginatedWalletTransactionResponse getTransactions(String id,
      RequestOptions requestOptions) {
    return this.rawClient.getTransactions(id, requestOptions).body();
  }

  public PaginatedWalletTransactionResponse getTransactions(String id,
      GetTransactionsWalletsRequest request) {
    return this.rawClient.getTransactions(id, request).body();
  }

  public PaginatedWalletTransactionResponse getTransactions(String id,
      GetTransactionsWalletsRequest request, RequestOptions requestOptions) {
    return this.rawClient.getTransactions(id, request, requestOptions).body();
  }
}
