/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.portal;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import core.ClientOptions;
import core.NovabillingApiApiException;
import core.NovabillingApiException;
import core.NovabillingApiHttpResponse;
import core.ObjectMappers;
import core.QueryStringMapper;
import core.RequestOptions;
import errors.BadRequestError;
import errors.NotFoundError;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import java.lang.Void;
import java.util.List;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import resources.portal.requests.CreateCheckoutPortalRequest;
import resources.portal.requests.GetBillingPortalRequest;
import resources.portal.requests.GetInvoicesPortalRequest;
import resources.portal.requests.GetPaymentsPortalRequest;
import resources.portal.requests.GetSubscriptionsPortalRequest;
import types.CheckoutResponse;
import types.PaginatedInvoiceResponse;
import types.PaginatedPaymentResponse;
import types.SubscriptionResponse;

public class RawPortalClient {
  protected final ClientOptions clientOptions;

  public RawPortalClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Returns subscriptions, recent invoices, payments, and summary stats for a customer. Use this to render a billing dashboard for your end-users.
   */
  public NovabillingApiHttpResponse<Void> getBilling(String externalId) {
    return getBilling(externalId,GetBillingPortalRequest.builder().build());
  }

  /**
   * Returns subscriptions, recent invoices, payments, and summary stats for a customer. Use this to render a billing dashboard for your end-users.
   */
  public NovabillingApiHttpResponse<Void> getBilling(String externalId,
      RequestOptions requestOptions) {
    return getBilling(externalId,GetBillingPortalRequest.builder().build(),requestOptions);
  }

  /**
   * Returns subscriptions, recent invoices, payments, and summary stats for a customer. Use this to render a billing dashboard for your end-users.
   */
  public NovabillingApiHttpResponse<Void> getBilling(String externalId,
      GetBillingPortalRequest request) {
    return getBilling(externalId,request,null);
  }

  /**
   * Returns subscriptions, recent invoices, payments, and summary stats for a customer. Use this to render a billing dashboard for your end-users.
   */
  public NovabillingApiHttpResponse<Void> getBilling(String externalId,
      GetBillingPortalRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("api/portal/customers")
      .addPathSegment(externalId)
      .addPathSegments("billing");if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        if (response.isSuccessful()) {
          return new NovabillingApiHttpResponse<>(null, response);
        }
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        try {
          if (response.code() == 404) {
            throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (IOException e) {
        throw new NovabillingApiException("Network error executing HTTP request", e);
      }
    }

    /**
     * Returns all subscriptions for the customer with plan details.
     */
    public NovabillingApiHttpResponse<List<SubscriptionResponse>> getSubscriptions(
        String externalId) {
      return getSubscriptions(externalId,GetSubscriptionsPortalRequest.builder().build());
    }

    /**
     * Returns all subscriptions for the customer with plan details.
     */
    public NovabillingApiHttpResponse<List<SubscriptionResponse>> getSubscriptions(
        String externalId, RequestOptions requestOptions) {
      return getSubscriptions(externalId,GetSubscriptionsPortalRequest.builder().build(),requestOptions);
    }

    /**
     * Returns all subscriptions for the customer with plan details.
     */
    public NovabillingApiHttpResponse<List<SubscriptionResponse>> getSubscriptions(
        String externalId, GetSubscriptionsPortalRequest request) {
      return getSubscriptions(externalId,request,null);
    }

    /**
     * Returns all subscriptions for the customer with plan details.
     */
    public NovabillingApiHttpResponse<List<SubscriptionResponse>> getSubscriptions(
        String externalId, GetSubscriptionsPortalRequest request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("api/portal/customers")
        .addPathSegment(externalId)
        .addPathSegments("subscriptions");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          if (response.isSuccessful()) {
            return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, new TypeReference<List<SubscriptionResponse>>() {}), response);
          }
          Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
          throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
        }
        catch (IOException e) {
          throw new NovabillingApiException("Network error executing HTTP request", e);
        }
      }

      /**
       * Returns a paginated list of invoices. Filter by status to show only pending invoices.
       */
      public NovabillingApiHttpResponse<PaginatedInvoiceResponse> getInvoices(String externalId) {
        return getInvoices(externalId,GetInvoicesPortalRequest.builder().build());
      }

      /**
       * Returns a paginated list of invoices. Filter by status to show only pending invoices.
       */
      public NovabillingApiHttpResponse<PaginatedInvoiceResponse> getInvoices(String externalId,
          RequestOptions requestOptions) {
        return getInvoices(externalId,GetInvoicesPortalRequest.builder().build(),requestOptions);
      }

      /**
       * Returns a paginated list of invoices. Filter by status to show only pending invoices.
       */
      public NovabillingApiHttpResponse<PaginatedInvoiceResponse> getInvoices(String externalId,
          GetInvoicesPortalRequest request) {
        return getInvoices(externalId,request,null);
      }

      /**
       * Returns a paginated list of invoices. Filter by status to show only pending invoices.
       */
      public NovabillingApiHttpResponse<PaginatedInvoiceResponse> getInvoices(String externalId,
          GetInvoicesPortalRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("api/portal/customers")
          .addPathSegment(externalId)
          .addPathSegments("invoices");if (request.getStatus().isPresent()) {
            QueryStringMapper.addQueryParameter(httpUrl, "status", request.getStatus().get(), false);
          }
          if (request.getPage().isPresent()) {
            QueryStringMapper.addQueryParameter(httpUrl, "page", request.getPage().get(), false);
          }
          if (request.getLimit().isPresent()) {
            QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
          }
          if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Accept", "application/json");
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PaginatedInvoiceResponse.class), response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
          }
          catch (IOException e) {
            throw new NovabillingApiException("Network error executing HTTP request", e);
          }
        }

        /**
         * Initiates a payment session with the configured payment provider. Returns a checkout URL to redirect the customer to.
         */
        public NovabillingApiHttpResponse<CheckoutResponse> createCheckout(String externalId,
            String invoiceId) {
          return createCheckout(externalId,invoiceId,CreateCheckoutPortalRequest.builder().build());
        }

        /**
         * Initiates a payment session with the configured payment provider. Returns a checkout URL to redirect the customer to.
         */
        public NovabillingApiHttpResponse<CheckoutResponse> createCheckout(String externalId,
            String invoiceId, RequestOptions requestOptions) {
          return createCheckout(externalId,invoiceId,CreateCheckoutPortalRequest.builder().build(),requestOptions);
        }

        /**
         * Initiates a payment session with the configured payment provider. Returns a checkout URL to redirect the customer to.
         */
        public NovabillingApiHttpResponse<CheckoutResponse> createCheckout(String externalId,
            String invoiceId, CreateCheckoutPortalRequest request) {
          return createCheckout(externalId,invoiceId,request,null);
        }

        /**
         * Initiates a payment session with the configured payment provider. Returns a checkout URL to redirect the customer to.
         */
        public NovabillingApiHttpResponse<CheckoutResponse> createCheckout(String externalId,
            String invoiceId, CreateCheckoutPortalRequest request, RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("api/portal/customers")
            .addPathSegment(externalId)
            .addPathSegments("invoices")
            .addPathSegment(invoiceId)
            .addPathSegments("checkout");if (requestOptions != null) {
              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
              } );
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("POST", RequestBody.create("", null))
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Accept", "application/json");
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            try (Response response = client.newCall(okhttpRequest).execute()) {
              ResponseBody responseBody = response.body();
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              if (response.isSuccessful()) {
                return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CheckoutResponse.class), response);
              }
              try {
                if (response.code() == 400) {
                  throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
            }
            catch (IOException e) {
              throw new NovabillingApiException("Network error executing HTTP request", e);
            }
          }

          /**
           * Returns a paginated list of all payments made by the customer.
           */
          public NovabillingApiHttpResponse<PaginatedPaymentResponse> getPayments(
              String externalId) {
            return getPayments(externalId,GetPaymentsPortalRequest.builder().build());
          }

          /**
           * Returns a paginated list of all payments made by the customer.
           */
          public NovabillingApiHttpResponse<PaginatedPaymentResponse> getPayments(String externalId,
              RequestOptions requestOptions) {
            return getPayments(externalId,GetPaymentsPortalRequest.builder().build(),requestOptions);
          }

          /**
           * Returns a paginated list of all payments made by the customer.
           */
          public NovabillingApiHttpResponse<PaginatedPaymentResponse> getPayments(String externalId,
              GetPaymentsPortalRequest request) {
            return getPayments(externalId,request,null);
          }

          /**
           * Returns a paginated list of all payments made by the customer.
           */
          public NovabillingApiHttpResponse<PaginatedPaymentResponse> getPayments(String externalId,
              GetPaymentsPortalRequest request, RequestOptions requestOptions) {
            HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("api/portal/customers")
              .addPathSegment(externalId)
              .addPathSegments("payments");if (request.getPage().isPresent()) {
                QueryStringMapper.addQueryParameter(httpUrl, "page", request.getPage().get(), false);
              }
              if (request.getLimit().isPresent()) {
                QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
              }
              if (requestOptions != null) {
                requestOptions.getQueryParameters().forEach((_key, _value) -> {
                  httpUrl.addQueryParameter(_key, _value);
                } );
              }
              Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
              Request okhttpRequest = _requestBuilder.build();
              OkHttpClient client = clientOptions.httpClient();
              if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
              }
              try (Response response = client.newCall(okhttpRequest).execute()) {
                ResponseBody responseBody = response.body();
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                if (response.isSuccessful()) {
                  return new NovabillingApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PaginatedPaymentResponse.class), response);
                }
                Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                throw new NovabillingApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
              }
              catch (IOException e) {
                throw new NovabillingApiException("Network error executing HTTP request", e);
              }
            }
          }
